### ISSUE TITLE
schema updates

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#103]
here is the biccn discussion on the schema, which should update our schema. i.e. we will need a path to update dandiset.yaml as the schema changes. so dandiset.yaml should also have schema-version in it.

https://github.com/BICCN/BICCN-Infrastructure-Draft/pull/15/files

@AlmightyYakob - please see the comment on the roles section to add a list of roles to the schema.

please add a README here: https://github.com/dandi/dandiarchive/tree/master/web/src/assets/schema 
so we know which schemas are being used for what. if some schemas are not being used, let's delete them. they can always be recovered from git history.

@yarikoptic has created a project for dandi-core that can be used as a submodule to dandiarchive. we can move common things there so that they can be used by multiple projects. schemas seem like a good thing to move there.

**Comment by satra** [comment]
@AlmightyYakob - i don't think this was communicated after @mgrauer and i edited this file:

https://github.com/BICCN/BICCN-Infrastructure-Draft/blob/ce0df09b310bbcdd0a7a63cc51a0955e3cae97b8/BICCN-policies/dataset-metadata.yaml

the schema should be updated to reflect the keys/options from this file. the file is visually divided into 3 sections. the first section should all be available as part of the human metadata entry through the DLP

**Comment by AlmightyYakob** [comment]
@satra in reference to this line:

https://github.com/BICCN/BICCN-Infrastructure-Draft/blob/ce0df09b310bbcdd0a7a63cc51a0955e3cae97b8/BICCN-policies/dataset-metadata.yaml#L6

We seem to have everything except "datacite", is that correct? I.e. should I add the role "Datacite" to the list of allowed roles?

**Comment by satra** [comment]
@AlmightyYakob - i think @mgrauer sent you that list from the google doc, which we also curated during that call. so that should be all set.

**Comment by satra** [comment]
from slack (cc: @yarikoptic @mgrauer):

- let's add an annotation key/field as a list of notes.
- each note should be a text-area field

ideally each note should be a structured key:

```
- annotation:
   - description: (text area to provide information)
      user: (logged in user)
      timestamp: timestamp of note
   - description:
...
```

cc:

**Comment by AlmightyYakob** [comment]
> ```
> - annotation:
>    - description: (text area to provide information)
>       user: (logged in user)
>       timestamp: timestamp of note
>    - description:
> ...
> ```

So the user and timestamp fields would be autogenerated?

**Comment by satra** [comment]
> So the user and timestamp fields would be autogenerated?

yes

**Comment by satra** [comment]
we can punt annotation till after this week, but schema alignment is more critical

**Comment by mgrauer** [comment]
Examples of schema mismatch are:
 - license doesn't have a fixed set of choices
 - publications is not listed

**Comment by satra** [comment]
@Jake Nesbitt - while we do want the current updates in so we can view and enter the metadata, i wanted to mention that we are likely to move to many of the components in the dats model (https://github.com/datatagsuite/schema/blob/master/README.md) over the next few weeks. i am hoping that we will have a clean-ish upgrade path from the current schema to customized version of dats for dandi. overall the plan will be to align, with some specific elements set aside for dandi. 

many things are already similar, but i will spend some specific time to make that alignment cleaner.

i also expect this to be more of an evolution over time, so the process should be made as simple as possible for the dandi team to update both schema and ui components. 

again, this should not affect your current PRs which are much needed, but to consider your experience with them in laying out a pathway for the future.

**Comment by AlmightyYakob** [comment]
@satra Am I good to close this issue, since #173 was merged?

**Comment by satra** [comment]
@AlmightyYakob - yes let's close this now. we can open a new one after our call on Monday.
