### ISSUE TITLE
metadata editor

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#104]
1. After editing the metadata, clicking on save does not save the metadata
2. The only way to return to the previous screen is to hit cancel
3. Roles should be a drop down list or pillbox with appropriate roles.
4. any orcid id should be verified with the orcid api.
5. right after i entered an author role with an orcid , the publish button came online. at present, till we have implemented validation, publish should be disabled from view.

**Comment by satra** [comment]
a few updates. 

- the reason i couldn't save was because i was not logged in. should have warned or disabled save or forced to log in before editing.
- changing the name of the metadata does not alter the name of the folder
- asks for an identifier when editing metadata. this should be read only and refer to the created id.

**Comment by mgrauer** [comment]
* The dandiset `id` field:
   * should not be editable in the metadata editor
   * should be `identifier`, not `id`
   * We will need to migrate existing data
 * Move validation errors to be inline with the field that is invalid
 * Make `roles` a multiselect with the following options for now:
```
Author
Conceptualization
ContactPerson
Data Collector
DataCurator
DataManager
Formal Analysis
Funding acquisition
Investigation
Maintainer
Methodology
Producer
ProjectLeader
ProjectManager
ProjectMember
Project administration
Researcher
Resources
Software
Supervision
Validation
Visualization
Other - ideally also would prompt a text box and allow free form entry, for now, fine if Other
```

**Comment by mgrauer** [comment]
* Remove `publish` button from metadata editor
