### ISSUE TITLE
Make girder metadata records "structured"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#105]
ATM, metadata editor for a dataset dumps the record straight as a metadata of that folder, see e.g. https://girder.dandiarchive.org/#collection/5e59bb0af19e820ab6ea6c62/folder/5e5c0c6c513f45fe78c07491 .  For the files uploaded by `dandi-cli` I was dumping into the first level not only metadata extracted from nwb files, but also `uploaded_*` fields and might later add additional auxiliary records such as `checksums`.  Partially that was done because the `gui.'s` search implementation ATM considers only flat structure.
I think it would be worthwhile making metadata record more structured, by not (ab)using first level, making it hard to separate different types of metadata, but adding top level sections:

- `dandi`: for the top folder of a dandiset it would be the dandiset level metadata record (mirroring `dandiset.yaml` content).  For a file - file metadata, e.g. extracted and uploaded by `dandi upload`
- `dandi-client`: anything dandi client(s) would like to communicate.  E.g. it could be the `uploaded-*` fields, which would allow to identify if file was modified by girder (by comparing mtime of the file asset, or relying on checksums). We could later extend this record with e.g. `history` for https://github.com/dandi/dandi-cli/issues/43 or any other information which is not directly data "metadata", but rather metadata to assist our technologies.

It might be that when/if we decide to implement some other solutions, like versioning, having flexibility of extending metadata records with top-level entries could be of help to assist with experimentation, and later migrations from one scheme to another (e.g. that `history` into something more generic like `dandi-versioning`)

**Comment by yarikoptic** [comment]
actually we might even split `dandi` into two `dandiset` and `dandifile` to make it explicit from metadata record alone what schema to validate that entry against (for a file vs for a dandiset).

**Comment by mgrauer** [comment]
I agree we should make this structured.

@AlmightyYakob and I have constructed a metadata schema for Girder folders that are dandisets, that currently looks like this, as in #120. We only have draft dandisets so far.

```
meta
    dandiset
        identifier: '000000'
        version: 'draft'
        name: 'dandiset name'
        description: 'dandiset description'
```

**Comment by yarikoptic** [comment]
Fwiw I will repeat my dislike of anything but semantic (or some other sensible, eg date based?) version as a version. At least it could be based on semantic version eg `0.0.0.draft` when no version released, and otherwise be there .draft suffix attached to the last released version

**Comment by satra** [comment]
eventually we can get to something like:
```
$ git describe
1.4.2-118-gb75a7cebc
```
where the last bit could be the current checksum. but we can't make dandiset.yaml have a checksum if the checksum includes dandiset.yaml. but metadata could hold the checksum.

semantic versioning always is about the next version you are going to release e.g., 0.0.1-draft on release becomes 0.0.1.  so version updating happens within the draft folder.  if i make some drastic changes it becomes 0.1.0-draft or even more drastic changes it could become 1.0.0-draft. so we would expect people to update versions during the drafting stage. that could get complicated unless we provide a clear path for users. most neuroscientists would not be familiar with this approach. 

semantic versioning was created for code/API/software, and we would need to determine for the users what would be the corresponding levels of public API, API change, etc.,. would be for datasets.

**Comment by yarikoptic** [comment]
> semantic versioning always is about the next version you are going to release

Yes and no ;)

## Yes -- "hyphen" 

Indeed [9. A pre-release version..](https://semver.org/#spec-item-9) describes `-`separated suffixes.  The convention I had never seen used in the wild!  :
- `git describe` output (although that one is nowhow promised to follow semver) doesn't follow it either.
-  In Debian, there is only `mu-editor` package which depends on python3-semver.
- [Python](https://www.python.org/dev/peps/pep-0440/#compatibility-with-other-version-schemes) came up with its own convention(s) for pre-releases, and distutils StrictVersion would puke on such, and LooseVersion would treat `-` as an addition:

```
> python -c 'from distutils.version import StrictVersion as SV, LooseVersion as LV; print(SV("2.4-1"))'
...
ValueError: invalid version number '2.4-1'

$> python -c 'from distutils.version import StrictVersion as SV, LooseVersion as LV; print(LV("2.4-1") < LV("2.4"))'
False
```
- which is more inline with `git` and Debian treatment -- that adding additional components (in Debian -- a Debian revision) after `-` means 

## No -- "plus"

[10. Build metadata](https://semver.org/#spec-item-10) allows for `<version core> "+" <build>`.  So if we were to stick with semver (and not Python's versioning) we could use it to annotate draft, e.g. `0.0.0+draft`.   I use "+" for debian package build version composition from `git describe`, e.g. for `0.3.0-5-gcf05739` it would become `0.3.0+git5-gcf05739`.  `distutils.LooseVersion` handles it welll
```
$> python -c 'from distutils.version import StrictVersion as SV, LooseVersion as LV; print(LV("2.4") < LV("2.4+git5-gcfg05"))'
True
```
but khe khe -- `semver` disregards `build` in comparison:
```
In [6]: semver.compare('0.1.0+draft', '0.1.0')                                                                          
Out[6]: 0

In [7]: semver.compare('0.1.0', '0.1.0+draft')                                                                          
Out[7]: 0
```

So -- the "jury" is still out for the exact convention we would like to use, but it shouldn't be a "draft", even though LooseVersion seems to tollerate it well (assuming that our draft is always the latest):
```
$> python -c 'from distutils.version import StrictVersion as SV, LooseVersion as LV; print(LV("0.0.1") < LV("draft"))'
True
```
IMHO it would be best to leave it empty if there is no version assigned, although for post-release versions it would be suboptimal.

## Idea: abuse/automate PATCH

If we tried to stay inline with semver -- we could use a convention to use `.0` PATCH for released versions and `.1`  for unreleased (draft); and increment MINOR (or MAJOR.MINOR) for any release.  So - start with `0.0.1`, and then go to `0.1.0` released and `0.1.1` in the draft.  Even now, upon each upload to a dandiset, `dandi cli` could automagically increment PATCH in the version in the record.  Then, we would get sensible progression of the versions.  We could increment  at the beginning of the upload so if interrupted we would be no worse but only better annotating changes.

**Comment by mgrauer** [comment]
I haven't read the last few comments in detail, but I had been thinking about this last night. A couple high level thoughts:
 * let's use date based versions as that is well defined, whereas semver is not for datasets (which one can everyone agree on the semantics of without further discussion?)
 * `draft` is not a version, as you cannot ever get back to a specific point it time. So maybe it doesn't make sense to have draft as a version.

**Comment by mgrauer** [comment]
I think this has been accomplished. If you feel something is still outstanding, please clarify and reopen. Or better yet, open a new more specific issue, as I think we drifted around in scope on this issue.
