### ISSUE TITLE
"id" vs "identifier" - we need to converge or diverge ;)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#107]
our schema (https://github.com/dandi/dandiarchive/blob/master/web/src/assets/schema/base.json) has `identifier`, not `id`.  https://github.com/dandi/dandiarchive/blob/master/girder-dandi-archive/girder_dandi_archive/rest.py populates and uses in the route `id` not `identifier`.  That leads to having both in the metadata: see https://girder.dandiarchive.org/#collection/5e59bb0af19e820ab6ea6c62/folder/5e5c0c6c513f45fe78c07491 currently having 

```
  "id": "000001",
  "identifier": "000001",
```

Are those (`id` vs `identifier`) to be the same thing, or different?  If the same -- we should unify, probably into `id` since shorter etc (thus - adjust `schema/base.json`).  If different, e.g. `identifier` would be something like an identifier from identifiers.org, then should become `dandi:{id}/staging` (which we then change to the versioned one upon publish), but then we would need to keep both `id` and `identifier` fields in metadata (and thus schema).

attn: @satra @mgrauer

**Comment by AlmightyYakob** [comment]
I believe they're supposed to be the same (per my conversation with Satra).

**Comment by yarikoptic** [comment]
Ok, let's wait for @satra - I see no reason to keep two identical values with different names in the metadata.

**Comment by satra** [comment]
let's just keep `identifier` and `version`, which if not there should be there and set to `staging` for now for a staged dandiset.

**Comment by yarikoptic** [comment]
I really dislike arbitrary strings in a `version` string, which is expected to contain some semver.  Better keep it empty if version is not "set" for that dataset.

By "keep `identifier`" - do you mean "replace `id` with `identifier`" or what exactly?  just keep them both lingering around with identical value, but use `id` for rest API etc?

**Comment by satra** [comment]
yes, keep the key `identifier` only.

for `version`, i'm thinking github, which has versions other than semver. so i'm ok with `staging` for now. unless you want to use `master`
