### ISSUE TITLE
DLP - instructions for next steps

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#119]
On the dataset landing page (and only for collaborators on the dataset) we should create a collapsable sidebar that describes the instructions for the next steps:

1. filling the rest of the metadata
2. installing the python CLI (@yarikoptic - we should publish this to conda as well)
3. using the CLI to organize and upload. 

It should also contain instructions for how to contact the team to be added as a collaborator to the dataset.

For download (this would be available for all), there should be a separate page with explicit instructions for how to download the data using the CLI.

**Comment by djarecka** [comment]
@satra - I think most or all of the items are already implemented. I'm not completely sure about the "instructions for how to contact the team to be added", contact person is not enough?
Please close or comment/update.

**Comment by waxlamp** [comment]
This kind of thing is covered by the "empty states" designs that @jtomeck has included in the DLP redesign mockups. We may need more than is seen there, but it would be good to update this issue with new thoughts about how to proceed based on those designs.

**Comment by satra** [comment]
let's close this issue for now. between adding intro.js to code, updating the handbook, and the empty states instructions, this should be covered.
