### ISSUE TITLE
Document dandiarchive setup

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#12]
Not including details now, just placeholders to come back and fill in more.

- mailgun
- dns
- github oauth
- ansible
  - girder
  - nginx
  - letsencrypt
  - mongo
- EC2 instance props
- S3 bucket and role
- circle ci + ansible
- netlify

TODOs:
- [x] account info on mailgun
- [x] specific DNS entries that have been added (if this makes sense to do and is not redundant with the DNS itself; perhaps just a quick listing of what DNS entries are for what services)
- [x] how to install girder dandi archive plugin for local dev
- [x] what are the CORS settings on the public data S3 bucket for Girder, what are the settings on Girder for the S3 bucket (this may be redundant with the Girder assetstore setup)

**Comment by mgrauer** [comment]
As part of this, reproduce netlify setup with the dandibot GH oauth account

**Comment by mgrauer** [comment]
Describe how the girder plugin is installed via sdist and ansible, and how it can be installed locally for dev, this local dev part should also go into th ereadme. 
Sentry on the client and server.
How Circle builds the client and pushes to netlify.
The use of dandibot. 
What DNS entries are there for Girder, for gui on netlify, for mail entries for Girder/mailgun.

**Comment by mgrauer** [comment]
CORS and env vars settings, on S3 bucket, and Girder for netlify.

**Comment by mgrauer** [comment]
We have an initial doc to cover this https://github.com/dandi/dandiarchive/blob/master/DEPLOYMENT.md.

Update that doc with further details:

- account info on mailgun
- specific DNS entries that have been added (if this makes sense to do and is not redundant with the DNS itself; perhaps just a quick listing of what DNS entries are for what services)
- how to install girder dandi archive plugin for local dev
- what are the CORS settings on the public data S3 bucket for Girder, what are the settings on Girder for the S3 bucket (this may be redundant with the Girder assetstore setup)

**Comment by yarikoptic** [comment]
I have copied @mgrauer 's items into initial description as check boxes, so we could see what is left todo to have this one closed

**Comment by yarikoptic** [comment]
I would be really interested to see this going forward, so I could try deploying locally for testing and possible development.
