### ISSUE TITLE
Restructure tests for create and get dandiset endpoints

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#126]
I won't have time right away to restructure the tests in response to QA for #120, so I'm breaking that restructuring out into a separate issue. This way we can get the endpoint changes in sooner without this additional work blocking, as we are pushing to have all of the beta features come together soon.

**Comment by brianhelba** [comment]
@mgrauer I asked @dchiquit to work on this now, since a lot of his other WIP features will need to add tests, and new fixtures / organization will benefit those tests too.

**Comment by mgrauer** [comment]
That makes me sad because I was hoping to do it someday, but this is the right choice. Thanks.
