### ISSUE TITLE
identifier error on landing page

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#127]
![image](https://user-images.githubusercontent.com/184063/76245043-94e19800-6211-11ea-83c9-aac5ffc0aa5a.png)

**Comment by mgrauer** [comment]
At least one reason this is happening is that dataset has an `id` field and not an `identifier` field. This aspect will be fixed when we merge #120 and do a data migration.

**Comment by mgrauer** [comment]
This has been fixed.
