### ISSUE TITLE
DLP does not have a permalink URL

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#130]
i only saw a permalink URL for an older dataset. any newly registered dataset does not have a permalink URL on the DLP

**Comment by mgrauer** [comment]
This one is a show-stopper for the beta launch.

**Comment by AlmightyYakob** [comment]
@satra could you give a specific example? Is this on gui.dandiarchive.org? This is most likely the `id` vs `identifier` issue, I don't see an example on there that isn't caused by this
