### ISSUE TITLE
AppBar UI looks weird when viewport is narrow.

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#131]
see the dandi icon and the search bar in the image below.

![image](https://user-images.githubusercontent.com/184063/76329621-32e16b00-62c3-11ea-8e9a-1775aa42ea08.png)

**Comment by mgrauer** [comment]
This will become a moot issue with the UI redesign. This issue does capture an important notion: that generally we expect people will interact with the app from a desktop browser, but that they are likely to first load the app on a browser in their phone, and so the landing page and about page views should look good for typical phone widths (if such a thing is meaningful).

**Comment by mgrauer** [comment]
Fixed.
