### ISSUE TITLE
Set user quotas to 0

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#145]

**Comment by mgrauer** [comment]
You'll need to [install the plugin](https://github.com/dandi/dandiarchive/blob/master/ansible/playbook.yml#L44) `girder-user-quota` and then when it is installed, one of the Girder admins can set the user quota to 0.

**Comment by brianhelba** [comment]
We should probably auto-set this to 0 as part of the plugin load process, rather than rely on an admin to do it on every deployment.

**Comment by dchiquit** [comment]
From the README:
> Set CORS settings so that the vue client can talk to the Girder server (http://localhost:8080/#settings). In the "Advanced Settings" set the "CORS Allowed Origins" value to "*" and save.

This should be removed from the README and added to the plugin load step along with the other settings.

**Comment by dchiquit** [comment]
Current work to do is:
* On plugin load, set the CORS setting to *
* On plugin load, set the `Create default folders for new users` to No
* Add `girder-user-quota` to the requirements
* On plugin load, set the user quote to 0 using the `girder-user-quota`
