### ISSUE TITLE
Metadata editor: Switching between YAML and JSON keeps only "JSON"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#147]
title is somewhat "incorrect" because
- YAML is superset of JSON so displayed JSON view is legit YAML ;-)
- also someone could argue that the select is only for the format to Download not to display, but imho it is misleading and view should adjust dynamically between JSON and YAML since UI suggests it being possible

![DeepinScreenshot_select-area_20200313191428](https://user-images.githubusercontent.com/39889/76668528-12820c80-6560-11ea-8290-bc3591618f9c.png)

**Comment by satra** [comment]
perhaps we could disable the json/yaml view and download. not particularly useful at this point, given our present workflow.

**Comment by satra** [comment]
closing - no longer relevant.
