### ISSUE TITLE
disable download at folder level

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#148]
given the sizes of some of the datasets, can we disable download  for anything that is not an item.

we could instead pop a dialog to use the dandi cli instead.

**Comment by satra** [comment]
for now i think clicking on download should open a dialog that instructs the person to use dandi cli

```
Please use the DANDI python command line utility to download this item.

dandi download <url of item>

You can install the CLI with the command:  `pip install dandi`
```

if the item is a dandiset folder, the permalink (e.g., https://dandiarchive.org/dandiset/000001/draft) should be used, if not the a folder/item specific url can be used (e.g., https://gui.dandiarchive.org/#/folder/5e6e742576569eb93f451e51)

**Comment by mgrauer** [comment]
Fixed
