### ISSUE TITLE
Tag some version (e.g. 0.1.0) of current state

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#150]
ATM there is no tags, `git describe` cannot work without `--always`

**Comment by yarikoptic** [comment]
it is really not that hard ;-)  May be since it is still very volatile, could include the date, what about

```shell
git tag -m "A snapshot release at some deployed state" 0.1.`date +"20%y%m%d"`
git push origin --tags
```

**Comment by yarikoptic** [comment]
Please?  I do not think that `0.` versions of any kind is a strong promise of any API stability etc.  I would even like the above "dateish" style to give a better perspective while looking at versions recorded somewhere.
The reason I am asking is because it becomes hard to impossible (could use hexsha of commit but those provide no perspective without lookup) to annotate for changes in gui.dandiarchive.org within dandi-cli.  If you need assistance in running the above command, please let me know ;-)

**Comment by mgrauer** [comment]
Sorry to leave you hanging on this. I don't think I get what you are looking for.

Are you looking for a tag in the repo or a tag tied the deployed software or what?

I definitely want to make as few promises of API stability as possible, especially right now. At this point we don't have any API stability on this repo, and the only API we are claiming to support on dandiarchive.org right now (to my knowledge) is like `https://dandiarchive.org/dandiset/000004/draft`.

>The reason I am asking is because it becomes hard to impossible (could use hexsha of commit but those provide no perspective without lookup) to annotate for changes in gui.dandiarchive.org within dandi-cli.

Can you explain what you mean by this? Like what is your workflow and where are you running into friction?

**Comment by satra** [comment]
i should also note that api will not come from gui.dandiarachive.org since it is a client side app (it cannot be called with curl for example). it will at present come from redirector service and whatever the future architecture holds of that service.

we are providing a couple of endpoints right now:

```
https://dandiarchive.org/dandiset/drafts --> public dashboard page
https://dandiarchive.org/dandiset/[identifier]/[whatever-at-the-moment] --> dandiset landing page
```

after the schema is versioned, i was going to add content negotiation capability to return metadata. i could add a service info api, but i think we should perhaps have the api discussion call soon.

**Comment by yarikoptic** [comment]
> > The reason I am asking is because it becomes hard to impossible (could use hexsha of commit but those provide no perspective without lookup) to annotate for changes in gui.dandiarchive.org within dandi-cli.
> 
> Can you explain what you mean by this? Like what is your workflow and where are you running into friction?

`dandi-cli` ATM is tightly linked to the dandiarchive.org . While annotating for changes in dandi-cli (e.g. in commit messages which I am trying to have informative or upcoming changelog) I would like to state for which version of dandiarchive web UI those changes are pertinent. But I cannot. I can only say "today's version" or copy paste the hexsha of currently deployed (which might change in a minute) instance.  Having a version associated with current state of gui.dandiarchive.org would allow me to say instead of "just released" a "version 0.1" or alike, and later if needed to be able to diff e.g. `0.1..0.2` to spot what differences in URLs etc were introduced between two versions. Now I would need to match commits to two dates I would like to compare or start recording hexsha which would be ugly.
It would have been also nice if at some point CHANGELOG has appeared annotating at least major changes between two different versions, such as what functionality was removed/added or what major aspects have changed.
So the friction point is that I do not quite grasp why releases are rolled out without annotating at least major refactoring points with release versions which I kept asking about.

**Comment by yarikoptic** [comment]
> Are you looking for a tag in the repo or a tag tied the deployed software or what?

tag in the repo. Aren't we deploying straight from the master, and not e.g. upon pushing a new tag so it would also be the "deployed software" as in our single instance ATM?
As for querying deployed instance, separate issue -- see #316

**Comment by yarikoptic** [comment]
hand twisting in action -- I am placing a mental cron job of "sleep 36000 && git tag -m "New web ui supporting releases and other UI enhancements" 0.1.0 && git push origin 0.1.0" .

**Comment by mgrauer** [comment]
https://github.com/dandi/dandiarchive/releases/tag/0.1.0

I've pushed this tag, although I don't think the notion of a semantic version is well defined for a repo that contains provisioning code, a docker-compose, a web gui, and a plugin providing rest endpoints.

**Comment by yarikoptic** [comment]
Woohoo!  Thank you @mgrauer !  You could consider it a dandi webui platform version, as e.g. a version of any  linux distribution release which contains a variety of subcomponents which could have their own versions.

**Comment by satra** [comment]
> I don't think the notion of a semantic version is well defined for a repo that contains provisioning code, a docker-compose, a web gui, and a plugin providing rest endpoints.

i will simply consider it a version of the state of the union but the state always changes !

**Comment by mgrauer** [comment]
Yes, I think ultimately the piece that will stay with us the longest from this repo with be the Web UI.

The State of the Union is strong, or actually, it is 0.1.0.
