### ISSUE TITLE
reduce dandicli apikey scopes

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#156]
Reduce the dandicli apikey scopes to the minimum scope needed.

Basically revert https://github.com/dandi/dandiarchive/pull/153.

In order to do that, we need to change the [create dandiset endpoint](https://github.com/dandi/dandiarchive/blob/master/girder-dandi-archive/girder_dandi_archive/rest.py#L30) to have token write scope rather than user scope, such as this [example](https://github.com/girder/girder/blob/master/girder/api/v1/folder.py#L131).

**Comment by AlmightyYakob** [comment]
Would this affect the creation of dandisets on the frontend? I'm not sure if the token scope includes tokens given upon login, or if it refers to API keys

**Comment by satra** [comment]
both the frontend and the cli should be able to register.

> I'm not sure if the token scope includes tokens given upon login, or if it refers to API keys

i could not figure that out easily from the girder documentation
