### ISSUE TITLE
metadata edit icon should only be visible if the user has access

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#158]
i logged in as a different user, and the edit icon is still visible.

![image](https://user-images.githubusercontent.com/184063/76803502-5e2af500-67b0-11ea-8a63-a00a345da514.png)

this should only appear when:
1. a user is logged in
2. the user has access to edit the metadata

**Comment by satra** [comment]
![image](https://user-images.githubusercontent.com/184063/76803710-d8f41000-67b0-11ea-93e6-e93a0ab254e5.png)

also delete should only appear for a person who has authority to delete.

**Comment by AlmightyYakob** [comment]
> also delete should only appear for a person who has authority to delete.

@satra currently we've removed the delete button from the file browser, do you wanted it added back or is that comment just outdated?

**Comment by satra** [comment]
@AlmightyYakob -  it was removed because it was not doing the thing it was supposed to do, rather than the lack of the need to delete. we should allow deleting files/folders from the gui by the person(s) who has(ve) ownership of the dandiset. 

as a ui side note, i also think the delete and download buttons should appear at the top of the info panel.
