### ISSUE TITLE
add dandiset identifier and/or folder name into the title of the page

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#160]
I have now a number of tabs which are all "dandi".  Hard to figure out which one to choose.  Should be something like "dandi | 000001" or "dandi | drafts" or "dandi | blah" when I am in some random "blah" folder of a user set of folders

**Comment by mgrauer** [comment]
Examples of what they do on [openneuro](https://openneuro.org/datasets/ds002606/versions/1.0.1) and [zenodo](https://zenodo.org/record/3716018#.XnjQytNKjUo).

If this is easy we can do it now, but definitely want it in the site redesign.

**Comment by dchiquit** [comment]
https://github.com/vuejs/vue-router/issues/914 seems relevant
