### ISSUE TITLE
Show information from both sections in the DLP landing page

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#163]
The DLP landing page should show keys from both sections 1 (human entered) and sections 3 (from dandi organize) of the schema.

This should also show sections that are empty but required with an alert icon, so that dataset creators can see this.

**Comment by satra** [comment]
related issue #103

**Comment by AlmightyYakob** [comment]
@satra by the 3rd section, do you mean these lines?

https://github.com/BICCN/BICCN-Infrastructure-Draft/blob/ce0df09b310bbcdd0a7a63cc51a0955e3cae97b8/BICCN-policies/dataset-metadata.yaml#L66-L82

Do you have an example of a dandiset with this data?

**Comment by satra** [comment]
> Do you have an example of a dandiset with this data?

https://dandiarchive.org/dandiset/000004/draft

most of the new datasets in draft that have data should have this information.

**Comment by satra** [comment]
> @satra by the 3rd section, do you mean these lines?
> https://github.com/BICCN/BICCN-Infrastructure-Draft/blob/ce0df09b310bbcdd0a7a63cc51a0955e3cae97b8/BICCN-policies/dataset-metadata.yaml#L66-L82

yes.

**Comment by AlmightyYakob** [comment]
> This should also show sections that are empty but required with an alert icon, so that dataset creators can see this.

In the Landing Page itself, or just the editor?

**Comment by satra** [comment]
In the editor. the landing page can focus on available sections with data for now. it would be nice if the text on the landing page fields could be selected, and if it responsively covered two columns.
