### ISSUE TITLE
how is the sign in process being handled

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#164]
1. do you know if people get an email when they sign in using github that the account will need to be approved? 
2. do they get an email when their account is approved?

3. what happens between 1 and 2? is there some UI that notifies them that the account is waiting to be approved?

4. should we automate approvals?

**Comment by mgrauer** [comment]
>1. do you know if people get an email when they sign in using github that the account will need to be approved?

No they don't. They do get an email from GitHub saying (this is abbreviated):

`A third-party OAuth application (dandiarchive) with user:email scope was recently authorized to access your account.`

> 2. do they get an email when their account is approved?

Yes like:

`DANDI
Your account has been approved. You may now login.
https://girder.dandiarchive.org`

> 3. what happens between 1 and 2? is there some UI that notifies them that the account is waiting to be approved?

Yes, if they try to log in they get a message saying "Account approval required."

> 4. should we automate approvals?

Do you mean allow open registration? I think we are still in the phase that we should be approving registrations, at least until we have some processes a bit more smoothed out (e.g. user folder quota set up, and full cycle of dandiset creation, at least of drafts).

**Comment by mgrauer** [comment]
When do we close discussion issues? When the questions are answered or when it is clear what we will do next? When the asker is happy?

**Comment by satra** [comment]
> When do we close discussion issues?

play it by ear.

i'm fine with waiting for automated approvals, but we just need to make things to people who will use this.

**Comment by mgrauer** [comment]
@satra 

>but we just need to make things to people who will use this.

?

**Comment by satra** [comment]
i can't type properly today.

we just need to make things **clear** to people who will use this.
