### ISSUE TITLE
Include dandiset metadata into dandisets listing page

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#167]
ATM it is annoyingly hard to figure out which dandiset I need to go to solely by seeing its identifier on https://gui.dandiarchive.org/#/collection/5e59bb0af19e820ab6ea6c62 .  Metadata such as name, altid(s), contributors could be shown alongside in the row (as long as width permits or wrapped into a new row).  This is what is commonly done on github (and its clones/analogs) itself, openneuro displays  names, has sorting etc.

**Comment by mgrauer** [comment]
I agree. This is one of the downsides of moving to folder names being identifiers.

**Comment by mgrauer** [comment]
Here's the current mockup of the dandiset dashboard. Let's decide which specific pieces of metadata need to go in the display. 
<img width="788" alt="Screen Shot 2020-03-23 at 10 55 56 AM" src="https://user-images.githubusercontent.com/595023/77329906-03842280-6cf5-11ea-9aec-245577edb09d.png">

**Comment by satra** [comment]
- Version + release date/last updated
- Contact person name/institution (not last updated by)
- Keywords (upto 3)
- List of species
- Number of subjects / Number of files
- Size
