### ISSUE TITLE
cross-linking data

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#168]
I'd like a place in the meta-data file to identify other places where this data is shared, e.g. figshare, CRCNS, institutional servers, etc.

What do you all think about putting something like this is https://github.com/dandi/dandiarchive/blob/master/web/src/assets/schema/base.json that holds a list of urls to other data sources?

**Comment by satra** [comment]
yes: see this file:

https://github.com/BICCN/BICCN-Infrastructure-Draft/blob/ce0df09b310bbcdd0a7a63cc51a0955e3cae97b8/BICCN-policies/dataset-metadata.yaml

there are two relevant places:

```
associatedData (for example, other related data, or raw data, etc.,.)
distribution (other places through which the same data are distributed)
```

for now if you want you can add them to the dandiset.yaml manually locally. this should be editable in the not too distant future online.

**Comment by waxlamp** [comment]
What's the status of this issue? Is it possible to do what @bendichter requested using the latest metadata schema?

**Comment by satra** [comment]
we already have support for this in the Resources section of dandiset metadata, but also asset metadata.
