### ISSUE TITLE
can't save metadata after editing

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#176]
![image](https://user-images.githubusercontent.com/184063/77215907-34920680-6aed-11ea-8c11-6dc4573f4a15.png)

after #175 was merged, i see this error when:

- i'm editing 000005 metadata. 
- remove publications section
- add publication
- click save

note because of the way @yarikoptic was adding publications, on upload the original publication is just a list. so i first delete it and then add a new one.

@yarikoptic - we should also fix this in the dandi-cli. the new json sections in this archive have now been updated and are closer to our final state. 

@mgrauer - we should also discuss a migration path as the schema evolves.

**Comment by satra** [comment]
i think this is the unpacked error message:
```
{
    "message": "No matching route for \"GET 5e70033c0fe0ec33e6b3d732/metadata\"",
    "type": "rest"
}
```

**Comment by satra** [comment]
for this url: `https://girder.dandiarchive.org/api/v1/folder/5e70033c0fe0ec33e6b3d732/metadata`

**Comment by satra** [comment]
but i could do it for dataset 1. going to try 5 again!

**Comment by satra** [comment]
nevermind - i wasn't the owner of this (my alter ego was). closing this, but i think it would be really useful to not allow metadata editing if the logged in user is not the owner.

**Comment by mgrauer** [comment]
Agreed that this would be useful, it has been tracked at https://github.com/dandi/dandiarchive/issues/100.
