### ISSUE TITLE
Add an endpoint for high level archive statistics

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#179]
- number of dandisets
- number of species
- number of users

**Comment by mgrauer** [comment]
@satra @yarikoptic @bendichter 

Are these good top level stats for the overall archive, for the landing page, or are there better ones?

**Comment by satra** [comment]
in addition to the above:

- number of subjects
- number of cells
- total size of data

**Comment by dchiquit** [comment]
@satra This endpoint is intended to provide data for this info widget in the UI:
![Screenshot from 2020-03-24 14-35-44](https://user-images.githubusercontent.com/577946/77463972-db6fee80-6ddc-11ea-986a-24508a752be0.png)
Can you elaborate a bit on what you're hoping for?
* Does "subjects" mean "members of dandisets"? Does it mean description?
* What is a cell? I haven't heard that term used in the context of dandi before.
* If data size is exposed in girder I will add it.

**Comment by satra** [comment]
@dchiquit - each dandiset should have metadata related to number_of_subjects and number_of_cells.

**Comment by mgrauer** [comment]
It would be totally reasonable to start this with what is simple and then extend it later.

The following I expect are available easily for the current dandi archive:

 - number of users (there's already an endpoint for this)
 - total size (the current drafts collection has a display of its size, you could just use that, from wherever this value comes from)
 - number of dandisets (the number of folders in the drafts collection)
