### ISSUE TITLE
Create home page

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#184]
Depends on #179, #182.

[Figma link](https://www.figma.com/proto/kEHOgqU0rcOIyCYIDlpSMV/DANDI-UI?node-id=1%3A2&scaling=min-zoom)

For now we are omitting recent activity and below.

<img width="1297" alt="Screen Shot 2020-03-23 at 4 48 09 PM" src="https://user-images.githubusercontent.com/595023/77361709-2975eb00-6d26-11ea-9fe5-9b7e6cf6e1c5.png">

**Comment by satra** [comment]
@mgrauer - can the link be made publicly (viewable) or can we be given access to it?

**Comment by mgrauer** [comment]
We are looking into it. I'm not sure yet, so I wanted to drop in screenshots also for now.
