### ISSUE TITLE
List and get dandiset endpoints should use access control

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#194]
Right now, any user can list every / get any dandiset. This should be revisited to consider access controls.

**Comment by mgrauer** [comment]
To add a bit of context here, currently we only have draft dandisets, and those are intended to be publicly readable (are folders in a public collection). We plan to soon have published dandisets, which are also intended to be publicly readable. There was a longer term use case of embargoed dandisets, which would be private to a user/group and then made public after some time.

This doesn't mean that the endpoints shouldn't check/enforce access control, and that the permissions shouldn't be set correctly though, but it does reduce the urgency.

**Comment by mgrauer** [comment]
This will be obviated by the unified API
