### ISSUE TITLE
Create Sentry.io account

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#2]
@satra Can you create a Sentry.io paid account, and then we can attach that to the Girder instance once the instance is running?

**Comment by mgrauer** [comment]
This is done, with the dandibot user. 

I'll extend this issue to getting access for other people to the sentry account.

**Comment by mgrauer** [comment]
That is, we'll use dandibot as the admin user, and add other people through their own logins so they can see the error messages.

**Comment by yarikoptic** [comment]
I believe this one is resolved. I even received some (first in my life) sentry notification today! ;)
