### ISSUE TITLE
User quotas of zero shows as Unlimited in user view

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#208]
As a follow up to #171, when you look at a User's usage quota (User view, then Actions, then Quota and Assetstore policies) in the Girder client, it currently displays as `Unlimited` when they have a quota of 0.

I had viewed the value coming back the server in my Chrome JS console network tab, and it is correctly set to 0 in the current dandiarchive. I think this is a bug in the display that remains to be fixed as part of the upstream PRs to allow for a quota of 0. 

Probably it needs to be fixed in [quotaPoliciesWidget.pug](https://github.com/girder/girder/blob/master/plugins/user_quota/girder_user_quota/web_client/templates/quotaPoliciesWidget.pug) and whatever JS file sets values for that template, for the User View.

**Comment by dchiquit** [comment]
This is a girder bug, can it be moved to the girder project?

**Comment by mgrauer** [comment]
Good call. Can you create an issue there and cross link this one?

**Comment by brianhelba** [comment]
Closing in favor of upstream fix.
