### ISSUE TITLE
Add published folder and publishing mechanism

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandiarchive#212]
Currently we only have a drafts folder, so all dandisets are drafts by default. Add a `published` folder and a way to move dandisets from `draft` to `published`.

**Comment by satra** [comment]
thanks @dchiquit - we are having a call this afternoon to discuss this.

**Comment by mgrauer** [comment]
This is captured in https://github.com/dandi/dandi-publish/issues/21.
