### ISSUE TITLE
data format on publish

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#255]
when we publish a dataset, should we store on s3 as nwb or zarr? let's discuss. 

cc: @bendichter @mgrauer @yarikoptic

**Comment by mgrauer** [comment]
My thinking is that the publication workflow is going to be worked out sooner, as the zarr question is an optimization that will need some experimentation first. I assume that we'll go with the hdf5-backed NWB for now as part of the initial implementation of the publication workflow, and then when we are ready to make a decision about zarr, we can do a data migration of existing published datasets and the publication workflow then.

**Comment by satra** [comment]
there are several options that may enhance access to the data.

1. datalad dataset on github
2. adding chunking metadata a la https://medium.com/pangeo/cloud-performant-reading-of-netcdf4-hdf5-data-using-the-zarr-library-1a95c5c92314 as pointed by @bendichter 
3. future work on TileDB (https://tiledb.com/)

for now i think the publish workflow could consider adding 2 as a shadow dataset of chunking indices. 1 will definitely happen as part of publish if not earlier.

**Comment by waxlamp** [comment]
Can this be closed for the time being? Or is it still an active topic of discussion?

**Comment by satra** [comment]
let's close this for now. we will revive a specific zarr discussion.
