### ISSUE TITLE
Improve navbar styling

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#268]
## Logged Out

[Figma link](https://www.figma.com/proto/kEHOgqU0rcOIyCYIDlpSMV/DANDI-UI?node-id=1%3A2&scaling=min-zoom)

<img width="606" alt="Screen Shot 2020-03-23 at 5 02 31 PM" src="https://user-images.githubusercontent.com/595023/77362896-28de5400-6d28-11ea-932b-5c05df7a931d.png">

## Logged In

<img width="611" alt="Screen Shot 2020-03-23 at 5 02 41 PM" src="https://user-images.githubusercontent.com/595023/77362903-2d0a7180-6d28-11ea-9e7f-882cd5b1dcd7.png">

[Figma link](https://www.figma.com/proto/kEHOgqU0rcOIyCYIDlpSMV/DANDI-UI?node-id=15%3A371&scaling=min-zoom)

**Comment by mgrauer** [comment]
Fixed
