### ISSUE TITLE
files selection is no longer reflected in the URL

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#274]
We used to get URLs like

https://gui.dandiarchive.org/#/folder/5e60c14f81bc3e47d94aa012/selected/item+5e60c19381bc3e47d94aa014

with multiple items listed in the url if multiple files were selected.  That allowed to copy/paste such urls into `dandi download` invocation to streamline getting specific files.  Currently, with https://gui.dandiarchive.org/#/file-browser/folder/5e7160163da50caa9adafe6c UI it seems no longer possible.  That in effect disables  ability to download any specific file (or selection of them) via client.  There is `Download (zip)` for a the selection but likely it would be gone (#267)

**Comment by satra** [comment]
+1 to having multi-select download via the cli.

**Comment by mgrauer** [comment]
This is now tracked in https://github.com/dandi/dandi-cli/issues/183.
