### ISSUE TITLE
Guide user to use dandi client for downloads

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#275]
Whenever any item(s) selected, we should get a URL (ATM blocked by #274) reflecting selection, and instead of "Download zip" (will probably be gone with #262) get an entry "Download with client" which if clicked would open a popup informing

If you do not have dandi client install, follow its [Installation instructions](https://github.com/dandi/dandi-cli/#installation) , and then copy paste following command to your terminal:
```
dandi download https://gui.dandiarchive.org/#/folder/5e60c14f81bc3e47d94aa012/selected/item+5e60c19381bc3e47d94aa014
```

to download selected item(s).

Marked it as severity normal, since it does notably impact usability of the archive, thus not merely a wishlist

**Comment by mgrauer** [comment]
Fixed
