### ISSUE TITLE
Add subtitle to home page

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#287]

**Comment by mgrauer** [comment]
@satra @yarikoptic @bendichter 

We are close to switching over to the refactor branch--the website refactor isn't totally done, but we will soon be at the point where the refactor branch is strictly better than the current UI in all respects, and that will be the time to switch over.

The specific question is what text do we want to put in the subtitle for the website redesign?

Replacing the "Lorem ipsum..." text from the center content panel, that is. You can see a preview of the refactor branch [here](https://refactor--gui-dandiarchive-org.netlify.app/#/).

**Comment by mgrauer** [comment]
I should add, that the current refactor preview front-end is pointing to the production backend, so don't do any actions there you wouldn't do on the production instance.

**Comment by satra** [comment]
woohoo - i'm so looking forward to this refresh :)

How about "A platform for publishing and sharing cellular neurophysiology data." to start with.

**Comment by mgrauer** [comment]
I realize we could bikeshed all day about this, and I'm not trying for that, so I approved the PR for now, but I do want us to think carefully on this. Are we a platform or are we a specific instance of that platform (I know we are both, and further, expect to be distributed) ? Should we say that The Dandi Archive, located at `dandiarchive.org` and subdomains, is a platform or is it a hosted archive/hosted service/archive?

Maybe "The archive for publishing and sharing cellular neurophysiology data" (also note "the" vs "a"; Nemo says "The Neuroscience Multi-omic Archive")


I realize @satra said "to start with", and what we have now is strictly better than Lorem Ipsum!

**Comment by satra** [comment]
@mgrauer - yes we could evolve this over time. how about:

`The BRAIN Initiative archive for publishing and sharing cellular neurophysiology data.`
