### ISSUE TITLE
Make dandiset stats tooltip less sassy™

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#288]
Change it to a description of what a dandiset is.

**Comment by mgrauer** [comment]
@satra @yarikoptic @bendichter 

What text do we want in the tooltip that describes what a Dandiset is? It should be fairly short, a sentence or phrase rather than a paragraph.

**Comment by mgrauer** [comment]
I'll offer text for the tooltip: "A DANDI dataset that includes a set of files and dataset level metadata"

**Comment by mgrauer** [comment]
"A DANDI dataset including files and dataset-level metadata"
