### ISSUE TITLE
Improve UX when async loading from a slow connection

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#298]
somehow my home connection is really slow ATM (kids watching a movie might be contributing).

Our https://gui.dandiarchive.org/#/ feels sluggish and some aspects start to emerge: when I go from the list of dandisets (https://gui.dandiarchive.org/#/) into any specific one, and then from there into a file-browser, e.g. https://gui.dandiarchive.org/#/file-browser/folder/5e72840a3da50caa9adb0489 for a while it shows "Not Data Available"  **without** any indication of any activity like it is happening (running blue line on top) when I am going e.g. from [drafts](https://gui.dandiarchive.org/#/file-browser/collection/5e59bb0af19e820ab6ea6c62) within file-browser to that folder.  Ideally appearance should be the same and/or "No Data Available" be replaced with "Loading" until it is known that indeed there is no data.

**Comment by brianhelba** [comment]
I've updated the title of this issue. We should use this tool: https://developers.google.com/web/tools/chrome-devtools/network#throttle to determine which page transitions and async data fetches would benefit from graphical transitions or spinners to ease user frustration.

**Comment by dchiquit** [comment]
This is a behavior inherited from GWC, which makes it hard to fix. There will be a new file browser for the new DLP implemented sometime in the near future, so it doesn't make sense to waste effort on this relatively minor UX concern.

Monitoring the app's behavior for slow connections sounds like a separate issue to me.
