### ISSUE TITLE
Make GitHub login / registration more prominent 

### ISSUE THREAD

**Issue by brianhelba** [dandi/dandiarchive#307]
GitHub should be the preferred way for new users to register. GUIs should push them in that direction.

**Comment by satra** [comment]
@mgrauer - increasing the severity of this. if anything this has regressed the way it looks now with all indications for a user to register without github.

![image](https://user-images.githubusercontent.com/184063/89106513-75355100-d3f8-11ea-9818-cacce2c1ea70.png)

ideally for the moment, we would only have the Github OAuth link for registration.
