### ISSUE TITLE
Evolve the Dandi CLI at the same time as the web UI refactor update

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#308]
Figure out what the interaction points are between the CLI and the UI, and make sure we update the CLI for those interaction points at the same time as we update the UI so that they stay in sync.

The list of interaction points should be captured [here](https://github.com/dandi/dandi-cli/blob/master/dandi/download.py#L13).

**Comment by brianhelba** [comment]
https://github.com/dandi/dandi-cli/blob/master/dandi/download.py#L58

**Comment by satra** [comment]
more specifically the types of URLs that were supported: 

https://github.com/dandi/dandi-cli/blob/master/dandi/download.py#L16

**Comment by mgrauer** [comment]
After #303 is done, @AlmightyYakob can point @yarikoptic to the new URLs.

**Comment by satra** [comment]
this should be resolved: https://github.com/dandi/dandi-cli/issues/92

**Comment by mgrauer** [comment]
@AlmightyYakob can you provide a mapping of the old to new URLs? please correct me if I'm missing something.

**Comment by AlmightyYakob** [comment]
I believe the URLs should stay the same, except for an an added `file-browser/` in the path. If it was:

 https://gui.dandiarchive.org/#/folder/5e5593cc1a343161ff7c5a92

Now it'd be 

 https://gui.dandiarchive.org/#/file-browser/folder/5e5593cc1a343161ff7c5a92

Which on girder would be:

https://girder.dandiarchive.org/#user/5da4b8fe51c340795cb18fd0/folder/5e5593cc1a343161ff7c5a92

Does this answer your question?

**Comment by mgrauer** [comment]
@yarikoptic will you be able to make these changes? Does what @AlmightyYakob said in the previous comment give you everything you need?

**Comment by AlmightyYakob** [comment]
> @yarikoptic will you be able to make these changes? Does what @AlmightyYakob said in the previous comment give you everything you need?

@yarikoptic Can we close this issue?

**Comment by yarikoptic** [comment]
yes, AFAIK https://github.com/dandi/dandi-cli/pull/94 should have addressed it
