### ISSUE TITLE
dandiset permissions endpoints

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#335]
Provide a backend for #334.

This is a simplified permission model: users are either owners or not of dandisets. The original creator is the owner, can add and remove owners.

Create endpoints that support this: 
- list owners, given a dandiset identifier
- remove owners, given a dandiset identifier and list of owners
- add owners, given a dandiset identifier and list of owners

This doesn't have to map to three endpoints exactly, as long as this functionality is supported and the UI in #334 can call the right endpoints.

**Comment by mgrauer** [comment]
Users should be found by their username or first name or last name, so there will need to be support for this type of search (perhaps using the existing search endpoint, restricting to user).

**Comment by AlmightyYakob** [comment]
Should this be implemented into the existing girder instance, or into the new Django instance? Or is there any preference?

**Comment by AlmightyYakob** [comment]
It probably makes the most sense for me to start with the girder plugin, and then we can mirror that functionality on the Django instance if we want/need to.

**Comment by mgrauer** [comment]
This needs to be on Girder. I should have clarified that these permissions are for draft datasets. 

Published datasets do not have any permissions, they are read-only and public, for all users.

**Comment by AlmightyYakob** [comment]
> Users should be found by their username or first name or last name, so there will need to be support for this type of search (perhaps using the existing search endpoint, restricting to user).

It also seems like this should be a separate issue? That is, searching for users based on this criteria. Still a requirement for #334, but including it here might make this change a bit confusing.

**Comment by AlmightyYakob** [comment]
> Users should be found by their username or first name or last name, so there will need to be support for this type of search (perhaps using the existing search endpoint, restricting to user).

Whether we need a new endpoint or not may depend on how this is expected to be used on the front-end. The `/user` endpoint in girder allows for text search, but it's limited to whole text matching, i.e. if you search for a user by the firstName "Robert", but only type "Rob", the result won't appear until fully typing "Robert".
