### ISSUE TITLE
add link to setup workflow

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#337]
could we for the moment add a link to this:

https://docs.google.com/document/d/1ehxd5a6Hurz7VqQDAszEpGASRTUP6muXYwJ5wgXhzU4/edit

somewhere on the nav bar?

**Comment by mgrauer** [comment]
Thanks for capturing this, I forgot to add an issue.

Do you want to add it on nav bar or as part of create dandiset page or both?

**Comment by satra** [comment]
@mgrauer - i think it should be accessible all the time as people may want to come to it. one thought process is to change about -> docs and we revamp our jekyll site to be more like docs/faqs, etc.,.

the other is simply to put another item in the menu.

i'm not tied too strongly to either, but the conceptual point is that it should be easily accessible to a user wanting to create an upload a dandiset and then through the process of doing so.

**Comment by mgrauer** [comment]
Point to the [handbook](https://www.dandiarchive.org/handbook/) instead of the google doc.
