### ISSUE TITLE
s3 publish proposal

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#355]
been pondering the publishing workflow a bit. and here is a proposal for organizing s3 bucket for publishing dandisets:

```
# consider these folders at some <s3-prefix>
/blobs/:sha256.[extension] (actual bytes, we can decide the exact naming scheme)
/assets/uuid.jsonld (contains asset metadata: filename, rel path, format, link to other archives, etc.,.)
/dandisets/:identifier/:version/dandiset.[yaml/jsonld] (contains dataset metadata)
/dandisets/:identifier/:version/manifest.jsonld (contains mapping of assets)
/dandisets/:identifier/:version/index.html (contains landing page marked up with google dataset jsonld)

# could also support:
/blobindex/:sha256.[chunk-extension] (potentially for easy access into hdf5 or other serially compressed formats)
```

where the `manifest` would contain pointers to `assets`, which in turn would contain pointers to `blobs` this should handle versioning with deduplication of content. 

notes:
- other s3 stores (e.g. minio, used for dev) do not provide versioning the same way amazon does. we would turn s3 versioning off since that will not be required. 
- we should be able to map this to our api quite nicely
- anybody browsing s3 would know exactly where to find things
- mapping this should be relatively easy for any client/search/other service
- dandi-cli should be able to download this into a hierarchy quite easily
- this should be quite easy for datalad to slurp
- we handle google dataset search, deduplication, and metadata
- this should handle new versions quite nicely, and could handle drafts as well without duplication

cc: @mgrauer @yarikoptic @brianhelba @dchiquit @AlmightyYakob

**Comment by yarikoptic** [comment]
I like it:
- having it aligned to the API sounds like a nice thing to have indeed! ;-)
- also `/dandisets/:identifier.[yaml/jsonld]` - information about versions etc (explicit better than implicit reliance on listing the folder?)

but
- will amazon public dataset program be "happy" with it? (that files are not immediately available in a logical hierarchy)
- I do see benefits from top level `/blobs`, `/assets` etc, in particular for datasets which would be derived from existing, but I worry that it might eventually become problematic in some cases: e.g. if we need to remove some dandiset, figuring out which assets/blobs to remove and what other dandisets are effected - it would require download (if not present) and analysis of all dandisets metadata, might be expensive etc.  but if cases are rare and spare - might actually be of an advantage.

**Comment by satra** [comment]
i think amazon would be ok with this since all the information is there and anyone without special dandi tools could understand it. for them i think it was more of the current state which is essentially just uuid's that through them off.

>if we need to remove some dandiset

we did decide that for published datasets this would not be normal operation but a special op. so i think we would be able to do this and notify people who are dependent on those blobs. in fact this allows us to update metadata on the uuid.json to invalidate those as well. i would also think all metadata would be part of our search so should be able to construct this quite rapidly.

**Comment by mgrauer** [comment]
@satra this was a really useful distillation of the requirements, thanks for putting it together. Our discussion the other day following up on this was also extremely helpful.

We should try to work towards this as a suggested structure for the keys in S3 as we implement the restful API, that is, this structure would be the behind the scenes implementation that is created by the publish service and indexed/served out by the releases API. It may not satisfy all cases or have some rough edges, so we should definitely defer to the implementors and allow them flexibility, and we know the goals we are working towards in an implementation because of this discussion.

We had agreed in our in-person discussion that this path structure in S3 would not be an unbreakable API, we will have the ability to change and evolve this to suit our needs.

Clients, especially dandi-cli and the dandi-gui, should consume the dandi restful API for releases, which will allow for hiding implementation changes in how we structure keys in S3 without breaking those APIs, though of course we expect those APIs will need to evolve also.

For the near term, this S3 structuring will just apply to the releases/post-publication API and datastore. We'd like to do something similar (create an S3 structure and restful API for drafts) but that will have to wait for a later phase.

**Comment by satra** [comment]
@mgrauer - just wanted to check if any part of the current work on the publish process is creating the above proposed organization. i plan to add a subcommand to dandi cli in the next few days to organize a data like the proposal here (intended for publish) and fill in the yaml files (with jsonld syntax with the new schema being developed in dandi-core). wanted to check that i'm not redoing work.

**Comment by mgrauer** [comment]
I don't think any of the proposed organization has been created yet. I'd encourage you to wait to implement the proposed organization until we have a chance to discuss as a larger group, as I think we've learned some worthwhile lessons by the current publish work, and also (though I don't understand what you are proposing with the CLI) I wouldn't want any of the existing structures/files to change as to what goes into a dandiset draft, as that is the input to the current publish workflow and changes to that input would break the current publish workflow.

I think the yaml/jsonld for the dandiset.yaml would be the safest and most useful thing to do, as that shouldn't change I don't think with any changes to the structure of the published dandiset. I think the next safest thing would be the manifest, though i would expect  some change there.

**Comment by satra** [comment]
@mgrauer - does that mean you already have the blob and assets organization listed above? assets will also have a schema associated with them (as in the PR in dandi-core). and as we had discussed we may do this by hand behind the scenes and then update the publish workflow to reflect our hand curated process.

i should be sending a WIP PR to dandi-cli to reflect what i mean by publish hopefully tonight, may be tomorrow.

**Comment by mgrauer** [comment]
> does that mean you already have the blob and assets organization listed above?

no

I'm not following enough of what you are saying here, perhaps it will be more clear when I see the PR you are working on, but regardless I'd like to have a video call to sort this through as there are many different moving parts here being worked on by different people.

**Comment by waxlamp** [comment]
I think this is taken care of now; please re-open if there are lingering issues to discuss here.
