### ISSUE TITLE
"extract" web/src/components/Meta{Editor,Node}.vue into a reusable component

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#357]
Metadata viewer/editor is a useful module to be reused in other contexts.  E.g. it could be (re)used by `dandi-cli` by initiative a webserver exposing it with a given schema to adjust selected set of metadata fields .nwb files, and/or later on to tune up various .json files in BIDS datasets.  Also outside collaborators might be interested in reusing it in their projects.

I guess http://github.com/dandi/nwb-metadata-gui was the land for the prototype in pure JS which was later reworked into a vue app.

ATM, from a brief look at it (and I have no clue in vue unfortunately) it seems still to be generic enough to be made into a standalone reusable component, only the binding to girder should somehow be exposed as a parameter to the dandiarchive specific deployment.  In case of local invocations could probably just saving into a file.

@AlmightyYakob how difficult you think it would be to "extract" it into independent component and imported back into the dandiarchive as such?

**Comment by satra** [comment]
i'm cc:ing @jbpoline as well. multiple people (including BICCN) are interested in this as a potential separate tool. 

however, any refactor should wait till we have the new schema in place.

**Comment by yarikoptic** [comment]
refactor - yes, but meanwhile someone interested (or in need) could take care about "cloning" from within dandiarchive codebase following @AlmightyYakob blessing that it is feasible and any  instructions/recommendations ;-)

**Comment by jbpoline** [comment]
@satra @yarikoptic  yes, would be very interesting to get something stand alone, and I suppose we could not only use schema but also take the opportunity to suggest terms (values) in the future.

**Comment by mgrauer** [comment]
I'm concerned about the difficulty of making a general component that is also highly customized enough for our specific Dandi use case. Those might end up being separate things. Let's not prematurely split this out into a component until we know what we need for Dandi, as that path won't serve Dandi well.

There are other possibilities that could open up, for instance, perhaps once we finish with what Dandi needs, it might be straightforward to pull some more general piece out or to write one from scratch that covers the general case and doesn't cause additional friction for Dandi development.

**Comment by AlmightyYakob** [comment]
Agree with @mgraur, for Dandi itself I wouldn't be comfortable with the large complexity of trying to import a generalized tool, as our needs for dandi are too specific to be generalized in a tool like this (or rather, if it is possible, it's much more work than I think we want to expend). 

The best way I see forward in this regard is having the base tool on its own (without custom dandi behavior), which could then be forked/modified for whatever it needed to be, and would be completely separate from the dandi tool. Although if we were to do that, we should hold off until we've addressed all of dandi's needs and have a solid foundation to work from.

**Comment by AlmightyYakob** [comment]
The tool is also in need of a refactor, which I've had yet to get to, and I wouldn't feel comfortable taking steps towards this goal until that's completed.

**Comment by yarikoptic** [comment]
Just FTR: current meditor lives in/around https://github.com/dandi/dandiarchive/blob/e14af6c1959e0a460cdb92df9bdf4c7e7e27fb2f/web/src/views/DandisetLandingView/Meditor.vue

**Comment by waxlamp** [comment]
We have not explicitly solved this issue, but I am not sure we currently want to either. I will close this issue so please reopen if there is a viable path forward at the current time (otherwise, we can always file a new issue to drive this work when we have clearer demand/requirements).
