### ISSUE TITLE
dandiset.json: unify contributors roles ?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#360]
Looking at https://github.com/dandi/dandiarchive/blob/master/web/src/assets/schema/dandiset.json#L60
I see 3 types of records
- ContactPerson
- Data Collector
- Funding acquisition

Ideally they all should be unified to follow one of those schemas uniformly, unless they all match terms defined elsewhere as inconsistently (so we would need to fix them there first/as well).

**Comment by satra** [comment]
@yarikoptic - please see the revisions in the dandiset descriptor slides

**Comment by mgrauer** [comment]
This has been subsumed by the schema work.
