### ISSUE TITLE
Filter empty items from publication

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#363]
Following the discussion in #358, as part of the publish process, do not include any items that have 0 Files or have a File with 0 Bytes.

**Comment by yarikoptic** [comment]
Now that dandi client also uploads checksums, it would be best to prevent publishing of files without them. I prioritized https://github.com/dandi/dandi-cli/issues/105 to make it possible for users to avoid full reupload

**Comment by waxlamp** [comment]
Mooted by migration.
