### ISSUE TITLE
Refactored DLP doesn't have a link to content browsing

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#366]
The routes to browse a draft dandiset continue to work, but there is no longer an icon to get to the content browsing from the DLP. 

You can manipulate the url of a dandiset to get there, as a workaround for now, e.g.

https://gui.dandiarchive.org/#/dandiset/5e6eb2b776569eb93f451f8d
=>
https://gui.dandiarchive.org/#/file-browser/folder/5e6eb2b776569eb93f451f8d

/cc @yarikoptic

**Comment by satra** [comment]
till we get the new navigator, it would be good to have an icon for the current one.

**Comment by mgrauer** [comment]
yes, sorry, that's what I meant with creating this issue, but didn't actually say it :)
