### ISSUE TITLE
sign up allows regular email

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#367]
@mgrauer - we should not allow people to sign up through a login/password process at present. only github oauth. can we ensure this?

i just received two emails one which has an associated github account and one which doesn't. i approved the github one and deleted the other one.

**Comment by mgrauer** [comment]
So you want to disable password based registration altogether?

We had previously said to favor GH over email/password, see https://github.com/dandi/dandiarchive/issues/307.

**Comment by satra** [comment]
i would like users not to be able to register via username and password, since we are not using girder as oauth for jupyterhub. only github is supported for logging into the hub.

the other i felt was more in terms of ui presentation for login (github should be more prominent than user/password) for registration, if we can restrict to github for now, that would be fine.

**Comment by AlmightyYakob** [comment]
@satra to clarify, we're to still allow login from existing girder users? Just not registration?

**Comment by satra** [comment]
> we're to still allow login from existing girder users? Just not registration?

yes to both.

**Comment by mgrauer** [comment]
@AlmightyYakob there are some upstream GWC issues related to this that could help.

https://github.com/girder/girder_web_components/issues/262

**Comment by mgrauer** [comment]
Combined with/Subsumed by #307.

**Comment by mgrauer** [comment]
Fixed
