### ISSUE TITLE
search should allow for partial match and without field specification

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#37]
[searching for svobod](https://girder.dandiarchive.org/#search/results?query=svobod&mode=text) returns nothing, while [svoboda](https://girder.dandiarchive.org/#search/results?query=svoboda&mode=text) matches the folder.

Trying to [search for a word which I know mentioned in one of the metadata fields](https://girder.dandiarchive.org/#search/results?query=discrimination&mode=text) brings no hits.

Ideally search should allow for the simplest use of partial matching, and without any explicit field name specification

**Comment by yarikoptic** [comment]
d'oh -- that is just girder search and I should use our gui. not girder., sorry for the noise

**Comment by mgrauer** [comment]
You were correct in that the current DANDI search allows for exact match only of both key and value, and does not allow any prefixes or partial matches of keys or values.

**Comment by mgrauer** [comment]
e.g.

`lab:svoboda` will return results, but `la:svoboda` or `lab:svobod` will not return results, with the current data.

**Comment by yarikoptic** [comment]
ok then reopening after adjusting the title - we should allow also for simple searches with partial matches in the field values

**Comment by mgrauer** [comment]
This isn't so much a webui issue as it is an API issue, that the webui happens to expose.

Supporting partial search is a reasonable request, but the user should have to explicitly say they want a partial search. 

We should also require that the user specify a key, I don't think we should support searches across all fields. I think the below comment agrees with that.

>searching for svobod returns nothing, while svoboda matches the folder.

**Comment by satra** [comment]
if the ui supported completion, then i wouldn't worry about partial search. but if it didn't, they it should support partial search. the key is that individuals should not have to know specifics to search for to search. i do like how this app provides different ways to view their info: https://app.dimensions.ai/discover/publication

**Comment by satra** [comment]
@mgrauer - what can we search for now, with the DLP metadata? is there a quick way to fix search?

**Comment by mgrauer** [comment]
We can search for the following nwb metadata, with the nwb field listed first and the search grammar listed second:

 - `keyword` like `keyword:whiskers` or `keyword:whiskers keyword:cortex`
 - `number_of_units`, like `more_units_than:3 fewer_units_than:20`
 - `number_of_electrodes`, like `more_electrodes_than:3 fewer_electrodes_than:20`
 - `related_publications`, like `doi:<doi>`
 - `experimenter`, like `experimenter:joe+snook`
 - `institution`, like `institution:janelia+research+campus`
 - `subject_id`
 - `session_id`
 - `lab`
 - `identifier`
