### ISSUE TITLE
a number of "npm WARN deprecated" dependencies - anything to mitigate?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#371]
Since I have no clue in node and npm - don't know if any of those is direct dependency (and thus should be replaced/upgraded) or something which would get upgraded whenever direct dependencies would.   Given the troubles I keep getting into while trying to establish development instance (#369, #113), might be worth making sure that the stack is without hidden stones like these:?
```
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
```

**Comment by brianhelba** [comment]
Many of these are nested deep within our tooling dependency chain. For our primary web app, we use the latest VueCLI to manage the build and regularly update its dependencies. Even then, some number of warnings may always be present, which is the nature of the npm ecosystem. If we have any dependency security issues, they will be flagged by GitHub's repo scanning our lock file.

If significant alerts are coming from the `girder build` step, those can be reported / addressed upstream in https://github.com/girder/girder , but we don't use that legacy web client in dandi for anything but internal server adminstration.
