### ISSUE TITLE
Add per-dandiset stats endpoint and frontend use

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#372]
Following up from this comment: https://github.com/dandi/dandiarchive/issues/38#issuecomment-637828542

This endpoint would return the following about a specific dandiset:

- number of folders
- number of items
- number of bytes
- ~~number of items with 0 files~~

**Comment by mgrauer** [comment]
OK by me. In the end it might end up being ok to go into the same endpoint, but i'm fine with splitting out into separate PR/issue.
