### ISSUE TITLE
Add frontend tests for dandiset stats

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandiarchive#375]
Dandiset stats are now displayed in the search/list pages and on the dandiset landing page. We should add tests for making sure they are rendered correctly on both pages.

**Comment by satra** [comment]
@dchiquit - is there a place to see this? i didn't see it in the current PR deploy preview. should i be refreshing something?

**Comment by dchiquit** [comment]
@satre It's currently still in review, I just preemptively made the issues so we could tackle them later.

**Comment by dchiquit** [comment]
Ah, I see what you mean. The draft preview only provides a preview of the frontend code, so the backend API is still running `master`. Part of the current PR involves adding a new endpoint, which is not available in the draft preview. If you open your web inspector while visiting the page, you will see a 400 error when it tries to hit the stats.

**Comment by waxlamp** [comment]
Closing this in favor of a more judicious, from-the-ground-up testing strategy, since the code landscape has changed significantly since this was originally filed.
