### ISSUE TITLE
deleting folders on girder does not update dandi dashboard stats

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#379]
i don't know how the dashboard stats are being calculated, but deleting folders on the girder does not update stats. i went ahead and emptied out two datasets as requested by wayne, but that did not change any of the stats. since that's the only way i knew to delete all folders. let me know if there is a way to select all folders and delete from the gui.

if the stats are being cached somewhere, we should have a way of re-triggering the computation of stats.

**Comment by yarikoptic** [comment]
I guess triggering regeneration would also be useful when we upload anything ?

**Comment by mgrauer** [comment]
The [stats](https://github.com/dandi/dandiarchive/blob/master/girder-dandi-archive/girder_dandi_archive/rest.py#L263-L328) are calculated on the fly. What have you seen that seems like it is not updating?

**Comment by satra** [comment]
i should have taken some pictures of the dashboard. my recollection at this point was that the dashboard did not update the number of cells and number of subjects when i deleted the datasets. let's close this issue for now, but keep an eye if we have to do this again.

**Comment by satra** [comment]
i think i know exactly why, deleting the files did not change the metadata information about number of subjects and number of cells.

**Comment by mgrauer** [comment]
that makes sense, you kept the dandiset around with top level metadata, but deleted subfolders. that should have still changed the data size, but might have been noise/rounded off.
