### ISSUE TITLE
folder sizes are shown only if files are directly under that directory not in subdir

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#38]
e.g.
![image](https://user-images.githubusercontent.com/39889/67146048-eda99780-f254-11e9-9772-1adffb9ecf0d.png)

**Comment by mgrauer** [comment]
Maybe it would be better not to show sizes at all. I don't see showing sizes a requirement of DANDI, especially as it will expose implementation details--let's say we use the system to explode and HDF5 file into json + datasets compared to storing NWB files themselves. Why should a user of DANDI need to know those details at all?

**Comment by yarikoptic** [comment]
I would vote to show sizes -- gives immediate idea on the size of the (sub)datasets etc.  That is why we have them even on http://datasets.datalad.org.  Also would give DANDI bragging rights -- "look we host X ZB of data from Y lab for  Z study" or alike.  Or "for the paper A there is B TB of data".

**Comment by matthewma7** [comment]
Looks like this is a limitation with the current Girder. Potentially, could develop a girder plugin to support this. @mgrauer

**Comment by yarikoptic** [comment]
How difficult would be to implement this feature?

**Comment by mgrauer** [comment]
Let's change this to make an endpoint that shows, for a dandiset:

- number of folders
- number of items
- number of bytes
- number of items with 0 files

**Comment by yarikoptic** [comment]
Note: Soon there might come a dandiset with two or more levels of subdirectories. 

In general, FYI: BIDS datasets can have up to 4 levels in standard enforced part of the hierarchy: subject/session/modality/obscuredirbasedformat/.

**Comment by djarecka** [comment]
@yarikoptic - i believe this is not an issue anymore. could you please confirm and close it

**Comment by djarecka** [comment]
closing, please open if needed

**Comment by yarikoptic** [comment]
yeap -- confirming that this issue was addressed awhile back!
