### ISSUE TITLE
Add/Check front end option to empty out all folders in a dandiset

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#380]
we should enable someway of emptying out all folders in a dandiset.

**Comment by waxlamp** [comment]
Are you describing a special "delete all assets" button? Would this be covered by a more traditional "select all" checkbox that would be followed by a standard "delete" action?

**Comment by satra** [comment]
it doesn't even have to be a checkbox. i think a delete icon for folders would be sufficient.

**Comment by djarecka** [comment]
@satra - is this still a valid issue? I thought we don't want to have a delete icon on the LP

**Comment by satra** [comment]
This was more about delete control at the level of the file browser.

**Comment by waxlamp** [comment]
@satra, what's the use case for this feature? Is it to remove uploaded assets from a draft dandiset that were, e.g., included by accident?

**Comment by satra** [comment]
@waxlamp - indeed this was to be able to do things which were not possible with the cli. however, the cli does have some delete/sync options now. i would suggest closing this in favor of a richer file view/manage component that would also allow more complex search/upload/select/delete/download etc.,.

**Comment by waxlamp** [comment]
> @waxlamp - indeed this was to be able to do things which were not possible with the cli. however, the cli does have some delete/sync options now. i would suggest closing this in favor of a richer file view/manage component that would also allow more complex search/upload/select/delete/download etc.,.

Opened #1014 and #1015.
