### ISSUE TITLE
wrap around text elements longer than width

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#381]
![image](https://user-images.githubusercontent.com/184063/83838023-18ead500-a6c6-11ea-8d41-389830d1de3a.png)

[link](https://gui.dandiarchive.org/#/file-browser/folder/5ed9c618e82be273d48e412f)

**Comment by yarikoptic** [comment]
I bet there is some css/js trick to shorten it with ... and expand with wrap upon click ;-) and again shorten when clicked again... All those more/less I see in many UI s

**Comment by waxlamp** [comment]
@jtomeck, what is the general way to implement this type of display in CSS? Specifically:
- how do we cut off overflowing text with an ellipsis?
- how do we force a single, long word like these to "wrap"?

**Comment by jtomeck** [comment]
```
overflow: hidden;
text-overflow: ellipsis;
word-break: break-word; /* or 'break-all' would work too */
```

This CSS should do it

**Comment by waxlamp** [comment]
Thank you, @jtomeck!

@AlmightyYakob, could you do a (very) fast investigation to see if that combination of CSS settings will do the trick for us? If you don't have the bandwidth now for a quick investigation, please let me know here and we'll defer until there's more availability.

**Comment by AlmightyYakob** [comment]
I believe the attached screenshot is taken from the old file browser. Since that is gone from the UI, I think we can close this issue. If we add this functionality into the new UI, we can report any bugs as new issues.

**Comment by waxlamp** [comment]
Oh, good catch. Let's close for now, and try to remember to build in a fix for this sort of behavior when it comes back around again.
