### ISSUE TITLE
view data icon is not intuitive to users

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#383]
![image](https://user-images.githubusercontent.com/844306/83887957-28463e80-a717-11ea-8701-212986ad1ccf.png)

Users are struggling to figure out how to access their data, and do not know to press this icon. Many of them are sending me personal emails, very confused about where all of their data is. Can we have a label for this icon, e.g. VIEW DATA in blue matching the icon, similar to the EDIT METADATA label that is right next to it?

@AlmightyYakob, are you able to help with this?

**Comment by mgrauer** [comment]
I will do this.

**Comment by bendichter** [comment]
Thanks for tackling this so quickly, @mgrauer. The fix looks great!
