### ISSUE TITLE
Bulk download in UI

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#385]
Right now it is possible to download individual files in the UI. Could we add the following bulk download methods?
* Groups of files that are simultaneously selected
* Directories
* Groups of directories that are simultaneously selected

**Comment by satra** [comment]
@bendichter - bulk download will only be supported via cli, not the Web UI. We may have a local UI that does this/manages this. 

you should be able to do individual directories via cli. we have currently lost the option of simultaneously selected files and groups of directories. but all of this should be cli enabled in the next few months (especially as we publish the dataset and link it with DataLad).

**Comment by dkobak** [comment]
Hi @satra. It was me who asked Ben about this. It's just the Web GUI very easily allows to select entire folders using checkboxes, and there is even "select all" checkbox that allows to select all folders in the entire archive. So I absolutely expected to see a "download" link that would allow me to download the selection as a zip archive. But there is no such link. I found that non-intuitive.

Also - what is cli?

**Comment by satra** [comment]
@dkobak - we will provide some form of a ui. the thing that makes the Web ui download difficult is that we have to pull the data together into a zip file (and this can get very large in general).

the CLI (command line interface) is the same tool that is used to upload data to dandi. the CLI can be installed in a Python 3.6+ environment with `pip install dandi`

for example to download this folder (https://gui.dandiarchive.org/#/file-browser/folder/5e9f9588b5c9745bad9f58fe)

you can simply do:

```
dandi download https://gui.dandiarchive.org/#/file-browser/folder/5e9f9588b5c9745bad9f58fe
```

your point about giving easy ways to download sub components is well taken, and we will work on it. just that the general problem across datasets is a bit complicated and we need to provide easier to use tools that works across these different use cases.

**Comment by dkobak** [comment]
Thank you! This makes sense. I wasn't so much complaining about bulk download not available through GUI, but rather about the GUI being not entirely intuitive. It *does* offer an easy way to select groups of files or groups of folder. But it seems this does *not* serve any useful purpose (apart from displaying the total size of the selection). That's why I was confused.

**Comment by satra** [comment]
@dkobak - aha - we are working on the next version of the file navigator, so this feedback is much appreciated.

**Comment by mgrauer** [comment]
This relates to https://github.com/dandi/dandiarchive/issues/325, that is, though bulk download would be supported via the CLI, what help can the UI be to make it easy to download in bulk selected resources that are determined via the UI. e.g., select a handful of resources in the UI, and have the UI tell you the exact CLI command to run to get those.

There could be a path to bulk download through the GUI (perhaps not synchronously for the reasons that @satra mentions), but that would take some additional infrastructure engineering, and the CLI path can be realized much nearer term.

**Comment by yarikoptic** [comment]
Re bulk download in web UI from URLs without channeling through the server: some overview of currently used approaches and possible implementations see https://github.com/con/jsdownloader and feedback on https://github.com/con/jsdownloader/issues/1

**Comment by mgrauer** [comment]
Update: The GUI now describes how to download a Dandiset using the CLI.

We still have more work and clarification for downloading selected subsets of a Dandiset in bulk.

**Comment by waxlamp** [comment]
I think this can be closed.

@dkobak and @bendichter, if you have more thoughts on this topic, please do continue to post on this thread.

And FWIW, to manage the problem of downloading a huge file via the web, perhaps an approach like the big data brokers (i.e., Google, Facebook et al.) use when you ask to exfiltrate all of your data would be good: you ask for the specific thing, you receive an email sometime later with some sort of pre-signed URL which is valid for several days, then you do the download at your leisure (either through a web browser, or a tool like `curl`, etc.). I don't know if this fits in well with how we use S3, but just an idea.
