### ISSUE TITLE
New users can create new datasets before account is approved

### ISSUE THREAD

**Issue by nicolocin** [dandi/dandiarchive#389]
Was able to click on the 'New Dataset' button and go to the 'Register a new dataset' page on DANDI archive today right after I registered.   Got a github email about a new third-party OAuth application, but didn't receive other emails after that so I assume I'm not approved yet.

**Comment by waxlamp** [comment]
Hi @nicolocin - sorry for such a delayed response.

Once you authorize the OAuth application (via your GitHub credentials), you are immediately "approved" to use the archive. We are now arranging to have confirmation emails sent to newly registered users after this simple procedure succeeds.

Please let us know if you have further questions!
