### ISSUE TITLE
stats feature

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#396]
@AlmightyYakob - love the stats feature.

here just suggesting a potential change. in the public datasets dashboard page, could the files and size be added to the subtitle line. right after the identifier?  (i think that will also help with the wrapping on smaller devices)

![image](https://user-images.githubusercontent.com/184063/84522164-27c41f80-aca4-11ea-93f1-6fc4a1d3e850.png)

**Comment by AlmightyYakob** [comment]
Is this from rendering on a mobile device? Or if not what device? I'm hoping this only occurs on mobile

**Comment by satra** [comment]
yes, that was on a smaller viewport. this is what it looks like on my standard viewport:

![image](https://user-images.githubusercontent.com/184063/84523085-b8e7c600-aca5-11ea-872c-dfb2c70a8af6.png)

but the key is just to make any additional info look a bit more consistent

Contact Created Identifier Filecount Size 
(filecount and size could use icons)

**Comment by satra** [comment]
actually this is the order i would prefer: 

Identifier - Contact - Last updated - Filecount - Size
