### ISSUE TITLE
provide version information somewhere

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#40]
It would be nice, especially at current early stages of development, to display the deployed version (tag "releases" and use `git describe`) somewhere visible but not too prominent (bottom of the page?) on https://gui.dandiarchive.org

**Comment by mgrauer** [comment]
Do you mean the version of the gui client or of the dandi plugin?

**Comment by yarikoptic** [comment]
Both?

**Comment by mgrauer** [comment]
Probably doable at the next front end dev sprint.
