### ISSUE TITLE
Additional features for published dandiset content browsing

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#405]
This is a tracking issue, I'm not saying we should necessary do all of these.

- ~~breadcrumb clickability~~
- pagination
- display asset size
- add a download link for an asset
- what metadata to display and how for a published dandiset asset?
- clarify what the permalink is doing on the dandiset landing page
- display dandiset name and version in content browsing

**Comment by mgrauer** [comment]
Should be combined with #293.

**Comment by djarecka** [comment]
@mgrauer - I believe this can be closed, please re-open if needed

**Comment by mvandenburgh** [comment]
>   * what metadata to display and how for a published dandiset asset?
> 
>   * clarify what the permalink is doing on the dandiset landing page

I believe these two items are still not done, but yes most of these are complete. I'll defer to @waxlamp on whether to reopen this issue or make new ones.

**Comment by waxlamp** [comment]
> > * what metadata to display and how for a published dandiset asset?

This will be covered by the ongoing DLP redesign implementation, right?

> > * clarify what the permalink is doing on the dandiset landing page

I'm not entirely sure what this means, but if it's the general problem that the app URL does not match the permanent URL for a dandiset, then I believe we will fix that by removing the redirector from the workflow and reconfiguring dandiarchive.org to be the archive hosting URL, placing the dandi archive *website* at a different location. But I don't see this tracked in an issue, so might require a design doc. I'll file an issue for that.
