### ISSUE TITLE
"dev" or "next" branch for upcoming changes + an instance to test-drive it

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#407]
Since the archive now is in public use, I think it would be valuable to avoid merging possible breaking changes "rapidly".
`master` branch ATM is the "deployment" branch.  Any merged PR immediately takes an effect, possibly with only very limited testing in "as deployed" state.  I think it would be useful to start coordinating deployments by "staging" big changes first within some dedicated branch, which would also have a dedicated deployment (e.g. on `dev.dandiarchive.org`), probably with #269 in mind for that deployment and e.g. re-deployed daily "from scratch".  Then upon obtaining a next desired state it would be "rolled out" by merging it into `master`, tagging (#150) and continuing further development in that branch.
Meanwhile `master` would still be able to obtain critical bug fixes and gets "releases" cut.
Also, additionally deployment from master could happen only upon a tagged release.
This would also allow for better coordination of needed changes within `dandi-cli` (as now needed e.g. for #403).

**Comment by waxlamp** [comment]
Now that we have a staging deploy on Heroku, and Netlify previews on frontend PRs, I think what is left to do is:
- implement the branch infrastructure and promotion policy needed to make use of staging
- possibly set up a similar thing for Netlify (above and beyond the deploy previews)

@dchiquito can you weigh in with your thoughts?

**Comment by waxlamp** [comment]
I believe we have implemented a usable workflow and this can be closed.
