### ISSUE TITLE
Set up first end to end test

### ISSUE THREAD

**Issue by dchiquit** [dandi/dandiarchive#415]
Set up the first "hello world" end to end test. Most of the work here is setting up the dependencies, namely Jest and Puppeteer. https://github.com/dandi/dandiarchive/tree/master/test should be a decent starting point to copy from (ignore the `jest-puppeteer-vuetify` helper for now).
The actual test doesn't have to do anything significant, just verifying that the front page loaded and maybe a link click are sufficient. The first action in any VIIME workflow is to upload a CSV, which is not trivial in Puppeteer, so that's a stretch goal.

**Comment by dchiquit** [comment]
lol wrong project

**Comment by AlmightyYakob** [comment]
:shipit:
