### ISSUE TITLE
Fix extra slash in UI asset download redirect

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#419]
The endpoint it directs to is:
```
https://publish.dandiarchive.org/api//dandisets/000003/versions/0.200605.1956/assets/05570abd-3f2b-4cac-8411-2061d866e7f5/download
```

where it should be:
```
https://publish.dandiarchive.org/api/dandisets/000003/versions/0.200605.1956/assets/05570abd-3f2b-4cac-8411-2061d866e7f5/download
```

`/api//` -> `/api/`

**Comment by AlmightyYakob** [comment]
I really don't understand why Github is inconsistent with closing linked issues

**Comment by yarikoptic** [comment]
#441 was merged into `publish`, not `master` branch.  That is why it didn't close any issues.  If `Fixes #` was in a commit message withing that PR, then github would close when that branch gets merged into `master`.  But if it is only in a PR description, it doesn't get (re)listed in a merge commit message, thus would not be closed automagically even when `publish` is merged into `master`.  Hope this helps

**Comment by AlmightyYakob** [comment]
> #441 was merged into `publish`, not `master` branch. That is why github didn't close any issues. If `Fixes #` was in a commit message withing that PR, then github would close when that branch gets merged into `master`. But if it is only in a PR description, it doesn't get (re)listed in a merge commit message, thus would not be closed automagically even when `publish` is merged into `master`. Hope this helps

Putting it in the PR description is sufficient to link them (or at least is [supposed](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) to be), and that's what I do on every project I work on, usually without issue. As you can see above, it also mentions that I linked a pull request that will close this issue. For some reason on this particular project, I've had inconsistencies with linked PRs not closing issue when they should have :shrug:.
