### ISSUE TITLE
lock/unlock: return a proper record (not just null) in case of success

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#421]
ATM returns null
```
$> curl -X POST -d "" --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Girder-Token: B0Wm1Rwf8Y2q325cQmUUnUdvSMpBS4jOPeII23bEz4....' 'http://localhost:8091/api/v1/dandi/000028/unlock'  
null
```

**Comment by mgrauer** [comment]
@yarikoptic I think the reason we wanted this was so that the `result` object wouldn't be `None`. I looked at this further and saw another potential solution, can you try calling `post` with the additional parameter of `jsonResp=False` instead, and that might fix the issue, in https://github.com/dandi/dandi-cli/pull/130 ?

**Comment by yarikoptic** [comment]
I could try tomorrow... but also remembered that it does return json e.g. in the case whenever there is an error (e.g. already locked etc), so it doesn't feel like the right direction to me.

**Comment by yarikoptic** [comment]
Should I try or we should just expect consistent "return json" behavior from the API?

**Comment by mgrauer** [comment]
Let's do what is quickest--given that we want to migrate away from this service.

Does your current exception handling in the CLI work? If so, we could just not fix it here and just come up with something more sane when we migrate the locking service over, and go with your current PR that does the exception handling in the client without having to try the jsonResp=False path. Am I making any sense or just confusing the issue?

**Comment by waxlamp** [comment]
Mooted by migration.
