### ISSUE TITLE
lock/unlock: scope endpoints within girder

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#422]
We enable read/write but to lock/unlock needs full set of permissions atm

@mgrauer suggests that should be as easy as adding

```python
@access.user(scope=TokenScope.DATA_WRITE)
```

**Comment by mgrauer** [comment]
I think this might need DATA_OWN because ownership of folders is required, for the endpoints that mutate, and possibly DATA _READ for the get endpoints.
