### ISSUE TITLE
Capture person registering dataset as first contributor and contact person

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#425]
update create-a-dandiset endpoint to capture person registering the dataset as the first contributor and contact person

**Comment by mgrauer** [comment]
There is an ordered list of contributors, which should be changeable.

**Comment by waxlamp** [comment]
@mvandenburgh, looks like you worked on a fix for the old Girder 3 system (https://github.com/dandi/dandiarchive/pull/426) but unfortunately that didn't actually make it into master before your internship was up. Could you take on the task of reviving that fix in the current system?

**Comment by mvandenburgh** [comment]
> @mvandenburgh, looks like you worked on a fix for the old Girder 3 system (#426) but unfortunately that didn't actually make it into master before your internship was up. Could you take on the task of reviving that fix in the current system?

Yes I can do that.

**Comment by mvandenburgh** [comment]
Closed by https://github.com/dandi/dandi-api/pull/351.
