### ISSUE TITLE
draft API #341 GUI: comes back from draft dataset navigation into a released version

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#440]
clicking on "eye" icon in https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027/draft/files?_id=5f0640a2ab90ac46c4561e4f&_modelType=folder 

leads to https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027 

which forwards to https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027/0.200721.2222 . 

Expected - get to https://deploy-preview-341--gui-dandiarchive-org.netlify.app/#/dandiset/000027/draft . 

edit: ref #341

**Comment by mgrauer** [comment]
The eyeball icon when browsing a draft should point back to `dandiset/000027/draft` instead of `dandiset/000027` (because this now forwards to the most recent revision)
