### ISSUE TITLE
Add note to GUI about metadata editor being disabled

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#443]
During the schema release, the metadata editor will be broken and will have to be fixed in a later pass, compared to the DLP. So when we land the schema release, disable the metadata editor and add a note explaining how to edit with CLI and when to expect metadata editor functionality to return.

**Comment by AlmightyYakob** [comment]
I'm not sure how I should instruct the user regarding editing with the CLI? @yarikoptic do you have any ideas?

**Comment by yarikoptic** [comment]
Oh, I don't remember "editing with CLI" coming up. It is just yaml, they could just edit it, but it would be bug prone etc. Actually we even put a header into it you download to not edit manually. I guess it just will remain not editable until web UI gets fixed for that, or may be we could just adopt repro shema @satra? ;-)

**Comment by satra** [comment]
@yarikoptic and @AlmightyYakob - let me consider some editing options. but one of the things would be that the cli would validate the yaml in the short term (till the editor is fixed) and upload online.

**Comment by yarikoptic** [comment]
Yes, we can provide that convenience... May be even at least on some systems (not sure about windows) we can start default editor, and validate upon exit and prompt to edit more if anything fails to validate. But isn't reproschema provides editor, or it is too heavy to depend/ship with the client?

**Comment by waxlamp** [comment]
I believe this is moot now.
