### ISSUE TITLE
Indicate required but absent metadata via ui on the DLP

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#459]
On the DLP, we can indicate via a UI element that the dandiset has missing mandatory metadata somewhere close to the edit metadata element.

something similar to linkedin's completed profile option. that section, wherever should also list the version of the metadata schema. and in the future this should reflect a potential path for upgrade.

**Comment by djarecka** [comment]
@satra - is this is still a valid issue? You think it should be closer?

**Comment by satra** [comment]
I think this is part of the design update and the current validation
errors. This can be closed for now.
