### ISSUE TITLE
UI improvement for downloading a Dandiset

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#471]
This issue is to gather UI feedback.

Here's a mockup of a UI on the Dandiset Landing Page to guide users towards downloading the Dandiset using the CLI. There is a way to download a different version than the current version, which is hidden by an accordion view, and then that same widget is shown in the screenshot with the accordion opened.

![Download full dandiset](https://user-images.githubusercontent.com/595023/89813297-7872c000-db0f-11ea-8d64-0f76d9a4a66b.png)

I'm not sure if we want the API key so prominently there, because it is a one time setup (or few time setup) and also it won't be needed for most downloads (only of embargoed data, which isn't designed or implemented yet). 

Another option is to put the Dandi CLI instructions in an accordion, as that is a one/few time setup.

<img width="389" alt="Screen Shot 2020-08-10 at 1 45 08 PM" src="https://user-images.githubusercontent.com/595023/89813485-c5569680-db0f-11ea-8eba-b9ba7c7b1fab.png">

We can also have this overall download widget displayed when the user is exploring the dandiset. Not captured in this screenshot, we will want to display the name of the current 
![Download full dandiset button in view data](https://user-images.githubusercontent.com/595023/89813629-fafb7f80-db0f-11ea-8190-673ccefbd524.png)
dandiset above the hierarchy browser.

**Comment by mgrauer** [comment]
@bendichter @satra @yarikoptic

**Comment by yarikoptic** [comment]
Looks great! Let's do it! ;)

**Comment by satra** [comment]
notes from discussion:

- move `?` icon to `Help` 
- remove API key
- change `DANDI:000006/draft` to the full url 

with these changes, if the implementation is quick, let's implement as soon as we can.

**Comment by mgrauer** [comment]
Thanks for writing those down, I wasn't able to get to it until later:

move ? icon to Help => have a "help ?" at the far right side of that component title bar

change DANDI:000006/draft to the full url => that is the dandiset permalink (not the GUI url)

**Comment by satra** [comment]
> that is the dandiset permalink (not the GUI url)

just to clarify this is only in the case of a draft dataset. for any published dataset it should always use the identifier form as shown in the figure above.
