### ISSUE TITLE
remove contributor in metadata page

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#481]
I'm using the web form to create the metadata file, and I don't think it is currently possible to remove a contributor entry once it is created. If you accidentally duplicate a contributor entry, what is the workflow for removing the extra one? Would it be possible to create a mechanism for this?

**Comment by mgrauer** [comment]
Which dandiset?

**Comment by bendichter** [comment]
I ran into this problem with https://gui.dandiarchive.org/#/dandiset/000035/draft. To be clear, I can fix this myself by editing the metadata file in Girder or by uploading a YAML file that I manually edit. I'm more thinking about the user experience of someone who does not have access to Girder and wants to create the metadata entirely with the UI.

**Comment by mgrauer** [comment]
Got it, thanks for clarifying--I was going to point you to Girder metadata editor to solve your immediate problem, but you are good there it seems.

**Comment by satra** [comment]
i believe this is now addressed with the new meditor.
