### ISSUE TITLE
dandiset URLs

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#482]
The url of each dandiset now matches the ID, which is great! (e.g. `https://gui.dandiarchive.org/#/dandiset/000035/draft`)

However the URL listed on the metadata page is slightly different: `https://dandiarchive.org/dandiset/000035/draft`

If I try to put `https://dandiarchive.org/dandiset/000035/draft` into the address bar, the page does not render and I get a spinning wheel forever.

Is one for viewing the dataset and the other for downloading it, or is there a bug somewhere? Which of these is meant to be the URL that we use to share with others?

Sorry if this is a duplicate issue. I tried to find it but not sure what to look for.

**Comment by satra** [comment]
@bendichter - this is because the redirector PR was not merged and deployed. just did it. should be ok now. the gui URLs should not be used for any reference to datasets. the permalink is what is relevant.

**Comment by satra** [comment]
also the new download ui should guide a user as to what to use for downloading.

**Comment by bendichter** [comment]
@satra it's working now, thanks!

**Comment by mgrauer** [comment]
Good catch on redirector merge!

BTW, I'd like to improve the usability of the permalink, see https://github.com/dandi/dandiarchive/issues/470
