### ISSUE TITLE
displaying 0 GB

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#487]
As I scroll through the available datasets, some of the larger ones start by listing the size as 0 GB and then get updated after about 10 seconds to the true size. This is misleading, because there are datasets in DANDI that are truly 0 GB and a user might use this to determine if the data from a draft dataset has been uploaded. Would it be possible to either

a) cache the size of these datasets and display them properly as the page is rendered

 or

b) wait to show the size until we can display it correctly

**Comment by AlmightyYakob** [comment]
Waiting to show the size until it's been fetched is probably the best approach, and is easily done.

**Comment by yarikoptic** [comment]
I think this is no longer observed, https://gui.dandiarchive.org/#/dandiset shows sizes
