### ISSUE TITLE
Remove folder from dandiset details and use published dandiset data

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#490]
Once the `size` field is available on the `version` model in the publish app, then the dandiset details can display data per version, instead of always being locked to girder.

![Screenshot from 2020-08-28 17-15-10](https://user-images.githubusercontent.com/11370025/91615649-09d89380-e952-11ea-9c7e-18d366ba0add.png)

We currently display the number of folders in the dandiset, however folders don't really exist in our published archive. To remain consistent, I think we should remove this display from the dandiset details entirely. If folders are supposed to represent individual subjects, then we should handle that explicitly, instead of referring to them as folders.

**Comment by waxlamp** [comment]
I think this is fixed; re-open if not, @AlmightyYakob.
