### ISSUE TITLE
dandi archive in microsoft edge

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#496]
just heard this from a biccn collaborator:

> none of the DANDI archive links I have work using the Microsoft Edge browser; use something else. 

no further details yet, but i can ask them to chime in here.

**Comment by yarikoptic** [comment]
I have tested (browsed randomly on a windows 7  VM + recently installed edge) and everything seems to work just fine

**Comment by yarikoptic** [comment]
@satra please ask or we should just close this one (I failed to reproduce)

**Comment by satra** [comment]
jimmy is corresponding with mike over email

**Comment by satra** [comment]
I think this has been addressed.
