### ISSUE TITLE
some contact information not showing up on dataset listings

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#503]
when viewed in the dataset listing (page 5) this dataset doesn't show contact info.

example: https://gui.dandiarchive.org/#/dandiset/000038/draft

did we not add that the owner is automatically added as contributor to metadata in the current scheme?

**Comment by waxlamp** [comment]
Indeed, #425 is still active but Mike V. is working on it now.

@satra, is there an action to take on dandiset 38? I imagine after the correct behavior is implemented, we may want to autofix all contactless dandisets in a careful one-time operation? If that's the case, I can add that as a TODO to #425 and close this issue in favor of that.

**Comment by satra** [comment]
This is general and we can add owners as contributors to any dandiset that doesn't have one. Btw, this is true of license as well so, creating a dandiset should also ask for a license.

**Comment by waxlamp** [comment]
Sounds good. I'll close this in favor of #425 and #755.
