### ISSUE TITLE
Sharing UI 

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#504]
This issue is for determining a **sharing UI** to implement (see #470 for original super-issue). The options are as follows:

# Option 1 (combined with shareable link UI)
![Sharing - Option -1](https://user-images.githubusercontent.com/2903332/98583010-bcea3500-2291-11eb-9ed6-4e57a6da8c69.png)

# Option 2 (like Option 1, but showing title and version number as well)
![Sharing - Option -1B (showing title and version number in dropdown)](https://user-images.githubusercontent.com/2903332/98583061-cc697e00-2291-11eb-9b6b-26ea421e9544.png)

# Option 3 (separated from shareable link UI)
![Sharing - Option -3](https://user-images.githubusercontent.com/2903332/98583154-e86d1f80-2291-11eb-8e9d-2f1311f3e98f.png)

Please vote for which option you like best:
- "hooray" for Option 1
- "rocket" for Option 2
- "eyes" for Option 3

and feel free to discuss as usual in the comment thread. Once we determine which option we want to go with, we can continue with an implementation.

**Comment by waxlamp** [comment]
I myself like Option 2 best, because the shareable links always feel like the final, backup method of sharing in case none of the readymade sharing options is what you want. Including the title and version number is a subtle cue to make sure you are sharing the dataset and revision you mean to.

**Comment by mgrauer** [comment]
From a meeting: Satra said he likes option 2 (rocket) with the bottom part sliced off, and then in addition, option 3 (eyes), which is where the sliced off part goes.

I'm for this also.

🚀 🪒 👀

**Comment by yarikoptic** [comment]
Could also add `DataLad/GitHub: https://github.com/dandisets/000029` (well, pointing to a  tag whenever we have them)

**Comment by waxlamp** [comment]
Here's a Frankenstein's monster screenshot showing what we'd like (as described by Mike [above](https://github.com/dandi/dandiarchive/issues/504#issuecomment-724220824)):
![hybrid](https://user-images.githubusercontent.com/2903332/100652291-b4c36980-3314-11eb-8c5e-2c2ad0bb0986.png)

The placement of the shareable links menu is not correct; I placed it to the left of where it should go so it wouldn't crash into the sharing menu, for illustrative purposes. In the app, both menus will not generally be openable at the same time.

@dchiquit, is this sufficient to execute on this feature?

**Comment by waxlamp** [comment]
I'm surprised this is still open... I'm pretty sure we have solved this by now.
