### ISSUE TITLE
some metadata not showing up in current metadata editor

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#510]
some of the properties (e.g., species) are not showing up as an available for editing in the current metadata editor. the keys and values show up in the json/yaml side panel and is in the database. to recreate the bug open dandiset 4 as a privileged user in the metadata editor.

this also makes me think that we should have a sort of debug mode of the metadata editor that can show dandiset metadata in edit mode for non owners (without allowing them to save it). this bit can be queued up after the api upgrade.

**Comment by waxlamp** [comment]
> this also makes me think that we should have a sort of debug mode of the metadata editor that can show dandiset metadata in edit mode for non owners (without allowing them to save it). this bit can be queued up after the api upgrade.

Thanks for this suggestion, @satra; I've opened #513 to track this idea.

**Comment by AlmightyYakob** [comment]
> some of the properties (e.g., species) are not showing up as an available for editing in the current metadata editor. the keys and values show up in the json/yaml side panel and is in the database. to recreate the bug open dandiset 4 as a privileged user in the metadata editor.

@satra Since the new editor will be introduced soon, I don't plan on addressing this in the existing editor.

**Comment by satra** [comment]
@AlmightyYakob - do you know why it stopped showing up in the existing editor? it used to in the past. it almost seems like something was made readOnly in some schema.

**Comment by AlmightyYakob** [comment]
> @AlmightyYakob - do you know why it stopped showing up in the existing editor? it used to in the past. it almost seems like something was made readOnly in some schema.

I'm not sure, it could be due to the recent schema updates.

**Comment by waxlamp** [comment]
I believe this is solved now.
