### ISSUE TITLE
organism field not showing in yaml as well as editor

### ISSUE THREAD

**Issue by Saksham20** [dandi/dandiarchive#511]
I have uploaded this dataset: https://gui.dandiarchive.org/#/dandiset/000045/draft
for which I'm unable to see organism related fields like species, age, sex etc. Its neither in the yaml file nor under the add fields option in the editor. 
The nwbfiles have this info but under a custom extension of 'Subject'.

**Comment by satra** [comment]
@Saksham20 - this has been disabled for now. let me know which datasets need this info and i can add it in manually. the reason is that this should be pulled out of the NWB files in the future. But this transition will now happen within the new API server and updates.

**Comment by Saksham20** [comment]
> @Saksham20 - this has been disabled for now. let me know which datasets need this info and i can add it in manually. the reason is that this should be pulled out of the NWB files in the future. But this transition will now happen within the new API server and updates.

all of the files are of the same species: Mus Musculus, their age and sex differ within files, can the metadata field sex, age have all those possible values as a list?

**Comment by waxlamp** [comment]
@satra, please let me know if this can be closed.

**Comment by satra** [comment]
yes, organisms are now controlled completely by the NWB metadata.
