### ISSUE TITLE
Add a readonly JSON/YAML view of full metadata in the metadata editor

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#513]
This can be thought of as an escape hatch to show the raw metadata in cases where our heuristics don't reflect the exact metadata structure in the editor forms.

Derived from a mention in #510.

**Comment by waxlamp** [comment]
I am not sure this is still needed. It could be a useful feature but if there's no need for it we can close.

Please advise, @satra and @yarikoptic.

**Comment by satra** [comment]
There are many ways of getting at this, including a download option in the meditor, so I would say we close this

**Comment by yarikoptic** [comment]
FWIW, concur with having it closed.
