### ISSUE TITLE
do not show empty datasets by default

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#521]
We should not count or display empty datasets by default. There should be a toggle to display empty datasets.

**Comment by waxlamp** [comment]
Possible options to consider:
1. Don't show dandisets that have no assets.
2. Don't show dandisets that have no published versions.
3. Don't show dandisets that are explicitly marked as test dandisets (possibly controversial).

**Comment by yarikoptic** [comment]
FWIW -- we though should make sure that all (including empty) are shown in "My dandisets" view or people would keep creating new ones failing to find the one they created X days ago.
