### ISSUE TITLE
Make file browser work with no prepended /

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandiarchive#548]
The Dandiset file browser currently assumes that asset paths will always start with a `/`. The CLI does not, so the file browser needs to be tweaked to render those correctly.

https://github.com/dandi/dandi-api/pull/37

**Comment by waxlamp** [comment]
@dchiquito, I don't fully understand this--can you explain where this shows up as a problem in the GUI?

**Comment by waxlamp** [comment]
@dchiquito ^^^

**Comment by dchiquito** [comment]
I don't see any issues with the / in the UI right now, so if there ever were, they have been fixed.
