### ISSUE TITLE
Remove any type from Dandiset.most_recent_version

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandiarchive#549]
The type of `most_recent_version` needs to be changed to `Version` once girderize is ripped out.

_Originally posted by @AlmightyYakob in https://github.com/dandi/dandiarchive/pull/547#discussion_r562035606_

**Comment by waxlamp** [comment]
@dchiquito, now that we've migrated we can fix this issue (even though we haven't ripped out all of the feature flag stuff), correct?

**Comment by waxlamp** [comment]
@dchiquito ^^^

**Comment by dchiquito** [comment]
This was done at some point.
