### ISSUE TITLE
"Integration" with DataLad

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#55]
DataLad is not the primary workhorse for data logistics in the archive, but as we originally planned in the proposal, and since it comes handy (e.g. to auto-populate our https://github.com/dandi-datasets on github), I think it would be useful to establish some path for "integration" with it.  

DataLad will not be sought as the replacement for some dandi API we might come up with for more efficient within .nwb file data access (e.g. via @magland 's [h5_to_json](https://github.com/spikodrome/administrative/issues/1)) or alike, although in some long run we could see if datalad could be of help here since similar functionality [was requested there](https://github.com/datalad/datalad/issues/3121) already.

In the short term I see it feasible to proceed in a number of alternative ways, and this issue is to discuss and boil them down to the most sensible to us solution (`T#` is for `Todo#`):

- T1 Establish a [datalad crawler](https://github.com/datalad/datalad-crawler/) pipeline to crawl dandi archive to create or update collection of datasets from it. Then for anything which is uploaded to archive (e.g. via `dandi` client) we would be able to get a DataLad dataset. TODOs
    - [x] dandi client should provide API for traversing archive/collection/folder.  That will also be useful for regular downloads and other functionality
    - [x] finally introduce notion of a "dataset" to dandiarchive, as even only for identifying the boundary of it in the hierarchy (next level from collection?)
    - [x] be able to obtain URL/URI to a file from the archive (#54)
- T2 Develop "datalad export2dandi" functionality to export a given local DataLad dataset to DANDI archive
   - note: local datalad dataset would still get populated with URLs to copy of the files in DANDI archive (the same #54)
- T3 complimentary to full blown `export2dandi`, may be `dandi upload` could become datalad aware and 
  - [ ] simply use (#54) to populate URLs for files in a local dataset if it senses datalad dataset undeneath
  - [ ] in metadata record on DANDI provide git annex key for the file (so crawler could use exactly the same backend and even verify correspondence) and also UUID for the dataset

With such a tandem of T1+T2 we would be breaking correspondence between local original DataLad dataset which gets export'ed (as opposed to be published in datalad terms) to DANDI and its later crawled twin-brother.  But I think it is Ok, especially in the short run.  What elements of "breakage" I am talking here about is that (local and github dandi mirror) datalad datasets would 

- get different DataLad dataset UUIDs (mitigated in case of datalad-aware dandi upload T3)
- get unrelated git histories (even though file listings should be the same)
- get unrelated git-annex histories, but git-annex could easily merge them to share information about availability
  - the only gotcha for that merge to make sense is that both local and our mirror should use the same git annex backend (checksum). DataLad by default uses MD5E (md5sum with extension) whenever the default in git annex is SHA256E (mitigated in case of T3)

Also we could possibly make things better via **alternative to datalad export2dandi** approach:

- T4 If our `dandi-datasets` organization would be a canonical "DataLad" mirror of dandiarchive.org datasets, and we could somehow establish proper ways to delegate authentication etc so that for every dataset we establish on dandi archive we automatically create a dataset on github -- then in principle it could be a local datalad which would populate (datalad publish) the dataset on github while for data upload to DANDI archive we develop git-annex external special remote with [export support](https://git-annex.branchable.com/design/external_special_remote_protocol/export_and_import_appendix/) and then it would become a matter of regular `datalad publish` tandem where first content is exported to the special remote (dandi archive) and git repo is pushed directly to github and content.

Thinking about T4 I like it most somewhat, especially if we decide that indeed all (public) datasets on dandi should get their "mirrors" on github.  Since we make ppl authenticate via github we could probably programmatically make those who create those datasets on dandi become collaborators for corresponding datasets on github, thus being able to "datalad publish" to them directly. But it also makes it quite a bit fragile.

Related note: instead of github we could have our own [gin deployment](https://gin.g-node.org), but that questions either may be then if to consider gin for the ultimate backend if we were to replace girder.

**Comment by satra** [comment]
thank you @yarikoptic for laying this out. a few thoughts below. and for the moment let's consider everything public to limit complications of authorization/authentication for sub datasets and derived data.

besides other tooling (e.g., containers), the fundamental thing that datalad provides is a supervision/management of git-annex repos with distributed data sources linked via checksum. it may indeed in the future become an orchestrator (already does a bit with containers and siblings), but a generic one.

1. synchrony. in the short term, if we can create github dandi-dataset on upload to dandi archive that would be good. i would like current things to be driven via the validator and to have one trusted resource for tracking modification. 

2. checksum.  so often we are reliant on trying to match checksum algorithms. other than computational cost, is there a reason not to have multihash support or hash-recompute support on the dandi side?

3. versioning. datasets may be versioned on a slower time scale than changes in data. (like tagging on github). should we allow this or always squash dataset history to versions (from a dandi perspective) i.e. when you upload to dandi that's always a new version.

4. file level atomicity. every file should have a URL. we should return this as a json on upload to the dandi cli, so it can take care of local dataset metadata.

5. rate of change. the closer we are to raw data, the slower that dataset changes, the more we are on the derived side, the faster. we can thus focus on the slower data to start with in the archive and try and build that up.

more generally we want to be able to upload, access, and update datasets, and to merge pieces of datasets to create new datasets. therefore dataset as a construct is going to be useful, and we should discuss these operations on datasets.

in the future of dandi, data could be distributed, and all the fun things related to distribution come into play.

**Comment by satra** [comment]
in terms of datalad and dandi we should decide whether the specific dandi cli uses datalad or we make datalad handle dandi. i think the former is a little easier to customize.

**Comment by yarikoptic** [comment]
FWIW, we do have (for awhile now) DataLad datasets automagically produced/auto-updated and all linked under https://github.com/dandi/dandisets and http://datasets.datalad.org/?dir=/dandi/dandisets.  They use sha256 based git annex backend.  After refactoring of the archive to use dandi-api we should be able to provide "native" (from the archive) access to data blobs based on sha256.  Meanwhile I could potentially expose (as per sha256) all the blobs from S3 even from girder based backend using information in datalad.  
@magland - could you please quickly point me to how could we establish "hashery" (IIRC it uses sha256) interface to data in dandiarchive so your tools could easily access data files in the archive? 
Or you wouldn't think it would be useful ATM since none of the tools you care about would work with .nwb files?

**Comment by yarikoptic** [comment]
;-) seems to be doing fine -- last update to https://github.com/dandi/dandisets reflecting the entirety was done 20 hours ago (which is feasible).

This issue was more "overarching" , but I think we could indeed just close it for now and here since `dandiarchive` now is pretty much the "web-ui" and not representative of the entire archive.  If anything -- we might move/resurrect it elsewhere later (better integration should eventually be achieved at the level of dandi-api)

**Comment by yarikoptic** [comment]
although I've closed it for now, just want to dump an idea:  similarly to how datalad-osf  (see http://github.com/datalad/datalad-osf/blob/HEAD/datalad_osf/git_remote.py) uses `git fast-export` / `fast-import` to serialize/deserialize git history, I think it should be feasible to come up with the support for push/pull operations on datalad'ified locally dandisets, so that the git history etc is preserved, and we do not "mint" our own history .  We would probably limit it operations only to "fast-forwards" and not sure if handling merges etc could be made work, but worth checking.
