### ISSUE TITLE
DJANGO_API: interface shows ?? (not YH) when logged in

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#551]
![image](https://user-images.githubusercontent.com/39889/105741052-de110800-5f07-11eb-8dda-3070c8ca7fb4.png)

**Comment by waxlamp** [comment]
@yarikoptic, are there any error messages in the developer console or the network tab when this happens?

**Comment by dchiquito** [comment]
This was fixed in #552
