### ISSUE TITLE
Q: how/when https://gui-beta-dandiarchive-org.netlify.app is "refreshed"?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#555]
#552 etc got merged but I guess https://gui-beta-dandiarchive-org.netlify.app/#/ is running some prior version, so I decided to ask

**Comment by dchiquit** [comment]
I set another Netlify server pointed at another branch, `django-api`, which is identical to `master` except for having `DJANGO_API` enabled by default. Every time something is merged into `master`, I merge master into `django-api`. There's probably some automation that can be done, but it's probably more work to figure out than to just do the work manually.

I forgot to update `django-api` immediately after merge #552, it's updated now.

**Comment by yarikoptic** [comment]
I believe automation was done via github actions https://github.com/dandi/dandiarchive/actions?query=workflow%3A%22Update+django-api%22  , thus closing.  Please reopen if I am wrong
