### ISSUE TITLE
Interface external resources to act upon files stored in the archive

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#56]
A draft ATM to cross link relevant issues
- binder https://github.com/jupyterhub/binder/issues/175, from there directed to discussion on
- discourse https://discourse.jupyter.org/t/pass-parameters-to-a-notebook-on-jupyterhub-binderhub/1973/

**Comment by yarikoptic** [comment]
there seems to be an extension to allow for what is desired, and works with binder by urlencoding params within 'urlpath'.  I have tried with our jupyterlab, but haven't succeeded yet ([asked now](https://github.com/manics/jupyter-notebookparams/issues/1)): https://github.com/manics/jupyter-notebookparams .

**Comment by mgrauer** [comment]
I'm going to close as stale.
