### ISSUE TITLE
Set up a test deploy

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#561]
See [original discussion](https://github.com/dandi/dandi-api/issues/78#issuecomment-771713186).

**Comment by yarikoptic** [comment]
just to make it clear (since not much detail in description here): this is for "post-migration" since meanwhile we could just torture  https://gui-beta-dandiarchive-org.netlify.app/ instance (which is pretty much the test deploy), correct?

**Comment by satra** [comment]
also to clarify the database behind this and the bucket behind this would not be the production databases or buckets.

**Comment by waxlamp** [comment]
Both of you are correct. My vision of this is to set up a totally separate copy of the app that we can use to do any testing without fear of breaking anything that matters. But we should hash out details "post migration".

**Comment by waxlamp** [comment]
This is solved with the introduction of the staging deploy.
