### ISSUE TITLE
(wrong) dandiset id persists within URL while browsing "drafts"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#562]
it probably does not apply to new api based one yet, but can't be certain due to outstanding #554 

Originally reported by @djarecka in https://github.com/dandi/dandi-cli/issues/349#issuecomment-772103306 .
If you go to "drafts" folder while browsing some dandiset, that dandiset ID persists in url and even when you then switch to another dandiset. Steps to follow to see are in https://github.com/dandi/dandi-cli/issues/349#issuecomment-772103306

**Comment by waxlamp** [comment]
I don't think this is relevant anymore: I cannot reproduce according to the linked instructions, since there is no way to carry out the last step.
