### ISSUE TITLE
DJANGO_API: landing/browse on existing dataset keeps "spinning"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#565]
going to https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000009/0.210126.1624/files
just shows never ending "spinning bar"

might be related to now closed #554

**Comment by satra** [comment]
there is no published version on that dandiset. however, we should show a UI response that either says version not found or something.

**Comment by yarikoptic** [comment]
in a rush/mess of things -- it used to be a published dandiset (thus I got that URL) which I later overloaded with the one from girder instance.  I am no longer 100% certain, but pretty certain that when I filed this issue it was not yet "overloaded".  But oh well -- I guess we will figure out if all is good after we upload some files to draft and "publish" .   So it might be the same issue "visually" but for different causes.

**Comment by yarikoptic** [comment]
similar issue for just going to some dandiset which doesn't exist , e.g. ATM there is no https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000004

**Comment by yarikoptic** [comment]
FWIW -- issue persists (we have 000004 now, try https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000114)

**Comment by waxlamp** [comment]
Just to be clear, the issue here is that for a well-formed URL pointing to a dandiset that doesn't exist, rather than a 404-based error, we're showing an infinite spinner. Is that right?

**Comment by satra** [comment]
correct.

**Comment by yarikoptic** [comment]
retitled... I think this is what causes webshots (https://github.com/dandi/dandi-api-webshots) to time out and entire action to error out if someone removes some dandiset while webshots are going through pre-fetched list of dandisets

**Comment by satra** [comment]
i believe this is fixed. please reopen if still an issue.
