### ISSUE TITLE
DJANGO_API: download of an asset fails

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#571]
follow up to #570 (I think it was first file within https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000008/draft/files?location=sub-mouse-AAYYT%2F) -- I have waited for all download buttons to appear and then waited for a while for download to start but it only gave me "heroku --tail" or alike log message that there was an error -- so please check in the logs what happened.  After I finished filing #570 and tried again, it seems download worked ok

**Comment by waxlamp** [comment]
Going to close--please re-open if there's still a problem.

**Comment by yarikoptic** [comment]
FWIW, I did go to https://gui.dandiarchive.org/#/dandiset/000008/draft/files?location=sub-mouse-AAYYT%2F and it seems to work
