### ISSUE TITLE
DJANGO_API: takes awhile to open or navigate a dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#572]
Took me 23 seconds of the spinning wheel to see https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000008/draft , and even then after details appeared the spinning wheel is still spinning.   Clicking on "View data" also took > 35 seconds (sorry didn't time).
As for overview page, I have not done any analysis but my wild guess it might be due to stats on number of files and total size being recomputed and not cached ... might also relate to the fact that I am still trying (since bunch of 503 errors) to upload this dandiset.

Marking as important since it is way too long for anything reasonable.

**Comment by waxlamp** [comment]
Fixed via dandi/dandi-api#120
