### ISSUE TITLE
Ensure dandi-cli can correctly upload datalad dandisets to Django API

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#574]
This is a prerequisite to carrying out a full migration. It is specifically about making sure that a datalad-mirrored dandiset can be uploaded through the Django API as equivalent to the original Girder API dandiset. No special support for datalad is needed.

**Comment by yarikoptic** [comment]
by "datalad dandisets" you mean the dandisets we placed under datalad control and present on https://github.com/dandisets, but otherwise they should be just the same dandisets as available from https://gui.dandiarchive.org/ right?

NB asking because it could be some "native datalad support" within dandi-cli to be able to "smartly" (reusing checksum info etc) upload to the archive (not yet planned really)

**Comment by waxlamp** [comment]
I should have been clearer, apologies. This reflects my incomplete (but growing) understanding of how things are organized in this project.

My understanding is that some of the dandisets have been "mirrored" in a sense via datalad so that they are available locally to you. This issue has to do with making sure that those dandisets can be properly uploaded to the Django API in a way that makes the resulting dandiset equivalent to the one in the Girder system.

I don't mean to add any datalad-specific functionality to dandi-cli.

If this clears things up, I can update the issue description and/or title to be clearer.

**Comment by yarikoptic** [comment]
Yes, correct. Just note that they are available not just to me but to everyone as well. I just have an original clone with all data fetched, but anyone can get a similar copy if needed (eg if my server goes bust) as long as there is a an original girder blob store in the bucket

**Comment by yarikoptic** [comment]
dandi-cli can (again) upload to Django API as of dandi-cli 0.12.0-22-g089101e and dandi-api somewhere around d03491247c5ef3fb632b08996dc941822bbdf8a0 (see https://github.com/dandi/dandi-api/issues/36, no version can be deduced ATM).
