### ISSUE TITLE
FOI: load testing library

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#580]
FOI == For Our Information

Just ran into https://molotov.readthedocs.io/en/stable/ which I thought would be quite nice to (ab)use on our instance, especially while in development (may be within dedicated docker composed instance).

**Comment by waxlamp** [comment]
This looks interesting. @yarikoptic would you mind making a note of this in your personal documents? Unless something is actionable, I'd like to keep it out of the issue tracker.

**Comment by yarikoptic** [comment]
github is my "personal documents" ;) So the note is made (here), and it is generally ok to just close `FOI:` issues "upon reading".  It keeps them available for search etc if later someone decides to look up anything on "load testing" (so - would be "shared knowledge" instead of "personal").
