### ISSUE TITLE
Establish at least basic "Integration" with neurostars

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#584]
"Integration" could entail just implementing basic referencing, but could be more later 
- [x] we already have `dandi` tag on neurostars.org
- [ ] add "neurostars" link to the dandiarchive.org website, even if without specific linkage to dandisets, could be "Community: [search](https://neurostars.org/search?expanded=true&q=tags%3Adandi) or [ask a new question](http://whateverlinkshouldbe-to-lead-to-posting-interface-with-dandi-tag-added)".
- [ ] figure out how we could "link" neurostars posts to a specific dandiset.  Most likely we cannot use per-dandiset tags (to not abuse tagging system) and would need some other way to link a specific question to a dandiset
- [ ] may be in addition to a tag (above) we might want to establish a dedicated category (`DANDI Archive`) in addition if it would somehow facilitate above "linkage"

**Comment by waxlamp** [comment]
> * [ ]  figure out how we could "link" neurostars posts to a specific dandiset.  Most likely we cannot use per-dandiset tags (to not abuse tagging system) and would need some other way to link a specific question to a dandiset

Why not just a link to the dandiset in the post text itself--what's gained by using an out-of-band mechanism to link back to a dandiset?

**Comment by djarecka** [comment]
right now we suggest to ask questions via helpdesk, do you want to change it? if we add a neurostar link, we should be clear when do we want people ask question using neurostar and when using helpdesk

**Comment by yarikoptic** [comment]
ok, it doesn't have to be neurostars -- we can "integrate" with helpdesk. ATM I do not see any mentioning of the helpdesk on DLP and discussions on helpdesk are nohow associated with specific dandisets.  

By "integration" I mean to
- offload actual discussions etc to some other platform
- ideally have some UI block on DLP which
  - lists "discussions" associated with that dandiset
  - allows to search among those
  - allows to submit a new question/discussion

I didn't check github's `discussions` API  but I guess something like that could be achieved.  We could probably mint a label per each dandiset?

**Comment by waxlamp** [comment]
We could simply open a new discussion thread on Neurostars for each dandiset, but that seems very abusive. An easier and less abusive practice might be to link to Neurostars from the DLP with a prebaked search for the dandiset itself. A separate button could link to a new topic on Neurostars with the URL of the dandiset filled in. I wonder if the Neurostars people might have other ideas.

Final (wild) idea is for us to host or pay for a dandi-specific discourse instance: https://www.discourse.org/pricing.

**Comment by waxlamp** [comment]
@yarikoptic I would like to close this if there's nothing actionable to do here (perhaps in favor of a more general issue that aims to set up discussion threads for dandisets).

**Comment by yarikoptic** [comment]
ok, it seems that we decided to not "bother" (ab)using neurostars... filed a more generic wishlist https://github.com/dandi/dandiarchive/issues/1017 to replace this one
