### ISSUE TITLE
Optimize loading of meditor on dandisets with large metadata

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#588]
When trying to click the "Edit Metadata" button on the Dandiset Landing Page, there's quite a delay in switching to the new view, when there's a lot of metadata on that dandiset (likely due to the large amount of component rendering / data validation that occurs). A good example of this is dandiset [000004](https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000004).

We should look into ways that this can be optimized, or at the very least, display something to indicate that it is loading. The latter might not be possible, as I believe the browser is mostly running JavaScript (as opposed to drawing/rendering) during that time. More investigation is needed.

**Comment by djarecka** [comment]
is this still a valid issue? not sure how to check it without written access to this big dataset

**Comment by waxlamp** [comment]
I think this can be closed for now.
