### ISSUE TITLE
Add description of search grammar when there are no search results

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#59]
Start with this text:

`Please use our search grammar.`

**Comment by mgrauer** [comment]
Can use this [feature](https://github.com/girder/girder_web_components/pull/194) from GWC.

**Comment by matthewma7** [comment]
![image](https://user-images.githubusercontent.com/3123478/69434394-8aa39880-0d0b-11ea-9342-2b77ff8186f1.png)

Hi @mgrauer, please advice for the text. Anything in the red box is customizable.

**Comment by yarikoptic** [comment]
> Please use our search grammar.

I guess then somewhere really close there should be some link or popup leading to description of the grammar ?

**Comment by mgrauer** [comment]
@yarikoptic Yes. The idea here was @matthewma7 was going to get me a working feature where I could add additional text. `please use our search grammar` is a placeholder until I can add more info.
