### ISSUE TITLE
DJANGO_API: 000003 was freshly updated but dates/sizes are wrong and goes to a release not draft

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#597]
I finished uploading (2.6 TB) on Mar 24 21:27:01, and ATM (Mar 25 08:27) going to https://gui-beta-dandiarchive-org.netlify.app/#/dandiset lists it as 
![image](https://user-images.githubusercontent.com/39889/112472941-17b59200-8d44-11eb-9635-1586933ab904.png)
and clicking on it ends up being in an empty released version.

Clicking on draft - it does get to a populated one but still says "Last updated March 23, 2021 at 11:38 AM" which is not reflective of 

I will leave it to dandiarchive/api folks to triage and possibly split into multiple (why not draft? why wrong date?) or move (might be dandi-api issue)

**Comment by djarecka** [comment]
@yarikoptic - is this still a valid issue?? sounds serious...

**Comment by yarikoptic** [comment]
Probably no longer pertinent indeed
