### ISSUE TITLE
DJANGO_API: Double / / if have 3rd level directory

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#599]
See current test ds https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000/draft/files?location=sub-1%2Fsub-1_ses-10_cell-1.z%2F (goes a bit further than our 2 level `dandi organize`'ed datasets, as eg might happen later with zarr or any BIDS dataset with sessions)

![image](https://user-images.githubusercontent.com/39889/112637507-9f6ad180-8e14-11eb-9de7-4448f07da9e1.png)

**Comment by satra** [comment]
@sanuann - this should be a simple fix and perhaps a way to get used to the codebase. could you please send a PR to fix this?

**Comment by yarikoptic** [comment]
even at two places in the path for https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=derivatives%2FEPIC%2Fsub-I46%2F
![image](https://user-images.githubusercontent.com/39889/117017808-e83e6180-acc1-11eb-8cdf-fcae1d482be7.png)
