### ISSUE TITLE
DJANGO_API: takes awhile to get to the 2nd level subdirectory for a dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#600]
To facilitate future support of large (in # of files, https://github.com/dandi/dandi-api/issues/78) dandisets I am in the midst of uploading a test dandiset with 1,000,000 assets . By now (running for probably 18 hours) uploaded only about 43k according to the summary of https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000/draft .

An interesting behavior already showed up.
- navigate: "View Data", "sub-1/" , "sub-1_ses-10_cell-1.z" -- *everything (besides minor UI glitch https://github.com/dandi/dandiarchive/issues/599) is working nicely and not too slow*
- now if you click on "sub-1" in the breadcrumbs navigator then
  - it would take you many (I waited for 20) seconds: *should be at least as fast as you went there originally (so not sure what holds it up)*
  - meanwhile breadcrumbs path would show the target destination (`sub-1`) while the files listing pane would show old sub-directory content (while "spinning bar" is still spinning and some times getting stuck even) - make view a big confusing: IMHO *should clear the pane* (before repopulating with the new listing)

**Comment by yarikoptic** [comment]
Just ran into https://github.com/open-telemetry/opentelemetry-python and wondered if it could come handy if issue boils down to dandi-api

**Comment by waxlamp** [comment]
Do you still have this 1e6 test dandiset? The best I can do at the moment is https://gui.dandiarchive.org/#/dandiset/000045/draft/files?location=, which only has ~6000 assets in it, but at least there's no significant lag in loading the file browser. (But it doesn't have a two-level hierarchy either.)

**Comment by yarikoptic** [comment]
- go to https://gui.dandiarchive.org/#/dandiset/000052
- navigate down to https://gui.dandiarchive.org/#/dandiset/000052/draft/files?location=dataset%2Fsub-MGH_19-1_021520%2Fmicroscopy%2F
- click on breadcrumbs to go one directory up

extra side effects discovered while trying to re-prepare the reproducing workflow here:
- leaving that tab with deep down directory while it still is populating the download urls (hopefully would be fixed whenever that https://github.com/dandi/dandi-api/pull/312 is finished/used), and coming back to it - just gives me the white page

so what I think is happening is that web ui session is waiting for all download buttons to be populated, and doesn't redraw anything (if I go up, or just come back to the page in the tab) until "it is done getting all download buttons"

but also there is something funky about state -- going back and forth (via our "navigator") https://gui.dandiarchive.org/#/dandiset/000052/draft/files?location=dataset%2Fsub-MGH_19-1_021520%2Fmicroscopy%2F and the above https://gui.dandiarchive.org/#/dandiset/000052/draft/files?location=dataset%2Fsub-MGH_19-1_021520%2F -- some times it is fast to go up, some times start to take time

**Comment by mvandenburgh** [comment]
I looked closer at the problem and the slowness does indeed seem to be a result of the client waiting for all the download buttons to be populated as @yarikoptic said. To get those download links the client sends a request to the server for each of the files in the current directory, so when you have hundreds/thousands or more files in a directory it lags a lot. 

It seems we need some way of limiting the displayed files so only a manageable number is shown at once. Is pagination an option here UI/UX-wise?

**Comment by yarikoptic** [comment]
I would not mind to re-introduce pagination (I believe it was in place with an older web ui), but I guess it would be best if it was just interfacing pagination of the API.

So IMHO it would be better to finish up https://github.com/dandi/dandi-api/pull/312 .  Unfortunately "pagination" there would be just at the level of a "return" values serialization, and we would still need to go through all the assets to deduce all the directories (and as a side-effect their sizes).
