### ISSUE TITLE
DJANGO_API (beta instance): should provide correct download command

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#603]
If you click on "Download" for any dandiset you would see instructions like

```
dandi download https://dandiarchive.org/dandiset/010000/draft
```
but that would redirect to our original (girder) instance.  Sure thing it would be correct after we migrate fully.  But in preparation for migration we would like to invite users (during hackathon) to try out API and new Web UI.  This would bring confusion/questions.

One possible solution (without involving tuning up redirector) just to have URL pointing to the beta instance instead of redirector, e.g.

```
dandi download "https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000/draft"
```
and if it is not hard-coded but taken from actual instance, even when "migrated" it should show the actionable (by `dandi-cli`) URL.

Not marking it for "migration" project/milestone (since if migrated without fixing it -- it would "autofix") but giving severity label since we need it **before** migration happens.

**Comment by waxlamp** [comment]
I believe this is now moot.
