### ISSUE TITLE
issues with gihub oauth for registration

### ISSUE THREAD

**Issue by tgbugs** [dandi/dandiarchive#606]
I get the following messages when I try to register via GitHub. I got an email from GitHub telling me that the link had been made, but dandi doesn't seem to have made the link. I'm also seeing a `502` error to `https://girder.dandiarchive.org/api/v1/oauth/github/callback?code=4415a06dae5631ee8123&state=Ej0lUivdkcXgfH8MBLrtR6Ee1lXHHy2hzqpbL2l6bkEARDvJyMVlo9H7ITecLDRn.https%3A%2F%2Fgui.dandiarchive.org%2F%23%2Fuser%2Flogin%3FreturnTo%3D%257B%2522name%2522%253A%2522home%2522%2C%2522query%2522%253A%257B%257D%2C%2522params%2522%253A%257B%257D%257D%23girderToken%3D%7BgirderToken%7D__`

```json
{
    "message": "This GitHub user has no registered email address.",
    "type": "rest"
}
```
```json
{
    "message": "Invalid CSRF token (state=\"pW6p2ki2OEb0ea9sA2XnQ0h3sSOTYeoUbkMzbgKE0zvopBB7cUWBRNQ4skWuCuMp.https://gui.dandiarchive.org/#/user/register#girderToken={girderToken}__\").",
    "type": "rest"
}
```

**Comment by satra** [comment]
that's weird. i'm assuming you do have a registered email address :) the oauth process does request that scope as far as i know.

**Comment by satra** [comment]
@mgrauer - any thoughts here? i don't see the user on girder. @tgbugs - just to clarify you went through dandiarchive.org right?

**Comment by satra** [comment]
can you try to redo it after clearing any session storage. (at least on chrome/brave: developer tools-> application-> clear stite data).

**Comment by tgbugs** [comment]
No site data in firefox or chrome, same issue on both browsers.

**Comment by mgrauer** [comment]
@tgbugs @satra and I debugged this in the NWB/DANDI hackathon together in Gathertown. The issue was that @tgbugs didn't have a verified email in GitHub. Once he verified his email in GitHub, he was able to register on the Dandi GUI (Girder based).

**Comment by tgbugs** [comment]
Thanks for the debug, I have no idea how that one was unverified, but apparently it was.
