### ISSUE TITLE
DJANGO_API: ensure that schema version handling is in sync (dandi-cli, web-ui, and dandi-api)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#614]
Just a stab that before we click "migrate" we are in sync on what metadata version is defined (dandi-cli), created (dandiarchive), expected (dandi-api)

**Comment by waxlamp** [comment]
The API and the web UI are currently using schema version 0.1.0. Is that what dandi-cli is using?

**Comment by satra** [comment]
dandi-cli is at `0.2.0`

**Comment by dchiquito** [comment]
https://github.com/dandi/dandi-infrastructure/pull/51 should fix this for now
