### ISSUE TITLE
DJANGO_API: Publish button should not appear for an empty (no assets) dandiset

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#617]
Since `dandiset.yaml` is not an asset, freshly created or even with modified metadata dandiset is empty, and should not be allowed to be published.  No point to have Publish button (although could be just channeled via error from dandi-api, I think it would be a better UX to not have it/have it disabled)

**Comment by djarecka** [comment]
i believe this is fixed now
