### ISSUE TITLE
Make "title" for the back button clickable as well

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#620]
ATM , e.g. on https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000003, we have `<-- Dandiset Dashboard` where only smaller `<--` is clickable and `Dandiset Dashboard` is just text. IMHO it would be a better UX if the entire `<-- Dandiset Dashboard` would be a clickable element leading to the dashboard

**Comment by waxlamp** [comment]
In this example, `Dandiset Dashboard` is the title for the current page. I don't think that text should be a link that takes you somewhere else.

Similarly, upon clicking the back arrow, the title reads `Public Dandisets`. I certainly wouldn't expect that title to be a hyperlink to somewhere else either.

**Comment by satra** [comment]
`<--` is a weird icon for taking one back to public dandisets. 

i think that icon should be changed, but then there is duplication (we already have public dandisets on that page). so ideally it is back but takes you back to where you came from, which at the moment it doesn't. it takes you to public not the specific page of public dandisets you were looking at. 

overall it's a misleading UI i think.
