### ISSUE TITLE
back arrow from metadata page returns to page 1

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#621]
When the back arrow is clicked on viewing the landing page of a dandiset after browsing dandisets, it takes one to the first page of listings. in that case the icon should be replaced with a home icon. if not, it should take you back to the last state.

**Comment by sanuann** [comment]
do we want this to return to the home page or the last state?

**Comment by satra** [comment]
i think the arrow was removed. there may be an open PR to this effect. #690

**Comment by waxlamp** [comment]
Yes, I will work on getting #690 merged asap.

**Comment by waxlamp** [comment]
Since the arrow was removed, this is solved.
