### ISSUE TITLE
Searching on search results page does not update results

### ISSUE THREAD

**Issue by rly** [dandi/dandiarchive#626]
After searching with a term and going to the search results page, e.g., https://gui.dandiarchive.org/?#/dandiset/search?search=steinmetz , entering a new search term and pressing enter / clicking the search icon does not update the results. The URL does update, and the search results do update when I refresh the page though.

**Comment by satra** [comment]
i believe this is fixed in the new GUI (hopefully rolling out early next week):

https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/search?search=steinmetz
