### ISSUE TITLE
Migration execution plan

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#629]
- [x] 1. Prepare email text to send to users (@satra)
- [x] 2. Prepare a downtime message in a public webpage (@satra)
- [x] 3. Email all users about the downtime (@satra)
- [x] 4. Repoint girder.dandiarchive.org and gui.dandiarchive.org to dandi.github.io (@waxlamp)
  - [x]  [PR](https://github.com/dandi/dandi.github.io/pull/28): Add a maintenance notice to github pages
  - [x]  [PR](https://github.com/dandi/dandi-infrastructure/pull/54): Repoint DNS records
  - [x]  [PR](https://github.com/dandi/dandi.github.io/pull/29): Update 404 page on www.dandiarchive.org to show downtime notice
  - [x]  Merge these two PRs (third PR was merged into first, hence only two remain to be merged) when ready (at 11:30am, 2021-04-20)
- [x] 5. Sync up with Girder (@waxlamp)
  - [x] a. Run Daniel's user migration script (`heroku run python manage.py runscript create_placeholder_users --script-args http://girder.dandiarchive.org/api/v1 username password -a dandi-api`) (@dchiquito)
  - [x] b. Verify that Yarik's data backups reflect current state (@yarikoptic)
  - [x] c. Run Yarik's script to create empty dandisets in Django (matched up to existing Girder dandisets) (@yarikoptic)
- [x] 6. Run delete script to fully wipe `/dev` from sponsored bucket (including `DeleteMarker`'d items) (@dchiquito)
- [x] 7. Upload all data to Django (@yarikoptic)
- [x] 8. Run size-based "diff" between Django and Girder (to verify that all assets were uploaded correctly) (@yarikoptic)
- [x] 9. Update redirector
  - [x] Make necessary changes to codebase (@yarikoptic)
  - [x] Redeploy (@satra)
- [x] 10. Merge this [PR](https://github.com/dandi/dandiarchive/pull/634) to merge the `django-api` branch of dandiarchive (to redeploy frontend with feature toggle enabled) (@dchiquito)
- [x] 11. Revert redirections
  - [ ] ~Merge this [PR](https://github.com/dandi/dandi-infrastructure/pull/57) to revert this [PR](https://github.com/dandi/dandi-infrastructure/pull/56) which redirected girder.dandiarchive.org to www.dandiarchive.org.~
  - [x] Merge this [PR](https://github.com/dandi/dandiarchive/pull/632) to revert this [PR](https://github.com/dandi/dandiarchive/pull/631) which redirected gui.dandiarchive.org to the downtime notice at www.dandiarchive.org.
- [x] 12. Release new CLI, deprecating all previous versions (@yarikoptic)
  - [x] a. Release new CLI which can switch to dandi-api automagically upon redirector record adjustment (@yarikoptic, @jwodder )
  - [x] b. Announce all previous versions bad in .et (@yarikoptic)
  - [x] c. Boost `cli-minimal-version` in redirector (@yarikoptic)
- [x] 13. Take a test flight of Django API/frontend by using Netlify address: https://gui.dandiarchive.org/
- [x] 14. Run script to update all Django dandiset created/modified times from Girder (@dchiquito)
- [x] 15. Revert downtime announcements (@waxlamp, @dchiquito)
  - [x] Merge this [PR](https://github.com/dandi/dandi.github.io/pull/30) to revert this [PR](https://github.com/dandi/dandi.github.io/pull/28) which added downtime notices.
  - [ ] ~Restore the nginx configs on the girder EC2 instance. Delete the existing .conf files and rename `_base`->`base.conf` and `_girder`->`girder.conf`.~ (skipping this in migration to leave old girder instance accessible only via its IP address)
- [x] 16. Email all users about restored service (@satra)
  - [x] Include note about using GitHub accounts to log in (as the only way to do so now)
  - [x] Mention having to create a new API key
  - [x] Mention the new CLI

**Comment by waxlamp** [comment]
Hi everyone - I've created this GitHub issue to make it a bit easier to coordinate the many actions that we'll be taking this week to execute the migration and turn off the Girder instance permanently.

I have listed out the steps and assigned points of contact for each. Feel free to discuss here if you need help with any step, or simply report progress, etc.

**Comment by yarikoptic** [comment]
FWIW: expanded the `cli` part - AFAIK no new release of `cli` would be needed any longer.  Reality would show if that is true ;)

**Comment by satra** [comment]
@mgrauer - changed item 6 to 4. it's not just an nginx config i believe. i'm ready to send out the email.

**Comment by waxlamp** [comment]
Well done @yarikoptic @satra @dchiquito @mgrauer and @AlmightyYakob!!

**Comment by mgrauer** [comment]
Amazing job organizing this @waxlamp ! and great work from the team to coordinate and grind it out!
