### ISSUE TITLE
no search capability within file view

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#639]
https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=sub-I46%2Fmicroscopy%2F

if a standard browser search is used, it doesn't select or show any entry.

**Comment by satra** [comment]
try this location: https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=rawdata%2Fsub-I46%2Fses-SPIM%2F

**Comment by yarikoptic** [comment]
Tried on the phone: works 
![Screenshot_20210520-161839](https://user-images.githubusercontent.com/39889/119043523-1fca3080-b987-11eb-8773-20ba38462b67.png)

**Comment by yarikoptic** [comment]
Brave made you extra safe @satra!

**Comment by waxlamp** [comment]
Browser search works for me too. This seems to be a problem elsewhere but if there's a connection to the DANDI archive code, please re-open.
