### ISSUE TITLE
dandiset doesn't show up under my dandisets for an owner.

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#641]
@colleenjg cannot see the following dandiset under "my dandiset".

`curl -X GET "https://api.dandiarchive.org/api/dandisets/000037/users/" -H  "accept: application/json"`

```
[{"username":"jeromelecoq"},{"username":"colleenjg"}]
```

**Comment by dchiquito** [comment]
The issue was that the email used to sign up in girder was different from the email associated with the GitHub account. I gave the GitHub account the proper permissions and deleted the placeholder user.

@colleenjg can you verify that you have access now?

**Comment by colleenjg** [comment]
It works now, thank you!
