### ISSUE TITLE
Add "Cite as" button or pane

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#645]
Following the lengthy discussion with @satra in slack, we ASAP need a prominently visible to a visitor guidance on how to cite any particulat dandiset.  I think it could be quickly achieved (even before `publish` functionality lands) by adding a  "Cite as" button next to "Get shareable link " which would open a similar pane with information such as 

"{contributors} {title}, {last-modified year}, https://dandiarchive.org/dandiset/{identifier}/{version}"

Later, whenever DOI-grade metadata records are established and DOIs minted, we should be able to produce citations in a selected number of styles and export (may be just redirect queries with proper headers to doi.org) in various styles for released dandisets.

**Comment by satra** [comment]
old discussion here #470

**Comment by satra** [comment]
with the new metadata structure this should be relatively easy to generate.

**Comment by yarikoptic** [comment]
yeap yeap... thanks for digging the elderly issue out.
And now we got a dedicated issue for it!  FWIW, duplicating from comment in slack: https://pypi.org/project/citeproc-py/ might come handy if we decide to provide similar to zenodo pane as you suggested in that https://github.com/dandi/dandiarchive/issues/470#issuecomment-674569799

**Comment by yarikoptic** [comment]
For all means and purposes #684 (thanks @sanuann @satra et al) addressed this issue
