### ISSUE TITLE
edit metadata takes forever to load

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#646]
i believe this has been reported for a few dandisets.  here is an example dandiset, which has minimal metadata. https://gui.dandiarchive.org/#/dandiset/000043

i know it loads for some and is not related to size of the metadata (for e.g., i was able to edit metadata for dandiset 26 just fine).

this also relates to the more automated testing issue of being able to hit the edit metadata button in our tests.

**Comment by satra** [comment]
the issue has to do with values that do not correspond to the schema. in general we should prevent this from happening at the API level.  i fixed the usability issue temporarily by fixing the relevant piece of metadata (in this case these were orcid identifiers that did not get parsed properly by the metadata converter.

however, i will leave this open for now since we don't have validators in the API, and someone, although unlikely, could potentially use the API to update metadata.

**Comment by yarikoptic** [comment]
FWIW it (browser) even times out for me locally and @jwodder in selenium (https://github.com/dandi/dandi-api-webshots/issues/1#issuecomment-831918453)  on https://gui.dandiarchive.org/#/dandiset/000021

**Comment by satra** [comment]
thanks for the report, will look at the metadata, probably some identifiers are of. we did not do json schema check when we uploaded the metadata and that's probably what's broken.

**Comment by yarikoptic** [comment]
while it is broken - might be a good time to fix up the UI part so it doesn't just hang but rather returns error or smth like that (ref: https://github.com/dandi/dandiarchive/issues/613)

**Comment by AlmightyYakob** [comment]
> while it is broken - might be a good time to fix up the UI part so it doesn't just hang but rather returns error or smth like that (ref: #613)

This might not be so easy, but I could attempt it. The problem is that the UI has to decide to either entirely allow or disallow the meditor to be opened. This could be approached by running json schema validation with a separate tool (probably [ajv](https://ajv.js.org/)), and if it fails, don't show the meditor. However we explicitly allow invalid metadata until publish, so we'd maybe have to only care about specific kinds of validation errors.

**Comment by yarikoptic** [comment]
> This is also separate from #613, as this is a client side bug, with no connection to the API.

Correct in that unrelated to dandi-api, but IMHO there should be a generic/unified way to channel an error message to the web ui user.

**Comment by satra** [comment]
the particular metadata is fixed. but we should run through the check on all the metadata. i think to simplify things the job of the UI should not be to check validity of metadata. it can do so, but we need to ensure that the API server serves up and ingest valid metadata. the word "valid" as we have discussed earlier has several levels. in the current instance of issues we are seeing, it is not about missing metadata, but when metadata values are incorrect.

what the ui will however have to do is to ensure that the metadata and schema version go hand  in hand and support multiple schema versions for both landing page and editing.

**Comment by djarecka** [comment]
is this still a valid issue?

**Comment by waxlamp** [comment]
I think this can be closed. Others can reopen if there are still things to do here.
