### ISSUE TITLE
a way to trigger "Edit metadata" interface in "read-only" (no Save) mode

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#647]
For the purpose of establishing testing and timing of the web ui  we need to be able to trigger "Edit metadata" by dandibot user.  Ref:
I would feel insecure to grant that user full admin privileges.  
We need some way, even if ad-hoc/hardcoded to work only for dandibot,  on web ui end to enable that.

**Comment by satra** [comment]
transferring info from https://github.com/dandi/dandiarchive/issues/627

> three options (in order of preference):
> 1. change to view metadata and make it completely readonly (i believe there is an option in the component to do this)
> 1. change to download metadata (and link to the metadata returned by the api)
> 1. disable this.

3 was implemented, but we should really consider 1.

**Comment by yarikoptic** [comment]
Thanks @satra !  FWIW, I am not sure what "3. disable this" means exactly, and what I see is that "Edit metadata" is disabled for dandibot while in e.g. 000003:

![image](https://user-images.githubusercontent.com/39889/117045881-087c1980-acde-11eb-9def-8c20e4faf1b0.png)

**Comment by satra** [comment]
disable is what has been implemented as a fix. it's not available except for an owner of the dandiset.

**Comment by satra** [comment]
ideally for a non-owner it should become view metadata. the underlying component i believe can be made fully readonly.

**Comment by waxlamp** [comment]
For completeness, it seems like a "view metadata" button could always be there, with an "edit metadata" appearing only for those authorized to do so.

On the other hand, it would be simpler to just have one always-on button that switches from "view" to "edit" with authorization level.

**Comment by yarikoptic** [comment]
To not waste space, I like "view" to "edit" switching button idea.
