### ISSUE TITLE
Provide "id"s for actionable elements in the UI

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#648]
ATM there is no easy and reliable way (besides an xpath like `'//*[@id="app"]/div/main/div/div/div/div/div[1]/div/div[2]/div[1]/div[3]/button[1]'` for "Edit metadata") to identify elements of the UI.  I think there should be an easy way to assign dedicated IDs per each such element (e.g. `edit_metadata_button`) so even if layout changes we have a robust way to find them (for testing).

**Comment by waxlamp** [comment]
Could you identify a list of the UI elements you are focused on for testing currently? We can start with that set just to make your current set of tests easier to manage.

**Comment by yarikoptic** [comment]
ultimate source is https://github.com/dandi/dandi-api-webshots/blob/master/tools/make_webshots.py.  Here is the only two we use ATM:

```python
        login_button = driver.find_elements_by_xpath(
            "//*[@id='app']/div/header/div/button[2]"
        )[0]
```
```python
        edit_button = WebDriverWait(driver, 3).until(
            EC.element_to_be_clickable(
                (By.XPATH,
                 '//*[@id="app"]/div/main/div/div/div/div/div[1]/div/div[2]/div[1]/div[3]/button[1]')))
```
of immediate need. But I don't see why not to add ids to  at least download, view data (we just go to url), publish, manage, Get shareable link "buttons" while at it.
