### ISSUE TITLE
landing page: could progressbar to not disappear until all elements finished rendering to their final form?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#650]
Detected while now grabbing a larger screen for https://github.com/dandi/dandi-api-webshots/ : we started to produce a diff in webshots for every commit .  The diff showed:
![image](https://user-images.githubusercontent.com/39889/117142044-4419f080-ad7d-11eb-8c63-86b04b1c10eb.png)

and indeed if you "flip" between two versions (e.g. get them from https://github.com/dandi/dandi-api-webshots/commit/fd88c1df1fd40ba3abd91fa1acb12d7077f8e6c4?short_path=6fce1b6#diff-6fce1b652b9d5870e6efe7b6cd22355f8eb085f67a44798a6e9c69937cb2e132) you will notice a difference in icon.  I wonder why that might be happening and how could we prevent that?

**Comment by yarikoptic** [comment]
figured it out (I think) -- it is because there is animation which turns it from gray to blue if you are owner (but see #652 which turns it blue regardless).

To mediate - I will just add a 2 sec sleep in the webshotting script.  BUT for longer term solution -- could progressbar to not disappear until all elements finished rendering to their final state?

**Comment by waxlamp** [comment]
> To mediate - I will just add a 2 sec sleep in the webshotting script. BUT for longer term solution -- could progressbar to not disappear until all elements finished rendering to their final state?

We could probably figure this out, but I believe that changing the app behavior to suit specific testing schemes is something of an anti-pattern and generally to be avoided.

I actually believe that the 2 second delay is the correct solution for webshotting--the app behaves correctly as is, and the webshot mechanism is too fast to properly "see" the correctness, so it should be the one to change.

**Comment by yarikoptic** [comment]
well, it depends what disappearing progressbar is signaling: that **all** elements state is ready or just **some** elements state is ready?

not quite a scalable comparison but I hate when webpages, right before I click on something, change their rendering so some other link pops up under mouse cursor.  Here it is similar to some degree: progress bar disappeared but elements are still changing their state.

as for 2 seconds delay: it is just a workaround.  One of the goals for those selenium driven tests is to establish timing on how long each page takes to load.  If progress bar disappears after only "some" elements are ready, we are not getting a complete picture/timing.

**Comment by yarikoptic** [comment]
in greater degree it relates to #638 .  If you go to https://gui.dandiarchive.org/#/dandiset/000026/draft/files?location=rawdata%2Fsub-I46%2Fses-SPIM%2F - progressbar disappears, and then it still takes forever for all download "buttons" to appear.  So it becomes nearly impossible (without some crafty ad-hoc logic) to even time loading of such pages to their "complete" state.

**Comment by djarecka** [comment]
@yarikoptic - i think this is not the case anymore, but please confirm
