### ISSUE TITLE
"Manage" is available for non-owner

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#652]
Discovered while troubleshooting #650 : dandibot user (non-admin and not owner) since can't "Edit Metadata" still gets that "Manage" icon turned blue for it and can edit the owners list.  But upon "Save" progress bar just keeps spinning:  so api refuses to perform action but due to lack of feedback (#613) it just stays at that until I click Cancel

**Comment by waxlamp** [comment]
@sanuann can you take this on?

**Comment by sanuann** [comment]
> @sanuann can you take this on?

Sure, will work on it on Monday.
