### ISSUE TITLE
individual file info

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#654]
![image](https://user-images.githubusercontent.com/844306/117294944-3f1e7500-ae41-11eb-9a03-8a6c43c9570d.png)

The data viewer now does not include any information about the files. If I click download, I have no idea how big of file I am requesting. If I update a file, I can't see from this view that it has been modified. This is really not ideal as a user. I'd much prefer a standard columnar view that you get in standard file explorers

![image](https://user-images.githubusercontent.com/844306/117295349-bb18bd00-ae41-11eb-94c8-8a17605edd04.png)

Features in order by importance:

* size (even better if we can recursively calculate this for folders)
* date modified
* date added/created
* uploaded by (user)
* kind

Even better would be if you could sort on those columns, but just displaying them would be a big help.

I also really liked the side panel for detailed information about individual files. Is there any way we could bring that back?

**Comment by waxlamp** [comment]
I think the sortable columnar display for files is a reasonable ask.

Do you remember what information was included in the detail side panel?

**Comment by AlmightyYakob** [comment]
Depends on https://github.com/dandi/dandi-api/issues/292

**Comment by satra** [comment]
since #292 has now been addressed, can we do a quick hack to add : 
- size of the file
- link out to file metadata (from the api server)
before addressing this issue in more general detail

**Comment by AlmightyYakob** [comment]
> * size of the file

This already exists in the response, so this is easy.

> * link out to file metadata (from the api server)

Do you just want us to link out to the metadata in a new tab like [this](https://api.dandiarchive.org/api/dandisets/000052/versions/draft/assets/46006535-59e4-49d1-88ee-fcf33da6cf7d/)? If not, what exactly do you mean?

**Comment by satra** [comment]
> Do you just want us to link out to the metadata in a new tab like this? If not, what exactly do you mean?

yup. exactly that for now. we can create prettier views later on.

**Comment by waxlamp** [comment]
> since [dandi/dandi-api#292](https://github.com/dandi/dandi-api/issues/292) has now been addressed, can we do a quick hack to add :
> 
> * size of the file
> * link out to file metadata (from the api server)
> 
> before addressing this issue in more general detail
> 
> cc: @mvandenburgh @waxlamp

This has been done via #800 (attn: @satra).

**Comment by djarecka** [comment]
I think this works much better now. There is still an open issue to provide nicer view fo metadata (#587), so I'm closing this now. @bendichter - please reopen if needed
