### ISSUE TITLE
why the squid?

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#655]
![image](https://user-images.githubusercontent.com/844306/117295706-2b274300-ae42-11eb-9ddc-bad59c793d8e.png)

The squid icon takes me back to the dandiset landing page? What is the reasoning behind this? I find it unintuitive.

**Comment by yarikoptic** [comment]
"bubbling up" to the dataset landing page was the intention IIRC.  Indeed we should improve on it.  I would say we take the "Home" icon for that, add it also add Home to "Dandiset Dashboard" on the landing page to "align" perception on its meaning. 
In the "files browser" interface Home icon should IMHO just be replaced with `./` or even better the `{dataset_id}/` in the path breadcrumbs so it is always clear without looking up in a smaller font of a browser url bar which dandiset I am in.

**Comment by waxlamp** [comment]
> "bubbling up" to the dataset landing page was the intention IIRC. Indeed we should improve on it. I would say we take the "Home" icon for that, add it also add Home to "Dandiset Dashboard" on the landing page to "align" perception on its meaning.
> In the "files browser" interface Home icon should IMHO just be replaced with `./` or even better the `{dataset_id}/` in the path breadcrumbs so it is always clear without looking up in a smaller font of a browser url bar which dandiset I am in.

Agreed. Let's:
- [ ] replace the squid with home
- [ ] replace the home with dandiset ID

**Comment by waxlamp** [comment]
@bendichter, we put in a fix for this that should be appearing on the app within a few minutes. Take a look and reopen this issue if anything else needs to be tweaked. Thanks for filing the issue!
