### ISSUE TITLE
meditor: cannot add dandiset contributors

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#681]
in dandiset 105, the owner cannot add contributors. the dropdown for selecting person/organization is grayed out.

i looked at this in the codepen, where it seems to work fine, hence this may relate to how the UI is handling those additional buttons.

https://codepen.io/satra-the-reactor/pen/NWbKbrj?editors=1010

**Comment by AlmightyYakob** [comment]
This seems to be a general bug with selecting a schema type, not just contributors. I can investigate.

**Comment by AlmightyYakob** [comment]
Just did some investigating, can confirm this issue is not initially present in master, but shows up after doing a fresh `yarn install`. So this might be caused by a dependency change. I will keep investigating.
