### ISSUE TITLE
Fix icon design for going "back" to public dandisets

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#689]
_Originally posted by @satra in https://github.com/dandi/dandiarchive/issues/620#issuecomment-845481473_:
> `<--` is a weird icon for taking one back to public dandisets. 
> 
> i think that icon should be changed, but then there is duplication (we already have public dandisets on that page). so ideally it is back but takes you back to where you came from, which at the moment it doesn't. it takes you to public not the specific page of public dandisets you were looking at. 
> 
> overall it's a misleading UI i think.

**Comment by waxlamp** [comment]
What if we just got rid of the "back" icon altogether? The nav bar at the top of the app is the clearest way to move from place to place already.

**Comment by satra** [comment]
i'm fine with removing. 

the only thought process would be adding a previous dandiset and next dandiset link, but that may be non-trivial for a given dandiset without changing our API returns. so let's go with removing the link and title.
