### ISSUE TITLE
Investigate VJSF performance issues

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#694]
This is an investigative task to help understand the root cause of #662, #646 and #588.

**Comment by yarikoptic** [comment]
FWIW, I did profile in browser today but since know no JS wasn't able to identify ultimate reason

**Comment by yarikoptic** [comment]
If there is no related issue filled with vjsf, I would've also failed one there, ideally with some code to reproduce/demonstrate

**Comment by mvandenburgh** [comment]
We discussed this in person yesterday, but just to summarize here:

The slowdown appears to occur when VJSF renders an "array" field from a JSON schema. When an array field contains many elements that contain several nested child objects, the rendering slows down (an example is the "contributor" field on [this dandiset](https://gui.dandiarchive.org/#/dandiset/000004)). I'll file an issue with vjsf with that dandiset as an example.

**Comment by satra** [comment]
this should also improve with dandi schema  `0.4.0` which simplifies affiliation  (and i might reduced the contact person model as well to a simpler form in a future schema update).

**Comment by waxlamp** [comment]
This investigation is concluded, with a fix in #730 waiting on a schema upgrade.

**Comment by mvandenburgh** [comment]
The slowdown still persists even after applying the fix in #730 - reopening this issue.

**Comment by satra** [comment]
@mvandenburgh - i've updated this codepen to use dandiset 26  (https://codepen.io/satra-the-reactor/pen/NWbKbrj?editors=1010) perhaps you can use this as an example with vjsf issue to see what could be done to speed things up.

**Comment by satra** [comment]
that being said, other dandisets are quite a bit faster now as a result of the change. and even this dropped by about 10s

**Comment by mvandenburgh** [comment]
Keeping this open until the cause of https://gui-staging.dandiarchive.org/#/dandiset/000020 freezing is determined.

**Comment by waxlamp** [comment]
> Keeping this open until the cause of https://gui-staging.dandiarchive.org/#/dandiset/000020 freezing is determined.

@mvandenburgh is this still valid or can we close? Dandiset 20 doesn't freeze the meditor (but maybe the dandiset in question has moved or something), and we are now moving onto a bit of an alternative metadata editing scheme.

**Comment by mvandenburgh** [comment]
> @mvandenburgh is this still valid or can we close? Dandiset 20 doesn't freeze the meditor (but maybe the dandiset in question has moved or something), and we are now moving onto a bit of an alternative metadata editing scheme.

This can be closed (and indeed should have been a while ago) - the freezing issue has been fixed (relevant [dandiarchive](https://github.com/dandi/dandiarchive/issues/835) and [vjsf](https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/289) issues)
