### ISSUE TITLE
Services "registry"

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#70]
I started formalizing the idea in a wiki page: https://github.com/dandi/dandiarchive/wiki/WiP:-dump-of-thoughts-on-%22services-registry%22

**Comment by mgrauer** [comment]
This is returned by https://dandiarchive.org/server-info

**Comment by yarikoptic** [comment]
I was not talking about our services, but rather external services which could be used on each file.

**Comment by waxlamp** [comment]
@yarikoptic, I'm going to close this issue as non-actionable, but I think it would make sense for you to pull any specific feasible service integrations from the wiki page and file new issues for each of them. That will make the proposed work much easier to track.
