### ISSUE TITLE
ORCID logo being displayed for unidentified contributors

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#707]
![image](https://user-images.githubusercontent.com/844306/120340603-2f6d4180-c2c4-11eb-852b-0df97d4e2c16.png)

The above image would seem to imply that each of the three authors has an associated ORCID, however if you click on the symbol associated with "Inema, Ingrid", it takes you to orcid.org/unidentified. I think it would be better to omit the ORCID symbol for users that do not have an associated ORCID. This would be more in line with what the user expects and will help us identify where we are missing this data for specific contributors.

**Comment by satra** [comment]
thanks @bendichter for the issue. @sanuann - this should be an easy fix.
