### ISSUE TITLE
ror.org: just FOI on current listing of institutions in ROR.org

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#710]
we have ror.org identifiers for institutions now in the metadata schema, which is great.  Not sure where/how we are going to bring in yet assistance to users for the metadata entries to come from dictionaries etc, but decided to just dump some ror.org information here: integrations are listed on https://ror.org/integrations/ and public metadata dumps are available from https://figshare.com/collections/ROR_Data/4596503 .

Looking at the last version there is quite a good number of institutions there already!  Here is a tail from that public dump

```shell
$> jq '.[] | {id: .id, name: .name}' ror-data-2021-04-06.json | grep name | nl | tail
100458	  "name": "International Innovative University"
100459	  "name": "UNESCO Institute for Statistics"
100460	  "name": "Sociedade Portuguesa de Ciências da Educação"
100461	  "name": "Russian Society of Sociologists"
100462	  "name": "United Nations Institute for Disarmament Research"
100463	  "name": "Center for the National Interest"
100464	  "name": "Tiny Beam Fund"
100465	  "name": "TMG Research"
100466	  "name": "UNICEF East Asia and Pacific Regional Office"
100467	  "name": "The White House"
```
so I guess for any completion/validation we might want to have some kind of a service to not burden web UI etc, which could be queried to e.g. resolve the institution name to ror.org identifier etc.

**Comment by waxlamp** [comment]
Could you clarify the problem and/or action items here?

**Comment by yarikoptic** [comment]
Well, sorry if I polluted the issues, I will close -- a "note" was made so could be searched up etc ;-)

FOI == "For Our Information".   The particular problem here is that meditor UI has fields for the organization name and  requests ror.org identifier for it: it requires user to go to the website/search/copy+paste.  The problem per se is not specific to ror.org but for any metadata entry eventually where value to be filled out by entry in another field (e.g. ror.org identifier could be filled out by searching for the name of the organization, and vise versa -- entry of ror.org identifier could fill out the name). The use case is not specific to ror.org - we have ORCID and others like that.
