### ISSUE TITLE
minor: bring "Cite as" to be close with "

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#713]
ref: https://github.com/dandi/dandiarchive/pull/684#issuecomment-847131661

ATM "Cite as" is positioned somewhere in the middleish between the lonely "Get shareable link" on the left and a group of actions like "Download", etc on the right:

![image](https://user-images.githubusercontent.com/39889/120532731-fd380e80-c3ad-11eb-9ea4-a0ab2302df8b.png)

I think it would be nicer if "Cite as" followed "Get shareable link" with the same spacing as between those actions in the group on the right.  Would IMHO make UI a bit more consistent and thus better UX.

@sanuann could you do this magic?

**Comment by waxlamp** [comment]
This has been mooted by the DLP redesign.
