### ISSUE TITLE
Make click on version to not copy to clipboard but go to github

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#726]
Reviewing #722 an idea came to mind

https://github.com/dandi/dandiarchive/tree/0.1.0-421-g609c077 works just fine ;)  so URL could be easily constructed from the exact commit or current `git describe` which is sweet.

copy pasting could be done via regular select/copy, but getting to github requires "knowledge"

**Comment by waxlamp** [comment]
I had the same thought, in a way. I clicked on the version string expecting to be taken to GitHub and felt a sense of disappointment that it only copied the URL to the clipboard.

I'll do this as a followup to #722.

**Comment by yarikoptic** [comment]
Great (when) users think alike! ;-)
