### ISSUE TITLE
Make "Modified" (or "Identifier") to be the default sorting

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#734]
ATM default sorting is by name, which might cause people to "abuse" that to have their dataset appear first.  Overall also sorting by Name is not as useful as by Modified or Identifier.  I think making web ui sort by Modified (or Identifier) would be more "fair" and informative IMHO.

**Comment by waxlamp** [comment]
I think Modified is better, so that newer stuff is at the top. 30% more dynamic™️!

Opinions?

**Comment by satra** [comment]
+1 for Modified being default (we should eventually get to the toggle mode of dandisets with and without any data :) )
