### ISSUE TITLE
Create dandiset landing page

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#74]
Every dandiset should provide a landing page with a summary of the metadata.

**Comment by satra** [comment]
to support this landing page, we should encode this: https://docs.google.com/document/d/1WvRr9J2Ums0-CQIcdUeFZakE2RPeagRnexUBFDiiV7w/edit?ts=5defc58b

into a yml/json file and provide a ui for editing via the gui. @mgrauer - is this something that kitware could implement?

**Comment by mgrauer** [comment]
@satra Yes, for sure.
