### ISSUE TITLE
Blank screen if OAuth token is invalid

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandiarchive#740]
The `/api/users/me` endpoint responds with a `401 Unauthorized` response if the client's OAuth `access_token` is invalid. The client does not properly catch this error, and instead just shows a blank white screen; right now the only way to get the UI to appear again is to manually clear the cookie from the browser.

**Comment by waxlamp** [comment]
What's the easiest way to reproduce this?

**Comment by mvandenburgh** [comment]
I think the easiest way is to just manually edit the cookie to invalidate it.

- Log in to dandiarchive w/ github oauth
- Open chrome dev tools -> Application tab -> Local Storage tab
- Invalidate the `access_token` field of the `oauth-token-xxxxx` entry by modifying it (not deleting it), then refresh

**Comment by yarikoptic** [comment]
loosely related to https://github.com/dandi/dandi-api/issues/331 -- as dandiarchive.org web-ui causes disabled users to end up in that api.dandiarchive.org page instead of IMHO just reporting in its web ui "Waiting approval" or "User is not enabled" or something alike.
