### ISSUE TITLE
VJSF 2.0.2 breaks "basicModel" forms in Meditor

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandiarchive#743]
The VJSF upgrade in #730 that fixes the freezing problems seems to introduce a new bug in the Meditor. Any edits to the "basicModel" forms (i.e. any VJSF form that is present on the main Meditor screen like `Dandiset title`, `Description`, `Study Target`, `License`, etc.) are not persisted after clicking the save button. "complexForms" still work.

GIF demo of the bug, note that changes are saved when the staging GUI is used (with VJSF v1), but not when the Netlify branch preview for #730 is used (with VJSF v2):
![meditor bug](https://user-images.githubusercontent.com/37340715/122241342-79dbea00-ce90-11eb-9e07-aa3d9dc883e0.gif)\

**Comment by waxlamp** [comment]
This is a critical bug. My intuition is there's some small thing we're missing so hopefully it's easy to fix, but please make this your priority in the short term, @mvandenburgh.
