### ISSUE TITLE
cite as url for dandiset is wrong

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#752]
I think I saw some recent issue or PR by @satra about that, can't find, feel welcome to close if it is a duplicate

https://gui-staging.dandiarchive.org/#/dandiset/000003/draft  for Cite as says

3 (2021). (Version draft) [Data set]. DANDI archive. https://dandiarchive.org/000003/draft

but the url is missing `/dandiset` : as in https://dandiarchive.org/dandiset/000003/draft

**Comment by waxlamp** [comment]
Well! This seems to have been fixed, even though I didn't fix it!

@yarikoptic, I'll close this as fixed, but if you see continued problems here please do re-open.
