### ISSUE TITLE
switch modified's sort direction

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#758]
i think the default modified direction is from oldest to newest. we should switch it to the other mode :)

**Comment by yarikoptic** [comment]
FWIW, Doh, I have missed that, indeed
![Screenshot_20210622-205620](https://user-images.githubusercontent.com/39889/123018350-60f59c00-d39c-11eb-9727-e41e67d731a8.png)

**Comment by mvandenburgh** [comment]
Oops, fixed that.
