### ISSUE TITLE
Change direction of arrow icon for sorting by "modified"

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandiarchive#759]
https://github.com/dandi/dandi-api/pull/355#issuecomment-866448082

The sorting arrow icon should point up when sorting by "modified" with most recently modified first, and down when sorting by "modified" with least recently modified first (right now the opposite is happening).

**Comment by mvandenburgh** [comment]
This should be fixed now. Apologies all for the PR notification spamming :sweat:

**Comment by yarikoptic** [comment]
Thank you @mvandenburgh --  Looks proper on the site! No problem with PR notifications whatsoever -- keep them coming!
