### ISSUE TITLE
Eliminate "authorize" screen during login

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#761]
During login, first the user is redirected to GitHub to provide credentials there, then they are redirected to a DANDI OAuth authorization screen, and finally they are redirected back to the app.

The second screen is redundant from the user's point of view, and in fact can be confusing. We should eliminate that step and consider the provision of credentials to GitHub to be authorization to use those credentials in the Dandi Archive.

If I've misunderstood the purpose of each of those screens, please correct me in the comments.

**Comment by yarikoptic** [comment]
FWIW: for me (as started to happen in webshots) that screen was appearing sporadically recently, so I had added a conditional handling in the https://github.com/dandi/dandi-api-webshots/blob/master/tools/make_webshots.py#L94 and mentally attributed to some github logic to re-ensure periodically user's decision.

**Comment by djarecka** [comment]
is this still an issue? I don't see it during my login

**Comment by mvandenburgh** [comment]
Yes has been fixed for some time, it should have been closed by https://github.com/dandi/dandi-api/pull/440. I'll close it now.
