### ISSUE TITLE
turn assetsSummary into a proper Summary display 

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#765]
we are now computing assetsSummary (example here: https://gui-staging.dandiarchive.org/#/dandiset/000002). however, as you can see the display does not render this properly. 

i think many things could become like we display keywords. you could title the section as `Dandiset summary` and have sub sections.

also `schemaKey` should not appear in the landing page anywhere.

**Comment by waxlamp** [comment]
@jtomeck, this could eventually be part of the DLP redesign process.

**Comment by jtomeck** [comment]
> @jtomeck, this could eventually be part of the DLP redesign process.

Is there a reason it would need to stay in a non-human-readable array format, or is there value to tidying that up?

**Comment by satra** [comment]
there is no reason for this to stay in a non-human-readable format. the information in this key can also be used for the files + size component in the sidebar. 

ps. i think we are moving to a state where there are versions of dandisets and anything about the DLP besides versions of a dandiset would be in the metadata of that version. once we hit publish the DLP would have to respect the version moving forward.

**Comment by yarikoptic** [comment]
Probably would not be fully reusable, but as the top level https://gui-staging.dandiarchive.org/#/ summary is just summary over the assetSummaries, consistency of the display of the aggregated assetSummary on the main page with the display per dandiset might contribute to better UX, so might be something to keep in mind.

**Comment by satra** [comment]
@mvandenburgh - just assigned this to you, in case you have some bandwidth and since sanu may be off for a few days. any hack to present it will likely be better than how it looks right now :)

**Comment by sanuann** [comment]
@mvandenburgh are you working on this?

**Comment by satra** [comment]
@sanuann - i was going to work on this, but got sidetracked with all the asset updates. please go ahead and work on this.
