### ISSUE TITLE
Allow for thumbnails to be associated to dandisets

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#770]

**Comment by sanuann** [comment]
@waxlamp can you please provide an example (or some detail) of what this is about?

**Comment by waxlamp** [comment]
I believe this has to do with allowing for an image to optionally be specified to go with a dandiset. Then in the public dandisets view, for example, that image would be shown alongside its dandiset entry.

@satra, @yarik: can you confirm my memory of this?

**Comment by satra** [comment]
to truly allow this the cli has to allow pushing other types of files to dandi without the use of the devel options. for example we could allow an infographic.png, but we need to determine:
- extension supported (only png, or png + svg)
- fixed name of file 
- decide whether only at root of dataset
- do we add a metadata field for this thumbnail(??) or do we allow for a bytestream in the metadata itself or neither

**Comment by yarikoptic** [comment]
- client could allow upload of images
- metadata/meditor allow to associate (found) image assets as thumbnails

**Comment by djarecka** [comment]
is this is just a duplication of #625?
I thought that the image would be loaded via website without being a part of dandiset...

**Comment by waxlamp** [comment]
Yes, this seems to be a dupe of 625. I'll continue discussion there.
