### ISSUE TITLE
Change "about" link to point to dandiarchive website top-level

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#771]
The about link currently points to https://dandiarchive.org/about, which in turn redirects to https://www.dandiarchive.org/.

Is this intended behavior (@satra)? If not, we should eliminate the redirect and point the about link directly to https://www.dandiarchive.org/.

**Comment by satra** [comment]
i think this could go straight. the only reason that's there is that we could then change the about link universally.
