### ISSUE TITLE
publish button reporting no files

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#781]
![image](https://user-images.githubusercontent.com/844306/124327837-87fb5d00-db56-11eb-8a8c-5e67f5c83e41.png)

For dandiset 8, the UI is reporting that the dandiset contains 0 bytes of data, but that is clearly not the case.

**Comment by waxlamp** [comment]
Hey @bendichter, sorry we never got back to you about this.

Can you check again and see if you're still getting that same error? Things have advanced since you filed this and it's possible that the specific problem has been fixed.

**Comment by bendichter** [comment]
Thanks for following up, @waxlamp, I'm pretty sure this has been fixed now.
