### ISSUE TITLE
Sort out initial data organization

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#8]
I'm trying to figure out how to organize the data hierarchy in Girder for SfN. We can change it after, I expect it will take some evolution regardless.

We had planned to feature data from Buzsaki, Chuchland, and Svoboda labs, so I was at first thinking to have a Girder collection per lab. @bendichter told me `LastNameOfFirstAuthor|Year is the standard tag`, so Najafi2019 or Najafi2019b for the second paper by the same author in a year.

It still might make sense to organize data by lab, that way labs could upload data that isn't tied to a publication (whether they will is another story), and then have the paper underneath the lab. The hierarchy is used for default browsing and for permissions. We can also synthesize any hierarchy we want based on metadata.

For the sake of moving forward and the good over the perfect, I recommend to create a single collection `SfN` with folders `Buzsaki`, `Churchland`, `Svoboda`, and subfolders named by papers under those, e.g. `SfN/Churchland/Najafi2019/NWB_file_1`. The lab will be included in the metadata of the Item, and the metadata can be used to drive arbitrary search.

I expect people will want to argue about this at SfN, which is good, it will generate useful feedback about what works and what is desired.

**Comment by satra** [comment]
just to add to this. i think we will have some notion of view that we will call a `dataset`. such a `dataset` may be one that is used for a paper, an aggregation of pieces of other datasets and so. 

perhaps a collection at this point can simply be a collection of papers and we can have folders within it

```
collection -> publications
  folders (are datasets): Najafi2019 (metadata: {'groups/labs': [Churchland], 'authors': [...], 'doi': ...})
     file: NWB_file1 (metadata: {'species': ..., ...}) # extracted from nwb file
```

this will also allow us to have other collections that we may call `projects`

folders can then be potentially mapped to a layout if we decide on one.

**Comment by mgrauer** [comment]
What specific queries do we want to support for the SfN demo? I need to know this in advance to be sure we are structuring the hierarchy and metadata appropriately to support the queries.

**Comment by satra** [comment]
> What specific queries do we want to support for the SfN demo?

that depends on what metadata we are extracting from the files.

perhaps @bendichter can make up a few queries. with a few datasets, queries are bound to be limited. so just having a nice way to display properties would be good.

**Comment by bendichter** [comment]
Here's an example of meta-data from the current extractor:

```
{'experiment_description': None,
 'experimenter': ('Farzaneh Najafi',),
 'identifier': '150817_001_ch2-PnevPanResults-170808-190057',
 'institution': 'Cold Spring Harbor Laboratory',
 'keywords': None,
 'lab': None,
 'related_publications': ('https://doi.org/10.1101/354340',),
 'session_description': '150817_001_ch2-PnevPanResults-170808-190057',
 'session_id': '170808190057',
 'session_start_time': datetime.datetime(2015, 8, 17, 1, 0, tzinfo=tzoffset(None, -14400)),
 'subject_id': 'mouse1_fni16',
 'number_of_electrodes': 0,
 'number_of_units': 0}
```

Ideally I'd want to be able to query all of these. In order of importance IMO:

```
related_publications (is in)
keywords (is in)lab (==)
experimenter (is in)
institution (==)
subject_id (==)
number_of_electrodes (>,<)
number_of_units (>,<)
session_start_time (>,<)
session_description (strmatch)
experiment_description (strmatch)
identifier (==)
session_id (==)
```

**Comment by mgrauer** [comment]
@bendichter 

Can you give an example of how'd you want to use the `related_publications (is in)` for search?

Would this be something like "find me any nwb files that are used in a given publication DOI" or perhaps a list of DOIs?

**Comment by yarikoptic** [comment]
> For the sake of moving forward and the good over the perfect, I recommend to create a single collection `SfN` with folders `Buzsaki`, `Churchland`, `Svoboda`, and subfolders named by papers under those, e.g. `SfN/Churchland/Najafi2019/NWB_file_1`. The lab will be included in the metadata of the Item, and the metadata can be used to drive arbitrary search.

I would support such a layout for the sake of the SfN demo, so to be `SfN2019` collection (to be more specific), `<PI>`, and a `<dataset-name>`.  In the case of Najafi2019 it would indeed have a direct correspondence to a publication, but in general it would not necessarily be the case.  As for the directories/files layout within dataset -- if we decide to allow other file types (e.g. ipython notebooks), then we might better just reflect original hierarchy for that dataset and upload at least a few notebooks as well.  As discussed, we could get 'Binder' button to jump to binder instance with that notebook happen someone likes to try it.

**Comment by bendichter** [comment]
@mgrauer `related_publications` returns a list of DOIs. I'd want to be able to provide a DOI and search across NWB files and get a view of all of them that have that publication in their `related_publications` list.

**Comment by mgrauer** [comment]
We had some discussion about this issue on our DANDI call yesterday, and it remains an open issue that we need to figure out.

It seems at this point the best sense we have is that we want to support a "dataset" (a set of different pieces of data, in the abstract, not in the NWB sense) as being a collection of data tied to a lab or tied to a publication. The individual pieces in the datasets can live in multiple datasets (e.g. in multiple labs or multiple publications or both).

**Comment by mgrauer** [comment]
Initial organization for beta launch, as of #120 is the following:

 - A public collection named `drafts`
 - Dandisets will be new folders within the `drafts` collection
 - Dandisets will have a metadata key of `dandiset`, and that nested metadata document will have:
   - key `identifier`, which is a six digit zero padded integer
   - key `name`
   - key `description`
