### ISSUE TITLE
create staging dandiset endpoint

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#80]
This endpoint API is subject to change 

* find or create the staging collection, which should be publicly readable
 * create a folder in staging collection
 * add a folder metadata of `dandiset_id:$(uuid)`
 * return the folder document

**Comment by satra** [comment]
@mgrauer - do you want to do this as an endpoint or do it in the cli for now? we could abstract away cli functionality to an api later on.

**Comment by mgrauer** [comment]
Yes agreed, we can do it in the CLI just as easily.

**Comment by mgrauer** [comment]
We have decide to change the dandiset ID to be a 6 digit zero padded incrementing counter. E.g., the first ever dandiset will get id `000001` and the second will be `000002`. 

Given this, and also in light of supporting #88, it makes sense to do this issue as an endpoint again, and not in the client, as we'll need to track the dandiset counter centrally, and perform the searches for a folder by its `dandiset_id`.

A suggested idea for tracking the dandiset counter is for the dandi plugin to add a new girder setting that is something like `max_current_dandiset_id`. As we have decided there will only ever be 999,999 dandisets, we will need protection in the endpoint from going above this number, at least to issue an exception.
