### ISSUE TITLE
improve size formatting and sorting for file/folder view

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#802]
would be nice to not have the wrap around for size.

![image](https://user-images.githubusercontent.com/184063/126344845-d9b242d2-8923-4e0a-93e8-7c5d89d87f29.png)

**Comment by satra** [comment]
@mvandenburgh - did this also address the sorting issue?

**Comment by mvandenburgh** [comment]
> @mvandenburgh - did this also address the sorting issue?

Oh I didn't see that - no, it only addresses the size formatting. Are you referring to the files/folders not being in alphabetical order?

**Comment by satra** [comment]
> Are you referring to the files/folders not being in alphabetical order?

yes

**Comment by mvandenburgh** [comment]
The sorting issue has been addressed in #806.
