### ISSUE TITLE
Add a context menu with options for "opening" an asset (or dandiset, folder?) on external services

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#821]
original idea: https://github.com/dandi/dandiarchive/wiki/WiP:-dump-of-thoughts-on-%22services-registry%22

An [issue](https://github.com/MetaCell/nwb-explorer/issues/244) with metacell nwb viewer resolved , so we have no roadblock to start working on this feature to gain initial integrations. And bisweb might be just a CORR tune up away: https://github.com/dandi/dandi-infrastructure/pull/88 .

Similar implementation [is ongoing](https://github.com/datalad/datalad-deprecated/pull/27) for https://datasets.datalad.org and could be previewed in action for a sample dandiset at http://datasets-dev.datalad.org/?dir=/dandi/dandisets/000027/sub-RAT123 (hover over file to see ⠇)

Instead (or in addition) to a context menu it could be an action to take upon a click on an asset (https://github.com/dandi/dandiarchive/issues/780) but [I still think](https://github.com/dandi/dandiarchive/issues/780#issuecomment-885061015) we better reserve that for a "view" of some kind without resorting to external services.

also ref: https://github.com/dandi/dandi-infrastructure/issues/10 as a generic metacell deployment issue (not necessarily just linking out)

**Comment by waxlamp** [comment]
An "open with" menu that has a list of services we have "registered" in the client is a good idea.
