### ISSUE TITLE
"Last updated" field shows current datetime

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#825]
![image](https://user-images.githubusercontent.com/844306/128079295-1063fd08-c493-4999-ade9-4614a56edd58.png)

The "Last updated" field shows the current datetime. When I refresh the page, the last updated field changes to the now current datetime, even though we are not making any changes to the dataset.

**Comment by yarikoptic** [comment]
> even though we are not making any changes to the dataset.

that's the hope! ;)

**Comment by yarikoptic** [comment]
if datestamps for overall dandiset (not version) record, then it seems we are ok:
```
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000053/" -H "accept: application/json" | jq . | grep -i -e modified -e created
  "created": "2020-12-22T18:29:52.301000Z",
  "modified": "2021-04-27T14:33:20.572614Z",
    "created": "2020-12-22T18:29:52.301000Z",
    "modified": "2021-07-08T12:27:45.658893Z",
      "created": "2020-12-22T18:29:52.301000Z",
      "modified": "2021-04-27T14:33:20.572614Z",
```

`/versions` endpoint also doesn't give any "current date":
```
$> curl --silent -X GET "https://api.dandiarchive.org/api/dandisets/000053/versions/" -H "accept: application/json" | jq . | grep -i -e modified -e created
      "created": "2020-12-22T18:29:52.301000Z",
      "modified": "2021-07-08T12:27:45.658893Z",
        "created": "2020-12-22T18:29:52.301000Z",
        "modified": "2021-04-27T14:33:20.572614Z",
```
so I guess it is indeed some UI defect, and otherwise dandiset metadata is "safe" (not some kind of an artifact triggering an update of datestamp upon some GET operation)

**Comment by waxlamp** [comment]
Wow, nice find!

Indeed, the internal application state seems to be reporting correct "last modified" times for dandisets, and somehow the current time is nonetheless being injected into the frontend. Looking into it.
