### ISSUE TITLE
review dandi endpoints

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#83]
right now we have:

dandiarchive.org
gui.dandiarchive.org
hub.dandiarchive.org
girder.dandiarchive.org

i think from a user perspective it would be good if dandiarchive.org directly pointed to the content on gui.dandiarchive.org (this would have landing pages, search, etc.,.) and an about that can point to the content currently on dandiarchive.org.

so dandisets would look like:

`dandiarchive.org` --> public dashboard
`dandiarchive.org/dandiset/{id}` --> landing page (e.g. https://openneuro.org/datasets/ds002547/versions/1.0.0)
`dandiarchive.org/asset/{id}` --> landing page for an asset

we should decide if there is a namespace id, which links to the latest version vs a version id.

all of the above should be decided soon.

(and more generally, if we do this, should this become a RESTful API with PUT/DELETE for staged datasets - we don't have to implement this for March 1).

**Comment by yarikoptic** [comment]
> i think from a user perspective it would be good if dandiarchive.org directly pointed to the content on gui.dandiarchive.org (this would have landing pages, search, etc.,.) and an about that can point to the content currently on dandiarchive.org.

I would vote for that too.  We then could move project description page to e.g. `project.dandiarchive.org` or `platform.dandiarchive.org` where we would provide all info on the project and how others could get their individual deployments (in the future).  And that page referenced from the footer of the dandiarchive.org

**Comment by mgrauer** [comment]
We have accomplished this with the redirector.
