### ISSUE TITLE
Paginate the file browser view

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#844]
This results from a discussion on a different issue: https://github.com/dandi/dandiarchive/issues/813#issuecomment-899800641.

The basic idea is, if you have a dandiset with many (say, 6000) assets, the browser view should not try to show all of them in one page.

**Comment by yarikoptic** [comment]
FWIW, https://github.com/dandi/dandi-api/pull/579 (pagination support) was merged so the road is open ;-)
