### ISSUE TITLE
dataset_id

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#85]
Namespace ID

Numeric
e.g. https://openneuro.org/datasets/ds002547/versions/1.0.0

Unique - non numeric IDs
e.g. https://osf.io/f45gu/

Same question for version id
1. Semantic versioning (of published datasets)
2. uuid/checksum versioning of staged datasets

a namespace id would always point to the latest version of a dataset
a version id should be available to go to a specific version of the dataset.

see also #83

**Comment by yarikoptic** [comment]
Since we will be in control of assigning IDs and publishing versions, Thinking of humans (and placing possible technical difficulties aside) I would have
- had both IDs human readable , eg `dandi00001` for namespace id
- version id contain namespace id, eg `dandi00001@1.0.0`

**Comment by mgrauer** [comment]
As it is currently implemented, from #120, a dandiset gets a metadata field of `identifier` with a value that is a six digit zero padded incrementing integer starting at 1. This will not be enough to distinguish dandisets from different instances of dandi.

**Comment by satra** [comment]
if we think of the url as `dandi:000001`, then presumably other future instances of dandi would have a different prefix.

**Comment by yarikoptic** [comment]
we settled on e.g. `000003` with identifiers.org prefix `dandi:` so https://identifiers.org/resolve?query=dandi:000003 seems to work,with correct url redirecting to the dandiset landing page. I guess versions etc we could discuss in a dedicated new issue whenever that one comes about (feel free to reopen if disagree)

**Comment by satra** [comment]
just a note that you should also be able to do: 

```
https://identifiers.org/dandi:000003
https://identifiers.org/dandi:000003/0.20200415.1034
```

**Comment by yarikoptic** [comment]
cool -- what is the `0.20200415.1034` exactly since we have no versions yet?

**Comment by satra** [comment]
currently that version id gets dropped by the redirector. however that version was simply:

`0.YYYYMMDD.HHMM` and the identifiers prefix supports versions of the form `/d+./d+./d+`
