### ISSUE TITLE
do we allow custom licenses?

### ISSUE THREAD

**Issue by bendichter** [dandi/dandiarchive#858]
The Allen Institute has their own custom license. This is referred to, e.g. in the description of [dandiset 39](https://dandiarchive.org/dandiset/000039/draft):

> Data are subject to Allen Institute Terms of Use policy, available at: http://www.alleninstitute.org/legal/terms-use/

Meanwhile, this dataset does not pass validation for publication because there is no selected license in the metadata editor. Clearly, none of those options would be perfect for this dataset, because they have their own license. I don't think we'd get much traction trying to convince the Allen Institute that they should pick a standard license instead of using their own. What is the best solution here?

**Comment by satra** [comment]
we presently do not allow custom licenses. we can always ask any dandiset to pick a license that's closest to the intent.

**Comment by yarikoptic** [comment]
eh, and the largest aspect of that ad-hoc license is the "non-commercial".  Stepping into those murky waters (of what is commercial what not) leads them to *enhance* with other vague permissions such as "you may, without obtaining further license or permission, publish a limited set of the Content in a scholarly journal, textbook or other professional, academic or journalistic publication (with appropriate citation) and still be compliant with these Terms."

Not yet sure if their "Freedom to Innovate and Rights to Improvements" section can find direct analogs among CC licenses. The copyleft "-SA" or may be some aspects of Apache 2.0 sounds similar to that, but not sure if there is a clear direct analog to this ad-hoc compilation of terms.

**Comment by yarikoptic** [comment]
not sure even if you @bendichter have permission to do anything with this data, since "or use of the Content to perform a commercial service for a third party" heh heh

**Comment by waxlamp** [comment]
> we presently do not allow custom licenses. we can always ask any dandiset to pick a license that's closest to the intent.

Licenses are legal instruments, with actual force in the real world (unless and until some higher legal power shifts the flow of things in a particular case). I don't think it's viable to ask data owners to pick a "closest" license--that defeats the purpose of licensing for open source / creative commons usage.

**Comment by bendichter** [comment]
@yarikoptic yes, thanks for alerting me to this. I have chatted with Allen people about this license issue. I think having a private company help them make data accessible to researchers is sufficiently within the spirit of the license that I'm not concerned. That verbiage is really for companies like pharmaceuticals that might mine this data for drug development.

**Comment by waxlamp** [comment]
Where did we land on this question?

From the discussion it sounds like the answer is "no, you must select a CC license", but I am not clear on where that leaves Allen Institute data.

**Comment by satra** [comment]
we need to fix their published dandiset records (they gave us permission), but they changed all their licenses to CC-BY

**Comment by waxlamp** [comment]
So the answer to the question in this issue is "no", and we have a path forward for AIBS data. Closing this issue; remaining tasking will be handled in #1004.
