### ISSUE TITLE
remove the empty space "fill" to bring up the footer

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#86]
https://github.com/dandi/dandiarchive/pull/72 added a footer.  I went to https://gui.dandiarchive.org/#/ and failed to see it.  Then I realized that I had to scroll page down to get to it.  IMHO there is no use for the empty space before footer, and it could just follow the navigation panel.

**Comment by mgrauer** [comment]
Fixed by GUI refactor.
