### ISSUE TITLE
Make meditor "ok" (store) vs "cancel" (disregard) changes action consistent across modal subwindows

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#860]
<details>
<summary>on top level we have "<-" (cancel) and "floppy" (ok/save) icons on **top** of the display, with click on "<-" warning about possibly lost changes which is awesome:
</summary> 

![image](https://user-images.githubusercontent.com/39889/131572575-b160d3dc-a0ff-4282-819b-899c5ef5aaf8.png)

</details>

<details>
<summary>one level down, in e.g "Dandiset contributors" which brings up "list of things editing" there is a "+" and an explicit "pen" (edit) for existing item which brings up another modal to actually edit, and which then has "Cancel", "Ok" on the **bottom** of the display (might need to scroll) </summary> 

![image](https://user-images.githubusercontent.com/39889/131572837-a049cb2a-7868-424d-b71e-27dafaed32ad.png)

</details>

<details>
<summary>upon Ok (saving) edits in prior one, I end up in that "Dandiset contributors" which has no buttons whatsoever and requires clicking somewhere outside of that modal window to end up on the top view with icons on the top</summary> 

![image](https://user-images.githubusercontent.com/39889/131573019-bce1cb51-8e53-413c-89be-fe42d7538f2b.png)

</details>

IMHO consistency should be improved.  Would it be easy for all of them to mimic what we have on the top level , i.e

- all have action icons on top left corner (would also be more consistent with DLP which has action icons on top)
- all have the same back arrow "<-" to signal "go back"/cancel
- for the 3rd level modal to edit an item, have the same floppy just of Orange color (which would nicely align with how top level floppy turns Orange when edits happen)

?

**Comment by waxlamp** [comment]
We can look into this, but the reason for the nice features at the top level, and the lack of them down below is that the down belows are all rendered by VJSF directly. There is probably a way to influence how the save/cancel actions are rendered, but I don't know how much control VJSF gives over to the client here.

@mvandenburgh is the right person to investigate this, but I will consider this to be low priority unless there's some specific demand for improved UX here.

**Comment by mvandenburgh** [comment]
Yeah VJSF does offer some options for customization, I just have to spend time looking into it since iirc the docs for it are pretty minimal. Somewhat related to https://github.com/dandi/dandiarchive/issues/692

**Comment by waxlamp** [comment]
Because of the DLP redesign, and our heavier use of advanced VJSF features therein, I'm going to close this as `wontfix`.
