### ISSUE TITLE
Ownership panel is confusing

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#863]
The ownership panel on a dandiset just says "Ownership", then presents a search box and several chips with usernames. It's not self-evident what to do with this, nor how to effect changes.

**Comment by djarecka** [comment]
it's indeed confusing, I'm also not sure what is the meaning of "ownership" and how it differs from "contact person"

**Comment by waxlamp** [comment]
The owners of a dandiset are the users who are able to make changes to it, publish it, grant other people ownership, etc.

@jtomeck, I believe we need an update on the design for this element.

**Comment by jtomeck** [comment]
I pinged Mike about this in Figma, but wanted to post these here as well.

![DLP - Initial stateDANDI](https://user-images.githubusercontent.com/1560779/136595562-930b0e5a-5cd4-4760-a1c7-712a907007fe.jpg)

![DLP - OwnershipDANDI](https://user-images.githubusercontent.com/1560779/136595614-b468abcb-41b2-488f-8b67-b45cf6897854.jpg)

![DLP - Ownership - Filter usersDANDI](https://user-images.githubusercontent.com/1560779/136595633-6cd78ded-f7e0-47d5-be80-1d4349800a43.jpg)

![DLP - Ownership - Users AddedDANDI](https://user-images.githubusercontent.com/1560779/136595648-f3071a9f-2092-4423-bf88-7385c1b08cd1.jpg)

**Comment by waxlamp** [comment]
This looks great, thank you @jtomeck!

@mvandenburgh, are you good to implement this design?

@satra, @yarikoptic: any objections to this design update?

**Comment by jtomeck** [comment]
One thing I did forget to add to the design is the "primary contact" icon on the ownership panel itself (first screen).
