### ISSUE TITLE
Dropdowns in DLP should not behave like material design buttons

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#865]
The "download", "shareable link", and "cite as" dropdowns behave like they are regular buttons with attached popovers. Specifically, they show the material design "bloop" effect when clicking on them, and there's a slight delay before the menu portion appears.

If this is standard vuetify behavior for dropdowns, then this can probably be closed. But it would be better to not have the buttons boop or bloop, and show the menu immediately--then it would feel like a real dropdown.

**Comment by djarecka** [comment]
@waxlamp - I've changed slightly the button: removing "down arrows", but I'm not sure about "bloop"...
