### ISSUE TITLE
Too much of the side panel is invisible without scrolling

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#867]
The DLP redesign includes several important sets of data in the righthand side panel, including dandiset actions, ownership, validation status, and version history. But much of this stuff (on my screen, at least) is not visible without scrolling.

**Comment by mvandenburgh** [comment]
Do you mean scrolling horizontally or vertically? (I'm guessing horizontally, but just want to clarify since I don't have this issue on my screen).

**Comment by waxlamp** [comment]
I meant vertically. We might need to compare each others' screens to fully grok what's going on. We can do that at Tuesday's meeting.

**Comment by waxlamp** [comment]
I kind of don't think this is a problem now (if it ever was). I'll close, but re-open if you disagree.
