### ISSUE TITLE
what do URLs support, how to download

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#87]
There are a few things that i don't know who will implement regarding addressability of datasets and assets and their downloads. 

q1. where will these URLs be resolved from:

```
dandiarchive.org/ds000001/v0.0.1
dandiarchive.org/dandiset/{id} --> should this exist?
dandiarchive.org/asset/{id}
```

q2. what will these URLs support content negotiation (e.g., HTML vs jsonld)

q3. will downloads be a separate URL? how will downloads differ between a dataset and an asset? or should downloads essentially be a redirect to the s3 bucket object.

it doesn't make sense for me to create a tar archive for downloading a dandiset. i would prefer some other transport layer.

**Comment by satra** [comment]
Should there be a separate api route from the above URLs?

```
api.dandiarchive.org/dandiset/{id}
api.dandiarchive.org/asset/{id}
```

and in q1 above, what resolves: `/ds000001/v0.0.1 --> {id}`

**Comment by mgrauer** [comment]
>it doesn't make sense for me to create a tar archive for downloading a dandiset. i would prefer some other transport layer.

This might require infrastructure to do on the server side, e.g. construct the dandiset for downloading, and then likely some async notification of the user that their data is ready. Are people likely to want a full dandiset in its entirety for download, or only subsets of both the dandiset and assets?

We had talked before about having the client do this piece, which would eliminate the need for server side infrastructure. Then we'd only have to support downloads of individual pieces (dandiset metadata, assets or subsets of assets) through API endpoints that the client would call.

**Comment by satra** [comment]
> We had talked before about having the client do this piece, which would eliminate the need for server side infrastructure. Then we'd only have to support downloads of individual pieces (dandiset metadata, assets or subsets of assets) through API endpoints that the client would call.

that would be my preference. that the transport layer we enable doesn't require downloading the whole dataset. but this requires implement a few things for march 1.

**Comment by mgrauer** [comment]
I believe this is implemented on the publish api and supported by the CLI. The GUI also describes the CLI commands to download a full dataset.
