### ISSUE TITLE
Consider moving file count and size to DLP header

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandiarchive#873]
The icons for number of assets and total dandiset size are currently next to the search bar above the DLP header. This seems like an odd place to put this info. Can we move it to the header itself, or somewhere else?

attn: @jtomeck, @satra, @yarikoptic

**Comment by satra** [comment]
yes, anything that's important to the scientist (and size of dataset seems to be one of those things), should be at the top of the DLP near the dandiset title. this will be the kind of thing that we flexibly alter.

**Comment by djarecka** [comment]
either I don't understand the issue or it was already fixed
