### ISSUE TITLE
Get dandiset endpoint

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#88]
Create an API endpoint which takes a dandiset ID, and some optional parameters. 
It returns (type: a girder folder document):
* The latest published dandiset, if no options were passed.
* If the option for a version was specified, return that version.
* The above option could also include the staging version.

**Comment by mgrauer** [comment]
For the first implementation I think we should just deal with the staging side of things, because we haven't defined how to version the published dandisets (in terms of their server side implementation).
