### ISSUE TITLE
Add Share (icon) with Twitter (and later other) social media

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#880]
so anyone (not only owner) visiting the DLP could share in his social circles information about cool dataset they want to promote.

An example to follow would be https://www.biorxiv.org/content/10.1101/2021.09.13.459835v1 which has Share with various social media. 

Could go alongside with "Cite as".

Related -- having a bot to tweet https://github.com/dandi/dandi-api/issues/512

**Comment by waxlamp** [comment]
This would be a great one for @djarecka or @sanuann to tackle.

**Comment by sanuann** [comment]
Should this be a new button beside "Cite as"? asking because we already have a "get shareable link". Can I modify that to just "Share" and then on clicking on it, it would open a modal with more info on sharing (similar to the example linked above)?

**Comment by yarikoptic** [comment]
good point -- I have missed that one. I think we could indeed just "generalize" that one into Share (with icon to the share arrow) and add "Link" within that modal drop down.

**Comment by waxlamp** [comment]
I thought this was quite a different thing but maybe I misunderstood: I thought the ask here was to provide a "share on Twitter" button that would take you to Twitter and pre-fill a Tweet with a link to the dandiset. That's different from both the shareable link and the citation, right?

**Comment by yarikoptic** [comment]
"Shareable link" and "share on Twitter" have a thing in common - "share", thus the idea to group.

Citation - is related but different beast. It might later be extended with different formats for that citation (bib, ris, etc). Rendered text version of citation - could be even present in both drop downs - after all ppl might share the citation (via email etc)

**Comment by yarikoptic** [comment]
@waxlamp clock on Share icon on that biorxiv link in the original description to see what I meant above

**Comment by waxlamp** [comment]
Got it. I'm not sure what I thought I was reading yesterday, but this makes sense today 😄

**Comment by sanuann** [comment]
when we share on social media, say Twitter, do we want that to open on a separate tab or the same tab?

**Comment by waxlamp** [comment]
My guess is, separate tab, but I would try to follow what other services with a "share on social media" function do.

**Comment by mvandenburgh** [comment]
afaik, most services that have this sort of functionality open it in a separate tab. There's also Vue packages that handle this for you like https://www.npmjs.com/package/vue-socials, where you wouldn't even have to worry about implementing "open in new tab" support

**Comment by sanuann** [comment]
thanks!
