### ISSUE TITLE
Copying DANDI version to clipboard is broken

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandiarchive#883]
After clicking the version tag in the footer (underneath `© 2021 DANDI`), a tooltip pops up and says that the link has been copied to the clipboard, but it doesn't actually do that.

Is there a need for this functionality? Automatically copying the link after the user clicks it without any sort of prompt seems like strange behavior. I think we could just strip out the copying functionality and leave it to users to right click and copy it themselves if needed.

**Comment by waxlamp** [comment]
> After clicking the version tag in the footer (underneath `© 2021 DANDI`), a tooltip pops up and says that the link has been copied to the clipboard, but it doesn't actually do that.
> 

When I click on it, it opens the commit in GitHub in a new window. That's the intended behavior right?

> Is there a need for this functionality? Automatically copying the link after the user clicks it without any sort of prompt seems like strange behavior. I think we could just strip out the copying functionality and leave it to users to right click and copy it themselves if needed.

Yes, let's remove the tooltip about copying to the clipboard.
