### ISSUE TITLE
something special about layout on dandisets 21 and 22

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandiarchive#947]
error for [000021](https://gui.dandiarchive.org/#/dandiset/000021), reported on https://github.com/dandi/dandi-api-webshots/#000021 for "Edit metadata" action, and I below error relates to clicking that "Edit metadata" (didn't traceback the selenium script we have):

```
Message: unknown error: Element <button type="button" class="v-btn v-btn--depressed v-btn--flat v-btn--outlined theme--light v-size--default" id="view-edit-metadata" style="width: 100%;">...</button> is not clickable at point (84, 1382). Other element would receive the click: <div data-v-3113d48c="" class="Cookie Cookie--bottom Cookie--blood-orange">...</div>
  (Session info: headless chrome=73.0.3683.75)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.0-0.bpo.9-amd64 x86_64)
```

may be something immediately comes to your mind @mvandenburgh ?  What would be that "Cookie" class-ed `div`?

I just wonder why only for those 2 dandisets - anything special about them or just may be our selenium driver gets "tired" by then? ;)

The probably relevant selenium code in question is https://github.com/dandi/dandi-api-webshots-tools/blob/master/make_webshots.py#L246 (not sure if comment should be just removed now that it refer by id).

**Comment by waxlamp** [comment]
I don't think this is a bug--please re-open if you feel otherwise.
