### ISSUE TITLE
Web interface listing invalid download commands for specific versions

### ISSUE THREAD

**Issue by jwodder** [dandi/dandiarchive#957]
If one views the page on gui.dandiarchive.org for a Dandiset with one or more published versions (e.g., https://gui.dandiarchive.org/#/dandiset/000023), clicks on the "Download" button, selects "Download a different version", selects "Other version" and then any non-draft version, a command like the following is then displayed:

    dandi download DANDI:000023/0.210914.1900

However, this command will not work, as the client attempts to resolve `DANDI:*` resource identifiers by prepending `https://identifiers.org/` to them, and https://identifiers.org/DANDI:000023/0.210914.1900 does not exist.

EDIT: [According to @satra](https://github.com/dandi/helpdesk/issues/37#issuecomment-962037772), the identifiers.org URL is invalid due to a bug on their end, and it becomes valid by lowercasing "DANDI:".

**Comment by jwodder** [comment]
This is addressed at the client level by https://github.com/dandi/dandi-cli/pull/829

**Comment by waxlamp** [comment]
> EDIT: [According to @satra](https://github.com/dandi/helpdesk/issues/37#issuecomment-962037772), the identifiers.org URL is invalid due to a bug on their end, and it becomes valid by lowercasing "DANDI:".

The bug is that such URIs are supposed to be case-insensitive, is that right @satra?
