### ISSUE TITLE
Add indexing to dandiset ID find

### ISSUE THREAD

**Issue by AlmightyYakob** [dandi/dandiarchive#96]
Raised by

https://github.com/dandi/dandiarchive/pull/94/files/b30fd0645be52c1010b3a08bc258e8e50cfc9693#r385823584

**Comment by mgrauer** [comment]
Based on the current state of #120, the following fields would need to be indexed in the Girder Mongo `folder` collection:

 - `meta.dandiset.identifier`
 - `meta.dandiset.version`

but, `version` is still up for some debate as described in #105.

**Comment by mgrauer** [comment]
we only need to index this field `meta.dandiset.identifier`

**Comment by dchiquit** [comment]
Ensure the new index during plugin load
