### ISSUE TITLE
contributors metadata not accessible in edit mode

### ISSUE THREAD

**Issue by satra** [dandi/dandiarchive#962]
### Discussed in https://github.com/dandi/helpdesk/discussions/39

<div type='discussions-op-text'>

<sup>Originally posted by **h-mayorquin** November  9, 2021</sup>
Hi, so yesterday (2021-11-08) I succesfully added funding information from a variety of sources to a [repository](https://dandiarchive.org/dandiset/000166/draft) This information was added in metadata -> contributors -> organization.  The results are displayed correctly on the main page
![fuding_correct](https://user-images.githubusercontent.com/6429509/140975374-2c4798f4-a634-41fd-a092-08f4add687cb.png)

However, when I try to access the edition tab in contributors to modify some of the data today (2021/11/09) I find that the information is not display and also can't not be access for edition:

![not_displaying_properly](https://user-images.githubusercontent.com/6429509/140975789-f0561f05-c0d5-4c87-836d-a7f3aad649f5.png)

The same problem is found in the subject matter of the dataset. Information is properly display in the main page but inability to edit or view in the metadata edition page.  

Has anyone encounter this problem before?</div>

**Comment by satra** [comment]
@mvandenburgh - i suspect this may be related to the schemaKey bug.

**Comment by h-mayorquin** [comment]
To add to this, I am also getting the following metadata errors:
![validation_errors](https://user-images.githubusercontent.com/6429509/141059580-b5b7a59b-d0d4-429c-8b16-e520b10bc6ca.png)

**Comment by satra** [comment]
@h-mayorquin - this above one is likely because contributor name was not entered as `Last, First`

**Comment by satra** [comment]
i'm going to close this issue as it was either fixed or i could not replicate in the specific dataset in question. let's reopen if the issue continues to persist.
