### ISSUE TITLE
Investigate if vjsf slots can be used in DLP redesign implementation

### ISSUE THREAD

**Issue by mvandenburgh** [dandi/dandiarchive#975]

**Comment by mvandenburgh** [comment]
![meditor](https://user-images.githubusercontent.com/37340715/146225854-917cfe0a-cbe9-4e0f-859c-72534ccb8c38.gif)

There's still some things that are unclear, but it looks like VJSF can generally support what we want to implement with the redesign. 

I've pushed the code for this here https://github.com/dandi/dandiarchive/commit/8e386b41bb1956b6cefc92db8ec88b3bc2e87506.
Some things in particular to note:

- https://github.com/dandi/dandiarchive/commit/8e386b41bb1956b6cefc92db8ec88b3bc2e87506#diff-dcd062cc7614a7dcb76f1f0216fc3d74f11251189dcbb7d173babfd7ed064931R302 This prop allows nested object cards to be edited inline rather than have a separate popup. I have yet to look into whether the '+' or delete buttons can be customized/moved to how they are in Jared's design.
- https://github.com/dandi/dandiarchive/commit/8e386b41bb1956b6cefc92db8ec88b3bc2e87506#diff-b06190e975ad9a4cc2514cff0027d4890b3b1d14b84f3dd0a9880088186131d1R10 This line is the trick that allows VJSF to render a single object from an array field, which was one of the main obstacles in getting this UI working.

The code is still unfinished and buggy (saving doesn't work properly yet, for example), but I believe these findings are sufficient enough to close this issue.

**Comment by satra** [comment]
very nice!
