### ISSUE TITLE
Dandiset metadata editor, when downloading metadata file, should use the file name `dandiset.yaml`

### ISSUE THREAD

**Issue by mgrauer** [dandi/dandiarchive#99]
Currently the file saves as `dandidata.yaml`.

**Comment by mgrauer** [comment]
When I said save,  I meant the name of the file that is downloaded.

**Comment by satra** [comment]
i would say it should also save into the dandiset folder as `dandiset.yaml`

**Comment by mgrauer** [comment]
That's a broader issue relating to how we manage metadata b/w the UI and the CLI. I had meant this issue to be much more narrowly scoped, but I named it poorly. I'll update the name now.
